-- Learn.ai JEE Mains Question Seed: Chemistry (Inorganic) Units 9-12
-- 21 questions per subconcept (7 easy, 7 medium, 7 hard)
-- Correct answers distributed across option1-4
-- JEE Mains level difficulty
-- Every answer verified before writing

INSERT INTO questions (question_text, option1, option2, option3, option4, correct_answer, solution_text, concept_id, difficulty_tier, source, status) VALUES

-- ============================================================
-- c_periodic_law_table (7 easy, 7 medium, 7 hard = 21)
-- Modern periodic law, periodic table, s/p/d/f blocks
-- ============================================================
('The modern periodic law states that the properties of elements are a periodic function of their', 'Atomic mass', 'Atomic number', 'Number of neutrons', 'Electron affinity', 'option2', 'Moseley (1913): properties are periodic functions of atomic number ($Z$), not atomic mass (Mendeleev).', 'c_periodic_law_table', 1, 'JEE Mains Prep', 'approved'),
('The long form of the periodic table has', '7 periods and 8 groups', '7 periods and 18 groups', '6 periods and 18 groups', '8 periods and 18 groups', 'option2', '7 horizontal periods (rows) and 18 vertical groups (columns).', 'c_periodic_law_table', 1, 'JEE Mains Prep', 'approved'),
('Elements in the $s$-block of the periodic table have their valence electrons in', '$p$ orbitals', '$s$ orbitals', '$d$ orbitals', '$f$ orbitals', 'option2', '$s$-block: Groups 1 (alkali metals) and 2 (alkaline earth metals) + He. Valence electrons fill $s$ orbitals.', 'c_periodic_law_table', 1, 'JEE Mains Prep', 'approved'),
('The $d$-block elements are also called', 'Representative elements', 'Transition elements', 'Inner transition elements', 'Noble gases', 'option2', '$d$-block: Groups 3-12. Called transition elements because they bridge $s$- and $p$-blocks.', 'c_periodic_law_table', 1, 'JEE Mains Prep', 'approved'),
('The $f$-block elements include', 'Halogens and noble gases', 'Lanthanoids and actinoids', 'Alkali metals', 'Chalcogens', 'option2', '$f$-block: lanthanoids (4$f$) and actinoids (5$f$). Placed separately at the bottom of the table.', 'c_periodic_law_table', 1, 'JEE Mains Prep', 'approved'),
('Elements in the same group have', 'The same number of electron shells', 'Similar chemical properties due to the same number of valence electrons', 'The same atomic mass', 'The same number of neutrons', 'option2', 'Same group $=$ same valence electron configuration $=$ similar chemistry. E.g., Group 1: all have $ns^1$.', 'c_periodic_law_table', 1, 'JEE Mains Prep', 'approved'),
('The element with atomic number $35$ belongs to', 'Period 3, Group 17', 'Period 4, Group 17', 'Period 4, Group 15', 'Period 3, Group 15', 'option2', '$Z = 35$: [Ar] $3d^{10}4s^24p^5$. Period 4 (4th shell), Group 17 (halogens). This is bromine (Br).', 'c_periodic_law_table', 1, 'JEE Mains Prep', 'approved'),
('The element with configuration [Ar] $3d^5 4s^1$ belongs to', 'Group 5', 'Group 6', 'Group 7', 'Group 1', 'option2', 'Total valence electrons in $d$ and $s$: $5 + 1 = 6$. Group 6. This is chromium (Cr, $Z = 24$).', 'c_periodic_law_table', 2, 'JEE Mains Prep', 'approved'),
('The number of elements in the 3rd period is', '$2$', '$8$', '$18$', '$32$', 'option2', 'Period 3: Na to Ar. $3s$ (2) + $3p$ (6) = 8 elements.', 'c_periodic_law_table', 2, 'JEE Mains Prep', 'approved'),
('The maximum number of elements in the 4th period is', '$8$', '$18$', '$32$', '$2$', 'option2', 'Period 4: K to Kr. $4s$ (2) + $3d$ (10) + $4p$ (6) = 18 elements.', 'c_periodic_law_table', 2, 'JEE Mains Prep', 'approved'),
('Diagonal relationships in the periodic table exist between', 'Li and Mg, Be and Al, B and Si', 'Na and K, Mg and Ca', 'F and Cl, O and S', 'He and Ne', 'option1', 'Diagonal pairs have similar charge/size ratios: Li-Mg, Be-Al, B-Si. They show similar chemical properties.', 'c_periodic_law_table', 2, 'JEE Mains Prep', 'approved'),
('The element with configuration [Kr] $4d^{10}5s^25p^3$ is in', 'Group 13', 'Group 15', 'Group 17', 'Group 5', 'option2', 'Valence: $5s^25p^3$ = 5 electrons in $s+p$. Group 15. This is antimony (Sb, $Z = 51$).', 'c_periodic_law_table', 2, 'JEE Mains Prep', 'approved'),
('Mendeleev''s periodic table was based on atomic mass and had limitations including', 'It was too accurate', 'The position of isotopes and the anomalous position of certain element pairs (e.g., Ar-K, Co-Ni)', 'It had too few elements', 'It was based on atomic number', 'option2', 'Ar ($40$) before K ($39$) by mass, but K should come after Ar by properties. Resolved by Moseley''s atomic number.', 'c_periodic_law_table', 2, 'JEE Mains Prep', 'approved'),
('The metalloids (semi-metals) in the periodic table are found', 'Along the zig-zag line separating metals and non-metals', 'Only in Group 1', 'Only in the $d$-block', 'In the $f$-block', 'option1', 'Metalloids (B, Si, Ge, As, Sb, Te, Po) have properties intermediate between metals and non-metals.', 'c_periodic_law_table', 2, 'JEE Mains Prep', 'approved'),
('The aufbau order of orbital filling ($1s, 2s, 2p, 3s, 3p, 4s, 3d, ...$) explains why', 'The 4th period has 18 elements (including $3d$ transition metals)', 'All periods have 8 elements', 'The $f$-block comes before the $d$-block', 'Noble gases have incomplete shells', 'option1', '$4s$ fills before $3d$ (lower $n+l$). This inserts 10 $d$-block elements into period 4, giving 18 total.', 'c_periodic_law_table', 3, 'JEE Mains Prep', 'approved'),
('The element with $Z = 114$ (flerovium) is expected to be in', 'Group 14, Period 7', 'Group 4, Period 7', 'Group 14, Period 6', 'Group 18, Period 7', 'option1', '[Rn] $5f^{14}6d^{10}7s^27p^2$. Period 7, Group 14 (same group as C, Si, Ge, Sn, Pb).', 'c_periodic_law_table', 3, 'JEE Mains Prep', 'approved'),
('The first ionization energy generally increases across a period because', 'Electron affinity decreases', 'Atomic size increases', 'Nuclear charge increases while shielding remains roughly constant', 'Electronegativity decreases', 'option3', 'Across a period: $Z_{eff}$ increases, atomic radius decreases, electrons are held more tightly.', 'c_periodic_law_table', 3, 'JEE Mains Prep', 'approved'),
('The anomalous position of hydrogen in the periodic table is because', 'It is a noble gas', 'It shows properties of both Group 1 (alkali metals) and Group 17 (halogens)', 'It belongs to the $d$-block', 'It has no electrons', 'option2', 'H: $1s^1$ like alkali metals (loses 1e$^-$), but also gains 1e$^-$ like halogens. Unique element.', 'c_periodic_law_table', 3, 'JEE Mains Prep', 'approved'),
('The secondary periodicity observed in Groups 13-16 is due to', 'The noble gas configuration', 'The large size of atoms', 'The high electronegativity', 'The poor shielding effect of $d$ and $f$ electrons', 'option4', 'After filling $3d$ (or $4f$), the poor shielding causes higher $Z_{eff}$, affecting properties of subsequent elements (e.g., Ga, In, Tl show irregular trends).', 'c_periodic_law_table', 3, 'JEE Mains Prep', 'approved'),
('The knight''s move relationship in the periodic table is observed between', 'Noble gases', 'Adjacent elements', 'Elements in the same group', 'Elements diagonally separated by one period and two groups (e.g., Zn-Sn, Ga-Sb)', 'option4', 'Knight''s move pairs show similar properties due to similar charge/size ratios after $d$-block contraction.', 'c_periodic_law_table', 3, 'JEE Mains Prep', 'approved'),
('The theoretical maximum number of elements in the 8th period (if it existed) would be', '$18$', '$32$', '$50$', '$72$', 'option3', 'Period 8: $8s$ (2) + $5g$ (18) + $6f$ (14) + $7d$ (10) + $8p$ (6) = 50. (Though relativistic effects may alter this.)','c_periodic_law_table', 3, 'JEE Mains Prep', 'approved'),

-- ============================================================
-- c_periodic_trends (7 easy, 7 medium, 7 hard = 21)
-- Atomic/ionic radii, IE, EA, electronegativity, oxidation states
-- ============================================================
('Atomic radius generally _____ across a period (left to right).', 'Increases', 'Decreases', 'Remains constant', 'First increases then decreases', 'option2', 'Across a period: increasing $Z_{eff}$ pulls electrons closer, decreasing atomic radius.', 'c_periodic_trends', 1, 'JEE Mains Prep', 'approved'),
('Atomic radius generally _____ down a group.', 'Decreases', 'Increases', 'Remains constant', 'First decreases then increases', 'option2', 'Down a group: new electron shells are added, increasing the distance from the nucleus.', 'c_periodic_trends', 1, 'JEE Mains Prep', 'approved'),
('Ionization energy generally _____ across a period.', 'Decreases', 'Increases', 'Remains constant', 'Oscillates randomly', 'option2', 'Higher $Z_{eff}$ and smaller radius make it harder to remove an electron across a period.', 'c_periodic_trends', 1, 'JEE Mains Prep', 'approved'),
('Electronegativity generally _____ across a period.', 'Decreases', 'Increases', 'Remains constant', 'Is zero', 'option2', 'Fluorine (top-right) is the most electronegative. Electronegativity increases across a period and up a group.', 'c_periodic_trends', 1, 'JEE Mains Prep', 'approved'),
('The element with the highest first ionization energy in Period 2 is', 'Li', 'Be', 'N', 'Ne', 'option4', 'Noble gases have the highest IE in their period due to completely filled shells. Ne: $2081\;\text{kJ/mol}$.', 'c_periodic_trends', 1, 'JEE Mains Prep', 'approved'),
('Electron gain enthalpy (electron affinity) is most negative for', 'Noble gases', 'Halogens', 'Alkali metals', 'Alkaline earth metals', 'option2', 'Halogens need just 1 electron to complete their octet. Cl has the most negative EA ($-349\;\text{kJ/mol}$).', 'c_periodic_trends', 1, 'JEE Mains Prep', 'approved'),
('The metallic character of elements _____ down a group.', 'Decreases', 'Increases', 'Remains constant', 'Becomes zero', 'option2', 'Down a group: lower IE, easier to lose electrons, more metallic. E.g., C (non-metal) $\to$ Pb (metal) in Group 14.', 'c_periodic_trends', 1, 'JEE Mains Prep', 'approved'),
('The first ionization energy of N ($1402\;\text{kJ/mol}$) is higher than that of O ($1314\;\text{kJ/mol}$) because', 'O has a noble gas configuration', 'O is larger than N', 'N has more protons', 'N has a half-filled $2p^3$ configuration (extra stability)', 'option4', 'Half-filled $2p^3$ in N has extra exchange energy stabilization. Removing an electron disrupts this, requiring more energy.', 'c_periodic_trends', 2, 'JEE Mains Prep', 'approved'),
('The first IE of Be ($900\;\text{kJ/mol}$) is higher than that of B ($801\;\text{kJ/mol}$) because', 'Be has a fully filled $2s^2$ subshell (extra stability)', 'B is larger', 'Be has more neutrons', 'B has a noble gas configuration', 'option1', 'Fully filled $2s^2$ in Be is more stable. B loses a $2p$ electron (less tightly held, easier to remove).', 'c_periodic_trends', 2, 'JEE Mains Prep', 'approved'),
('The electron gain enthalpy of fluorine is less negative than that of chlorine because', 'Cl has fewer electrons', 'F is larger than Cl', 'F is very small, causing strong electron-electron repulsion in the compact $2p$ shell', 'F has a positive EA', 'option3', 'F: tiny atom, adding an electron to the already crowded $2p$ shell causes significant repulsion. Cl ($3p$) has more space.', 'c_periodic_trends', 2, 'JEE Mains Prep', 'approved'),
('The ionic radius of Na$^+$ is _____ the atomic radius of Na.', 'Larger than', 'Smaller than', 'Equal to', 'Unrelated to', 'option2', 'Cations are smaller than their parent atoms (lost an electron shell or reduced shielding). Na: $186\;\text{pm}$, Na$^+$: $95\;\text{pm}$.', 'c_periodic_trends', 2, 'JEE Mains Prep', 'approved'),
('The ionic radius of Cl$^-$ is _____ the atomic radius of Cl.', 'Smaller than', 'Larger than', 'Equal to', 'Zero', 'option2', 'Anions are larger than their parent atoms (extra electron increases repulsion, expanding the electron cloud). Cl: $99\;\text{pm}$, Cl$^-$: $181\;\text{pm}$.', 'c_periodic_trends', 2, 'JEE Mains Prep', 'approved'),
('Among Na$^+$, Mg$^{2+}$, Al$^{3+}$, and Si$^{4+}$ (isoelectronic with Ne), the smallest ion is', 'Na$^+$', 'Mg$^{2+}$', 'Al$^{3+}$', 'Si$^{4+}$', 'option4', 'All have 10 electrons. Higher nuclear charge ($Z$) pulls electrons closer. Si$^{4+}$ ($Z = 14$) is smallest.', 'c_periodic_trends', 2, 'JEE Mains Prep', 'approved'),
('The second ionization energy of Na is much higher than the first because', 'Na has only one electron', 'The second electron must be removed from a noble gas core ($2p^6$)', 'The second electron is in the $1s$ orbital', 'Na$^+$ is larger than Na', 'option2', 'Na: $[Ne]3s^1$. First IE removes the $3s$ electron. Second IE must break into the stable Ne core — much harder.', 'c_periodic_trends', 2, 'JEE Mains Prep', 'approved'),
('The correct order of atomic radii is', 'Li $>$ Na $>$ K', 'K $>$ Na $>$ Li', 'Na $>$ K $>$ Li', 'Li $>$ K $>$ Na', 'option2', 'Down Group 1: K ($227\;\text{pm}$) $>$ Na ($186\;\text{pm}$) $>$ Li ($152\;\text{pm}$).', 'c_periodic_trends', 3, 'JEE Mains Prep', 'approved'),
('The correct order of ionization energy is', 'B $>$ Be $>$ C', 'Be $>$ B $>$ C', 'C $>$ Be $>$ B', 'C $>$ B $>$ Be', 'option3', 'IE: C ($1086$) $>$ Be ($900$) $>$ B ($801$). Be $>$ B due to $2s^2$ stability. C $>$ Be due to higher $Z_{eff}$.', 'c_periodic_trends', 3, 'JEE Mains Prep', 'approved'),
('The inert pair effect explains why', 'Heavier $p$-block elements prefer oxidation states 2 less than the group valence (e.g., Tl$^+$ over Tl$^{3+}$, Pb$^{2+}$ over Pb$^{4+}$)', 'All elements show the same oxidation state', 'Noble gases are inert', 'Transition metals have variable oxidation states', 'option1', 'The $ns^2$ electrons become reluctant to participate in bonding for heavier elements due to poor shielding by $d/f$ electrons and relativistic effects.', 'c_periodic_trends', 3, 'JEE Mains Prep', 'approved'),
('Lanthanoid contraction refers to', 'The contraction of $s$-block elements', 'The expansion of lanthanoids', 'The steady decrease in atomic/ionic radii across the lanthanoid series due to poor shielding by $4f$ electrons', 'The increase in size of actinoids', 'option3', '$4f$ electrons shield poorly. Increasing $Z$ across the series contracts the radii. This affects post-lanthanoid elements (Hf has similar radius to Zr).', 'c_periodic_trends', 3, 'JEE Mains Prep', 'approved'),
('The electron gain enthalpy of noble gases is', 'Highly negative', 'Positive (endothermic)', 'Zero', 'Slightly negative', 'option2', 'Noble gases have completely filled shells. Adding an electron requires placing it in a higher energy shell — unfavourable (positive EA).', 'c_periodic_trends', 3, 'JEE Mains Prep', 'approved'),
('Among O$^{2-}$, F$^-$, Na$^+$, Mg$^{2+}$ (all isoelectronic with Ne), the correct order of ionic radii is', 'Mg$^{2+} >$ Na$^+ >$ F$^- >$ O$^{2-}$', 'O$^{2-} >$ F$^- >$ Na$^+ >$ Mg$^{2+}$', 'F$^- >$ O$^{2-} >$ Na$^+ >$ Mg$^{2+}$', 'Na$^+ >$ Mg$^{2+} >$ F$^- >$ O$^{2-}$', 'option2', 'All have 10 electrons. Lower $Z$ = less pull on electrons = larger radius. O ($Z=8$) $>$ F ($9$) $>$ Na ($11$) $>$ Mg ($12$).', 'c_periodic_trends', 3, 'JEE Mains Prep', 'approved'),
('The Allred-Rochow electronegativity scale is based on', 'Electron affinity', 'Ionization energy', 'The electrostatic force exerted by the nucleus on valence electrons', 'Bond dissociation energy', 'option3', 'Allred-Rochow: $\chi = 0.359(Z_{eff}/r^2) + 0.744$. Based on the force experienced by valence electrons.', 'c_periodic_trends', 3, 'JEE Mains Prep', 'approved'),

-- ============================================================
-- c_p_block_general (7 easy, 7 medium, 7 hard = 21)
-- Group 13-18: electronic configuration, general trends
-- ============================================================
('The general outer electronic configuration of Group 13 elements is', '$ns^2np^3$', '$ns^2np^2$', '$ns^2np^1$', '$ns^2np^5$', 'option3', 'Group 13 (B, Al, Ga, In, Tl): $ns^2np^1$. They have 3 valence electrons.', 'c_p_block_general', 1, 'JEE Mains Prep', 'approved'),
('The halogens belong to Group', '15', '16', '17', '18', 'option3', 'Group 17: F, Cl, Br, I, At. Configuration: $ns^2np^5$. One electron short of noble gas configuration.', 'c_p_block_general', 1, 'JEE Mains Prep', 'approved'),
('Noble gases belong to Group', '1', '14', '17', '18', 'option4', 'Group 18: He, Ne, Ar, Kr, Xe, Rn. Completely filled valence shells ($ns^2np^6$, except He: $1s^2$).', 'c_p_block_general', 1, 'JEE Mains Prep', 'approved'),
('The most electronegative element among the $p$-block elements is', 'Oxygen', 'Fluorine', 'Chlorine', 'Nitrogen', 'option2', 'Fluorine ($\chi = 3.98$) is the most electronegative element in the entire periodic table.', 'c_p_block_general', 1, 'JEE Mains Prep', 'approved'),
('The oxidation states shown by Group 15 elements include', '$+1$ only', '$-1$ to $+7$', '$-3$ to $+5$', '$-2$ to $+6$', 'option3', 'Group 15 (N, P, As, Sb, Bi): $-3$ (NH$_3$), $+3$ (PCl$_3$), $+5$ (PCl$_5$). Range: $-3$ to $+5$.', 'c_p_block_general', 1, 'JEE Mains Prep', 'approved'),
('The chalcogens (Group 16) include', 'F, Cl, Br, I', 'O, S, Se, Te, Po', 'N, P, As, Sb', 'B, Al, Ga, In', 'option2', 'Group 16: oxygen family. Configuration: $ns^2np^4$.', 'c_p_block_general', 1, 'JEE Mains Prep', 'approved'),
('Down Group 17, the boiling points of halogens', 'Decrease', 'Increase', 'Remain constant', 'First increase then decrease', 'option2', 'F$_2$ (gas) $\to$ Cl$_2$ (gas) $\to$ Br$_2$ (liquid) $\to$ I$_2$ (solid). Increasing London forces with molecular size.', 'c_p_block_general', 1, 'JEE Mains Prep', 'approved'),
('The allotropes of carbon include', 'Diamond, graphite, fullerene, and graphene', 'Only diamond', 'Only graphite', 'Carbon has no allotropes', 'option1', 'Carbon has many allotropes: diamond ($sp^3$), graphite ($sp^2$ layers), fullerenes (C$_{60}$), graphene, carbon nanotubes.', 'c_p_block_general', 2, 'JEE Mains Prep', 'approved'),
('The tendency to form catenated compounds (chains) is highest for', 'Nitrogen', 'Silicon', 'Carbon', 'Oxygen', 'option3', 'C-C bond is very strong ($347\;\text{kJ/mol}$). Carbon forms extensive chains, rings, and networks. Si-Si is weaker.', 'c_p_block_general', 2, 'JEE Mains Prep', 'approved'),
('Nitrogen exists as N$_2$ (triple bond) while phosphorus exists as P$_4$. This is because', 'N is larger than P', 'P is more electronegative', 'N forms strong $p\pi$-$p\pi$ bonds; P cannot due to its larger size', 'P forms triple bonds more easily', 'option3', 'Small N atoms overlap $2p$ orbitals effectively for $\pi$ bonding. Larger P atoms cannot, so P forms single bonds in P$_4$ tetrahedra.', 'c_p_block_general', 2, 'JEE Mains Prep', 'approved'),
('The oxidizing power of halogens decreases in the order', 'F $>$ Cl $>$ Br $>$ I', 'I $>$ Br $>$ Cl $>$ F', 'Cl $>$ F $>$ Br $>$ I', 'All are equal', 'option1', 'F is the strongest oxidizing agent (highest electronegativity, highest reduction potential). I is the weakest.', 'c_p_block_general', 2, 'JEE Mains Prep', 'approved'),
('XeF$_2$, XeF$_4$, and XeF$_6$ are examples of', 'Transition metal compounds', 'Halogen compounds', 'Noble gas compounds', 'Organic compounds', 'option3', 'Xe (large, polarizable) forms compounds with F (most electronegative). Discovered by Bartlett (1962).', 'c_p_block_general', 2, 'JEE Mains Prep', 'approved'),
('The acidic strength of hydrides of Group 16 increases as', 'H$_2$O $>$ H$_2$S $>$ H$_2$Se $>$ H$_2$Te', 'H$_2$Te $>$ H$_2$Se $>$ H$_2$S $>$ H$_2$O', 'All are equally acidic', 'H$_2$O is the strongest acid', 'option2', 'Down the group: bond strength decreases (H-X bond weaker), making it easier to release H$^+$. H$_2$Te is the strongest acid.', 'c_p_block_general', 2, 'JEE Mains Prep', 'approved'),
('The thermal stability of hydrides of Group 15 decreases as', 'PH$_3 >$ NH$_3 >$ AsH$_3$', 'BiH$_3 >$ SbH$_3 >$ AsH$_3 >$ PH$_3 >$ NH$_3$', 'All are equally stable', 'NH$_3 >$ PH$_3 >$ AsH$_3 >$ SbH$_3 >$ BiH$_3$', 'option4', 'Down the group: bond strength decreases (larger atom, weaker overlap). NH$_3$ is most stable; BiH$_3$ decomposes easily.', 'c_p_block_general', 2, 'JEE Mains Prep', 'approved'),
('Ozone (O$_3$) is a powerful oxidizing agent because', 'It has no reactivity', 'It is very stable', 'It is a reducing agent', 'It readily decomposes to give nascent oxygen: O$_3 \to$ O$_2$ + [O]', 'option4', 'Nascent oxygen [O] is highly reactive. O$_3$ oxidizes PbS to PbSO$_4$, KI to I$_2$, etc.', 'c_p_block_general', 3, 'JEE Mains Prep', 'approved'),
('Interhalogen compounds (e.g., ClF$_3$, BrF$_5$, IF$_7$) are formed because', 'Only F forms interhalogens', 'All halogens are identical', 'Larger halogens can accommodate more smaller halogen atoms due to available $d$ orbitals', 'Interhalogens do not exist', 'option3', 'The larger halogen (central) uses $d$ orbitals for expanded octet. Maximum: IF$_7$ (I is large enough for 7 F atoms).', 'c_p_block_general', 3, 'JEE Mains Prep', 'approved'),
('The structure of H$_3$PO$_4$ (orthophosphoric acid) has', '3 P-OH bonds and 1 P=O bond (tribasic acid)', '4 P-OH bonds', '2 P-OH bonds and 2 P=O bonds', '1 P-OH bond and 3 P=O bonds', 'option1', 'H$_3$PO$_4$: P is $sp^3$ hybridized. 3 P-OH groups (acidic H) + 1 P=O. Tribasic acid.', 'c_p_block_general', 3, 'JEE Mains Prep', 'approved'),
('The basicity (number of replaceable H atoms) of H$_3$PO$_3$ (phosphorous acid) is', '$3$', '$2$', '$1$', '$0$', 'option2', 'H$_3$PO$_3$: 2 P-OH bonds + 1 P-H bond (non-acidic) + 1 P=O. Only 2 replaceable H atoms. Dibasic.', 'c_p_block_general', 3, 'JEE Mains Prep', 'approved'),
('Sulphuric acid acts as a dehydrating agent because', 'It has a strong affinity for water and can remove H and OH from compounds', 'It is a weak acid', 'It is volatile', 'It is a reducing agent', 'option1', 'Conc. H$_2$SO$_4$ dehydrates sugar (C$_{12}$H$_{22}$O$_{11} \to$ 12C + 11H$_2$O), formic acid (HCOOH $\to$ CO + H$_2$O), etc.', 'c_p_block_general', 3, 'JEE Mains Prep', 'approved'),
('The structure of SF$_6$ makes it extremely stable and inert because', 'The 6 F atoms completely shield the central S, and the S-F bonds are very strong', 'SF$_6$ is ionic', 'S has no $d$ orbitals', 'F is a weak oxidizer', 'option1', 'Steric protection by 6 F atoms + strong S-F bonds + no lone pairs on S = kinetically inert despite being thermodynamically reactive.', 'c_p_block_general', 3, 'JEE Mains Prep', 'approved'),
('The brown ring test for NO$_3^-$ involves the formation of', 'FeSO$_4$', 'Fe$_2$O$_3$', '[Fe(H$_2$O)$_5$NO]$^{2+}$ (brown complex)', 'Fe(OH)$_3$', 'option3', 'FeSO$_4$ + NO (from HNO$_3$ + Fe$^{2+}$) $\to$ [Fe(H$_2$O)$_5$NO]$^{2+}$ (brown ring at the junction of two layers).', 'c_p_block_general', 3, 'JEE Mains Prep', 'approved'),

-- ============================================================
-- c_p_block_first_element (7 easy, 7 medium, 7 hard = 21)
-- Unique behaviour of first element in each group
-- ============================================================
('The first element of each $p$-block group differs from the rest because', 'It has $d$ orbitals', 'It is always a metal', 'It has a small size, high electronegativity, and no $d$ orbitals available for bonding', 'It is always a gas', 'option3', 'Small size + high charge density + absence of $d$ orbitals = unique chemistry (e.g., N vs P, O vs S, F vs Cl).', 'c_p_block_first_element', 1, 'JEE Mains Prep', 'approved'),
('Nitrogen cannot expand its octet (unlike P) because', 'N has $d$ orbitals', 'N is too large', 'N has no $d$ orbitals in its valence shell', 'N is a metal', 'option3', 'N ($n = 2$): only $2s$ and $2p$ available. P ($n = 3$): $3d$ orbitals available for expanded octet (e.g., PCl$_5$).', 'c_p_block_first_element', 1, 'JEE Mains Prep', 'approved'),
('Oxygen forms strong $p\pi$-$p\pi$ double bonds (O=O) while sulphur prefers single bonds (S$_8$) because', 'O cannot form double bonds', 'S is more electronegative', 'O is small enough for effective lateral $2p$ overlap; S is too large', 'S has no lone pairs', 'option3', 'Small $2p$ orbitals of O overlap well laterally. Larger $3p$ orbitals of S overlap poorly for $\pi$ bonds.', 'c_p_block_first_element', 1, 'JEE Mains Prep', 'approved'),
('Fluorine is the most reactive halogen because', 'It has the weakest F-F bond and highest electronegativity', 'It has the strongest F-F bond', 'It is the largest halogen', 'It has $d$ orbitals', 'option1', 'F-F bond is weak ($159\;\text{kJ/mol}$) due to lone pair repulsion in the tiny molecule. High EA drives reactivity.', 'c_p_block_first_element', 1, 'JEE Mains Prep', 'approved'),
('Carbon forms strong catenated chains while silicon does not because', 'C-C bonds ($347\;\text{kJ/mol}$) are much stronger than Si-Si bonds ($226\;\text{kJ/mol}$)', 'Si is smaller than C', 'C cannot form chains', 'Si-Si bonds are stronger', 'option1', 'Stronger C-C bonds + resistance to oxidation = extensive catenation. Si-O bonds are stronger than Si-Si, so Si prefers silicates.', 'c_p_block_first_element', 1, 'JEE Mains Prep', 'approved'),
('Boron is a metalloid while aluminium is a metal because', 'Al has higher IE than B', 'Al is smaller than B', 'B has $d$ orbitals', 'B has very high ionization energy and small size, making it hard to form B$^{3+}$ ions', 'option4', 'B: very small, high IE ($801\;\text{kJ/mol}$). Forms covalent compounds. Al: larger, lower IE, forms Al$^{3+}$ ions.', 'c_p_block_first_element', 1, 'JEE Mains Prep', 'approved'),
('The anomalous properties of the first element in each group are primarily due to', 'Metallic character', 'Large size', 'Low electronegativity', 'Small size, high charge density, and absence of $d$ orbitals', 'option4', 'These three factors make the first element unique: strong $\pi$ bonding, no expanded octet, high polarizing power.', 'c_p_block_first_element', 1, 'JEE Mains Prep', 'approved'),
('N forms NF$_3$ but not NF$_5$, while P forms both PF$_3$ and PF$_5$. This is because', 'P lacks $d$ orbitals', 'N is too large', 'N lacks $d$ orbitals for expanded octet', 'F is too small', 'option3', 'N: maximum covalency $= 4$ (using $2s$ and $2p$). P: can use $3d$ orbitals for covalency $= 5$ or $6$.', 'c_p_block_first_element', 2, 'JEE Mains Prep', 'approved'),
('CO$_2$ is a gas while SiO$_2$ is a solid because', 'Si is more electronegative', 'SiO$_2$ is lighter', 'CO$_2$ has stronger bonds', 'C forms $p\pi$-$p\pi$ double bonds with O; Si forms a 3D network of single bonds', 'option4', 'CO$_2$: discrete O=C=O molecules (weak intermolecular forces). SiO$_2$: each Si bonded to 4 O in a giant covalent network.', 'c_p_block_first_element', 2, 'JEE Mains Prep', 'approved'),
('HF is a weak acid while HCl, HBr, HI are strong acids because', 'The H-F bond is very strong ($568\;\text{kJ/mol}$), making dissociation difficult', 'HF is not an acid', 'HCl has a stronger bond than HF', 'F is less electronegative than Cl', 'option1', 'Despite F being most electronegative, the very strong H-F bond resists dissociation. HCl ($431$), HBr ($366$), HI ($298$) have weaker bonds.', 'c_p_block_first_element', 2, 'JEE Mains Prep', 'approved'),
('Lithium shows diagonal relationship with magnesium. Similarly, boron shows diagonal relationship with', 'Aluminium', 'Silicon', 'Carbon', 'Germanium', 'option2', 'B-Si diagonal pair: similar electronegativity and charge/size ratio. Both form covalent compounds, acidic oxides, and similar hydrides.', 'c_p_block_first_element', 2, 'JEE Mains Prep', 'approved'),
('The maximum covalency of nitrogen is', '$3$', '$4$', '$5$', '$6$', 'option2', 'N: $2s^22p^3$. Can form 3 bonds + 1 coordinate bond (using lone pair) = max covalency 4 (e.g., NH$_4^+$).', 'c_p_block_first_element', 2, 'JEE Mains Prep', 'approved'),
('Fluorine shows only $-1$ oxidation state while other halogens show $+1, +3, +5, +7$ because', 'F has $d$ orbitals', 'F is the least electronegative', 'F has no $d$ orbitals and is the most electronegative element', 'Other halogens cannot show positive states', 'option3', 'F: no $d$ orbitals + highest electronegativity = cannot be oxidized. Cl, Br, I use $d$ orbitals for positive states.', 'c_p_block_first_element', 2, 'JEE Mains Prep', 'approved'),
('The hydrides of the first element in each group are more stable than those of subsequent elements because', 'The first element forms stronger bonds with hydrogen due to better orbital overlap (similar size)', 'Subsequent elements form stronger bonds', 'The first element is always metallic', 'Hydrogen bonds only with the first element', 'option1', 'NH$_3 >$ PH$_3$, H$_2$O $>$ H$_2$S, HF $>$ HCl in thermal stability. Better $1s$-$np$ overlap for smaller $n$.', 'c_p_block_first_element', 2, 'JEE Mains Prep', 'approved'),
('The ability of nitrogen to form $p\pi$-$p\pi$ multiple bonds leads to the existence of', 'N$_2$ (triple bond), NO, NO$_2$, HNO$_3$ with N=O bonds', 'Only N$_2$', 'No multiple bonds', 'Only single bonds', 'option1', 'N forms extensive $\pi$ bonding: N$\equiv$N, N=O, N=N. P, As, Sb, Bi prefer single bonds and $d\pi$-$p\pi$ bonding.', 'c_p_block_first_element', 3, 'JEE Mains Prep', 'approved'),
('The first element anomaly explains why B$_2$H$_6$ (diborane) has a unique structure with', 'Normal 2c-2e bonds', '3-centre 2-electron (3c-2e) banana bonds because B has only 3 valence electrons and no $d$ orbitals', 'Ionic bonds', 'Metallic bonds', 'option2', 'B is electron-deficient (3 valence electrons, 4 orbitals). B$_2$H$_6$ uses 3c-2e bonds to compensate.', 'c_p_block_first_element', 3, 'JEE Mains Prep', 'approved'),
('The oxides of the first element in Group 14 (CO, CO$_2$) are gases, while those of Si (SiO$_2$) are solids. This pattern extends to', 'All first elements forming molecular compounds while heavier elements form giant structures', 'All elements forming gases', 'All elements forming solids', 'No pattern exists', 'option1', 'First elements: strong $\pi$ bonds $\to$ discrete molecules $\to$ low bp. Heavier: single bonds $\to$ polymeric/network structures $\to$ high bp.', 'c_p_block_first_element', 3, 'JEE Mains Prep', 'approved'),
('The Lewis acidity of BF$_3$ is less than BCl$_3$ despite F being more electronegative because', 'Cl is more electronegative', 'F donates electron density back to B via $p\pi$-$p\pi$ back-bonding, partially filling B''s empty orbital', 'BF$_3$ is not a Lewis acid', 'BCl$_3$ has $d$ orbitals', 'option2', 'F ($2p$) back-donates into B ($2p$) effectively (similar size). Cl ($3p$) is too large for effective back-bonding with B ($2p$).', 'c_p_block_first_element', 3, 'JEE Mains Prep', 'approved'),
('The first element of Group 15 (N) forms N$_2$O$_5$ as the highest oxide, which is', 'Neutral', 'Basic', 'Amphoteric', 'Acidic (anhydride of HNO$_3$)', 'option4', 'N$_2$O$_5$ + H$_2$O $\to$ 2HNO$_3$. Highest oxide of a non-metal is always acidic.', 'c_p_block_first_element', 3, 'JEE Mains Prep', 'approved'),
('The reluctance of nitrogen to form N$^{3-}$ ion (nitride) except with very electropositive metals is because', 'The third electron affinity of N is highly endothermic (adding electrons to an already negative ion)', 'N is too large', 'N has positive electron affinity', 'N$^{3-}$ is very stable', 'option1', 'N(g) + 3e$^- \to$ N$^{3-}$(g): overall endothermic. Only compensated by very high lattice energy with Li, Mg, etc.', 'c_p_block_first_element', 3, 'JEE Mains Prep', 'approved'),
('The maximum coordination number of boron in its compounds is typically', '$8$', '$6$', '$3$', '$4$', 'option4', 'B: $2s^22p^1$, 4 orbitals total ($2s + 3 \times 2p$). Max coordination $= 4$ (e.g., BF$_4^-$, B(OH)$_4^-$). No $d$ orbitals.', 'c_p_block_first_element', 3, 'JEE Mains Prep', 'approved'),

-- ============================================================
-- c_transition_elements (7 easy, 7 medium, 7 hard = 21)
-- Transition elements: configuration, occurrence, general trends
-- ============================================================
('Transition elements are defined as elements that have', 'Completely filled $d$ orbitals', 'Partially filled $d$ orbitals in their ground state or common oxidation states', 'No $d$ electrons', 'Only $s$ electrons', 'option2', 'IUPAC: elements with incomplete $d$ subshell in ground state or any common oxidation state. Groups 3-11 (some include 12).', 'c_transition_elements', 1, 'JEE Mains Prep', 'approved'),
('The general electronic configuration of first-row transition metals is', '$[\text{Ne}] 3d^{1-10} 4s^{1-2}$', '$[\text{Ar}] 4d^{1-10} 5s^{1-2}$', '$[\text{Ar}] 3d^{1-10} 3s^{1-2}$', '$[\text{Ar}] 3d^{1-10} 4s^{1-2}$', 'option4', 'First row: Sc ($3d^14s^2$) to Zn ($3d^{10}4s^2$). Exceptions: Cr ($3d^54s^1$), Cu ($3d^{10}4s^1$).', 'c_transition_elements', 1, 'JEE Mains Prep', 'approved'),
('Transition metals generally exhibit', 'No oxidation states', 'Only one oxidation state', 'Variable oxidation states', 'Only negative oxidation states', 'option3', 'Both $ns$ and $(n-1)d$ electrons can participate in bonding, giving multiple oxidation states.', 'c_transition_elements', 1, 'JEE Mains Prep', 'approved'),
('Transition metal compounds are often coloured because', 'They reflect all light', 'They are always black', 'They have no electrons', '$d$-$d$ electronic transitions absorb specific wavelengths of visible light', 'option4', 'In complexes, crystal field splitting creates energy gaps in $d$ orbitals. Electrons absorb light to jump between levels.', 'c_transition_elements', 1, 'JEE Mains Prep', 'approved'),
('Transition metals are good catalysts because', 'They are gases', 'They are inert', 'They have variable oxidation states and can provide surfaces for adsorption', 'They have no $d$ electrons', 'option3', 'Variable oxidation states allow electron transfer. Surface $d$ orbitals adsorb reactants, lowering activation energy.', 'c_transition_elements', 1, 'JEE Mains Prep', 'approved'),
('The most common oxidation state of iron is', '$+1$', '$+2$ and $+3$', '$+5$', '$+7$', 'option2', 'Fe: $[Ar]3d^64s^2$. Loses $4s^2$ for Fe$^{2+}$ ($3d^6$) or $4s^2 + 1d$ for Fe$^{3+}$ ($3d^5$, half-filled, extra stable).', 'c_transition_elements', 1, 'JEE Mains Prep', 'approved'),
('Zinc ($3d^{10}4s^2$) is sometimes not considered a true transition element because', 'It has a completely filled $d$ subshell in all oxidation states', 'It has no $d$ electrons', 'It is a non-metal', 'It shows variable oxidation states', 'option1', 'Zn: $3d^{10}$ in ground state and in Zn$^{2+}$ ($3d^{10}$). No partially filled $d$ orbitals in any common state.', 'c_transition_elements', 1, 'JEE Mains Prep', 'approved'),
('The highest oxidation state among first-row transition metals is shown by', 'Sc ($+3$)', 'Mn ($+7$)', 'Cu ($+2$)', 'Zn ($+2$)', 'option2', 'Mn: $+7$ in KMnO$_4$ (all 7 valence electrons: $3d^5 + 4s^2$). Oxidation state increases up to Mn, then decreases.', 'c_transition_elements', 2, 'JEE Mains Prep', 'approved'),
('The melting points of transition metals are generally high because', 'They are gases', 'They are non-metals', 'They have weak bonds', 'Strong metallic bonding due to involvement of both $s$ and $d$ electrons', 'option4', 'More unpaired $d$ electrons $\to$ stronger metallic bonding. Maximum near the middle of the series (e.g., W: $3422°\text{C}$).', 'c_transition_elements', 2, 'JEE Mains Prep', 'approved'),
('The atomic radii of transition metals across a period', 'Increase steadily', 'Decrease slightly then remain nearly constant', 'Decrease sharply', 'Show no trend', 'option2', 'Increasing $Z$ is offset by increasing $d$ electron shielding. Radii decrease slightly then level off.', 'c_transition_elements', 2, 'JEE Mains Prep', 'approved'),
('Transition metals form alloys because', 'Their atoms are of similar sizes and can substitute for each other in crystal lattices', 'They are gases', 'They do not mix', 'They have very different sizes', 'option1', 'Similar atomic radii allow substitutional solid solutions. E.g., brass (Cu-Zn), steel (Fe-C), bronze (Cu-Sn).', 'c_transition_elements', 2, 'JEE Mains Prep', 'approved'),
('The ionization energies of first-row transition metals increase gradually because', 'IE decreases across the series', 'They have no $d$ electrons', 'The added $d$ electrons shield the nuclear charge poorly', 'All have the same IE', 'option3', 'Poor shielding by $d$ electrons means $Z_{eff}$ increases slowly. IE increases gradually (not as sharply as in $s$/$p$ blocks).', 'c_transition_elements', 2, 'JEE Mains Prep', 'approved'),
('The $+2$ oxidation state is common for most first-row transition metals because', 'The $3d$ electrons are lost first', 'The two $4s$ electrons are easily lost', 'Only $s$ electrons exist', '$+2$ is the maximum state', 'option2', '$4s$ electrons are lost first (higher energy in the presence of $d$ electrons). Losing both $4s$ electrons gives $+2$.', 'c_transition_elements', 2, 'JEE Mains Prep', 'approved'),
('Cu$^{2+}$ is more stable than Cu$^+$ in aqueous solution because', 'The high hydration enthalpy of Cu$^{2+}$ (smaller, more charged) compensates for the second IE', 'Cu$^+$ has a noble gas configuration', 'Cu$^{2+}$ has a filled $d$ shell', 'Cu$^+$ is more hydrated', 'option1', 'Cu$^+$ ($3d^{10}$) is stable in solid state but disproportionates in water: 2Cu$^+ \to$ Cu + Cu$^{2+}$ because Cu$^{2+}$ hydration energy is much larger.', 'c_transition_elements', 2, 'JEE Mains Prep', 'approved'),
('The enthalpy of atomization of transition metals is highest near the middle of the series because', 'The atoms are smallest', 'Maximum number of unpaired $d$ electrons gives strongest metallic bonding', 'They have no $d$ electrons', 'They are gases', 'option2', 'Unpaired $d$ electrons contribute to metallic bonding. Maximum unpaired electrons at $d^5$ (Cr, Mn region).', 'c_transition_elements', 3, 'JEE Mains Prep', 'approved'),
('The standard electrode potentials ($E^\circ$) of first-row transition metals show an irregular trend because', 'They depend on sublimation energy, IE, and hydration energy — all of which vary irregularly', '$E^\circ$ depends only on atomic number', 'All have the same $E^\circ$', '$E^\circ$ increases linearly', 'option1', '$E^\circ$ involves: M(s) $\to$ M(g) (sublimation) $\to$ M$^{n+}$(g) (IE) $\to$ M$^{n+}$(aq) (hydration). Each varies differently.', 'c_transition_elements', 3, 'JEE Mains Prep', 'approved'),
('Mn$^{2+}$ ($3d^5$) is particularly stable because', 'It has a noble gas configuration', 'Half-filled $d^5$ configuration has maximum exchange energy', 'It has no $d$ electrons', 'It is diamagnetic', 'option2', '$d^5$: 5 unpaired electrons with maximum exchange energy ($\binom{5}{2} = 10$ exchange pairs). Extra stabilization.', 'c_transition_elements', 3, 'JEE Mains Prep', 'approved'),
('The third-row transition metals (Hf to Hg) have similar properties to second-row (Zr to Cd) due to', 'They are all gases', 'They are in different groups', 'They have no $d$ electrons', 'Lanthanoid contraction making their atomic radii nearly identical', 'option4', 'Lanthanoid contraction: 4$f$ electrons shield poorly, so 5$d$ elements have similar radii to 4$d$ elements. E.g., Zr ($160\;\text{pm}$) $\approx$ Hf ($159\;\text{pm}$).', 'c_transition_elements', 3, 'JEE Mains Prep', 'approved'),
('The magnetic moment of a transition metal ion with $n$ unpaired electrons is given by', '$\mu = \sqrt{n(n+2)}\;\text{BM}$ (spin-only formula)', '$\mu = n\;\text{BM}$', '$\mu = n^2\;\text{BM}$', '$\mu = \sqrt{n}\;\text{BM}$', 'option1', 'Spin-only formula: $\mu = \sqrt{n(n+2)}$ BM. Works well for first-row transition metals where orbital contribution is quenched.', 'c_transition_elements', 3, 'JEE Mains Prep', 'approved'),
('The colour of [Ti(H$_2$O)$_6$]$^{3+}$ (purple) is due to', 'Ti has no $d$ electrons', 'Charge transfer', 'The water ligands', 'A $d$-$d$ transition: the single $d$ electron absorbs light to jump from $t_{2g}$ to $e_g$', 'option4', 'Ti$^{3+}$: $d^1$. In octahedral field: electron in $t_{2g}$ absorbs green-yellow light ($\sim 500\;\text{nm}$) to jump to $e_g$. Transmitted colour: purple.', 'c_transition_elements', 3, 'JEE Mains Prep', 'approved'),
('Sc$^{3+}$ and Zn$^{2+}$ compounds are colourless because', 'Sc$^{3+}$ ($d^0$) and Zn$^{2+}$ ($d^{10}$) have no possible $d$-$d$ transitions', 'They absorb all light', 'They are not transition metals', 'They have unpaired electrons', 'option1', '$d^0$ and $d^{10}$: no $d$-$d$ transitions possible. No visible light absorption $\to$ colourless.', 'c_transition_elements', 3, 'JEE Mains Prep', 'approved'),

-- ============================================================
-- c_transition_properties (7 easy, 7 medium, 7 hard = 21)
-- IE, oxidation states, colour, catalysis, magnetism, complexes, alloys
-- ============================================================
('Transition metal ions are paramagnetic when they have', 'No unpaired electrons', 'One or more unpaired electrons', 'A noble gas configuration', 'Only paired electrons', 'option2', 'Paramagnetism arises from unpaired electrons. More unpaired electrons $=$ stronger paramagnetism.', 'c_transition_properties', 1, 'JEE Mains Prep', 'approved'),
('The colour of CuSO$_4 \cdot 5$H$_2$O is blue because', 'Cu is a noble metal', 'It contains water', 'Sulfate is blue', 'Cu$^{2+}$ ($d^9$) undergoes $d$-$d$ transitions absorbing red-orange light', 'option4', 'Cu$^{2+}$ in [Cu(H$_2$O)$_4$]$^{2+}$ absorbs red light ($\sim 600\;\text{nm}$), transmitting blue.', 'c_transition_properties', 1, 'JEE Mains Prep', 'approved'),
('Anhydrous CuSO$_4$ is white because', 'White is the natural colour of all salts', 'Cu$^{2+}$ has no $d$ electrons', 'It is not a transition metal compound', 'Without water ligands, the crystal field splitting is too small for visible $d$-$d$ transitions', 'option4', 'Without H$_2$O ligands, the $d$-$d$ transition energy falls outside the visible range.', 'c_transition_properties', 1, 'JEE Mains Prep', 'approved'),
('Fe$_2$O$_3$ is used as a catalyst in the Haber process. This is an example of', 'Homogeneous catalysis', 'Heterogeneous catalysis', 'Enzyme catalysis', 'Autocatalysis', 'option2', 'Fe$_2$O$_3$ (solid) catalyzes the gas-phase reaction N$_2$ + 3H$_2 \to$ 2NH$_3$. Different phases $=$ heterogeneous.', 'c_transition_properties', 1, 'JEE Mains Prep', 'approved'),
('The number of unpaired electrons in Fe$^{3+}$ ($d^5$) in a weak field is', '$0$', '$1$', '$3$', '$5$', 'option4', 'Weak field (high spin): all 5 $d$ electrons are unpaired. $\mu = \sqrt{5 \times 7} = \sqrt{35} = 5.92\;\text{BM}$.', 'c_transition_properties', 1, 'JEE Mains Prep', 'approved'),
('Transition metals form interstitial compounds by trapping small atoms like', 'H, C, N, B in the voids of their crystal lattices', 'Noble gases', 'Alkali metals', 'Halogens only', 'option1', 'Small atoms fit in octahedral/tetrahedral holes. These compounds are hard, have high mp, and are chemically inert.', 'c_transition_properties', 1, 'JEE Mains Prep', 'approved'),
('The magnetic moment of Mn$^{2+}$ ($d^5$, high spin) is approximately', '$1.73\;\text{BM}$', '$3.87\;\text{BM}$', '$5.92\;\text{BM}$', '$0\;\text{BM}$', 'option3', '$n = 5$ unpaired. $\mu = \sqrt{5(5+2)} = \sqrt{35} = 5.92\;\text{BM}$.', 'c_transition_properties', 1, 'JEE Mains Prep', 'approved'),
('The oxidation state of $+7$ is shown by Mn in KMnO$_4$. In this state, Mn uses', 'All 7 valence electrons ($3d^5 + 4s^2$) for bonding', 'Only $4s$ electrons', 'Only $3d$ electrons', 'No electrons', 'option1', 'Maximum oxidation state $=$ group number (for early transition metals). Mn: Group 7, max $+7$.', 'c_transition_properties', 2, 'JEE Mains Prep', 'approved'),
('The stability of the $+2$ oxidation state increases across the first transition series because', 'All metals show only $+2$', 'The $+2$ state becomes less stable', 'The increasing nuclear charge makes it harder to remove $d$ electrons beyond the $4s^2$', 'The $d$ electrons are easily removed', 'option3', 'Higher $Z_{eff}$ stabilizes $d$ electrons. Late transition metals (Cu, Zn) strongly prefer $+2$.', 'c_transition_properties', 2, 'JEE Mains Prep', 'approved'),
('MnO$_4^-$ (permanganate) is intensely purple due to', 'The colour of Mn metal', '$d$-$d$ transitions', 'Charge transfer transitions (O $\to$ Mn)', 'Absorption of UV light only', 'option3', 'Mn in $+7$ is $d^0$ — no $d$-$d$ transitions possible. The colour is from ligand-to-metal charge transfer (LMCT).', 'c_transition_properties', 2, 'JEE Mains Prep', 'approved'),
('CrO$_4^{2-}$ (chromate, yellow) and Cr$_2$O$_7^{2-}$ (dichromate, orange) are interconvertible by', 'They cannot interconvert', 'Changing temperature', 'Adding a catalyst', 'Changing pH: acidic $\to$ Cr$_2$O$_7^{2-}$; basic $\to$ CrO$_4^{2-}$', 'option4', '2CrO$_4^{2-}$ + 2H$^+ \rightleftharpoons$ Cr$_2$O$_7^{2-}$ + H$_2$O. Acid shifts right (orange); base shifts left (yellow).', 'c_transition_properties', 2, 'JEE Mains Prep', 'approved'),
('V$_2$O$_5$ is used as a catalyst in the Contact process for manufacturing', 'NH$_3$', 'H$_2$SO$_4$ (oxidation of SO$_2$ to SO$_3$)', 'HNO$_3$', 'HCl', 'option2', '2SO$_2$ + O$_2 \xrightarrow{\text{V}_2\text{O}_5}$ 2SO$_3$. V$_2$O$_5$ provides variable oxidation states ($+4/+5$) for the catalytic cycle.', 'c_transition_properties', 2, 'JEE Mains Prep', 'approved'),
('The magnetic moment of Ni$^{2+}$ ($d^8$) in an octahedral weak field complex is', '$2.83\;\text{BM}$', '$0\;\text{BM}$', '$4.90\;\text{BM}$', '$1.73\;\text{BM}$', 'option1', 'Weak field $d^8$: $t_{2g}^6 e_g^2$. 2 unpaired electrons. $\mu = \sqrt{2(2+2)} = \sqrt{8} = 2.83\;\text{BM}$.', 'c_transition_properties', 2, 'JEE Mains Prep', 'approved'),
('The highest oxidation state compounds of transition metals are usually', 'Ionic and basic', 'Covalent and acidic (e.g., CrO$_3$, Mn$_2$O$_7$)', 'Always coloured', 'Always paramagnetic', 'option2', 'High oxidation state $\to$ high charge density $\to$ strong polarization $\to$ covalent character. Oxides are acidic (e.g., CrO$_3$ + H$_2$O $\to$ H$_2$CrO$_4$).', 'c_transition_properties', 2, 'JEE Mains Prep', 'approved'),
('The Irving-Williams series for stability of divalent complexes is', 'Mn $>$ Fe $>$ Co $>$ Ni', 'Zn $>$ Cu $>$ Ni $>$ Co', 'All are equal', 'Mn $<$ Fe $<$ Co $<$ Ni $<$ Cu $>$ Zn', 'option4', 'Stability increases from Mn$^{2+}$ to Cu$^{2+}$ (CFSE + Jahn-Teller effect for Cu$^{2+}$), then drops for Zn$^{2+}$ ($d^{10}$, no CFSE).', 'c_transition_properties', 3, 'JEE Mains Prep', 'approved'),
('The Jahn-Teller distortion is observed in Cu$^{2+}$ ($d^9$) octahedral complexes because', 'The unequal filling of $e_g$ orbitals ($d_{z^2}^2 d_{x^2-y^2}^1$) causes tetragonal elongation', 'Cu$^{2+}$ is too small', 'All octahedral complexes are distorted', 'Cu$^{2+}$ has no $d$ electrons', 'option1', '$d^9$: $e_g$ has 3 electrons (2 in one, 1 in other). Unequal occupation distorts the octahedron (elongation along $z$).', 'c_transition_properties', 3, 'JEE Mains Prep', 'approved'),
('The reason Cr$^{3+}$ ($d^3$) forms kinetically inert complexes is', 'Cr$^{3+}$ is very large', 'High CFSE in octahedral field ($t_{2g}^3$) makes ligand exchange slow', 'Cr$^{3+}$ has no $d$ electrons', 'All Cr complexes are labile', 'option2', '$d^3$ in octahedral: $t_{2g}^3$ (half-filled, high CFSE). Ligand substitution requires overcoming this stabilization.', 'c_transition_properties', 3, 'JEE Mains Prep', 'approved'),
('The low oxidation state compounds of transition metals (e.g., Ni(CO)$_4$, Fe(CO)$_5$) are stabilized by', '$\pi$-acceptor ligands (like CO) that accept electron density from the metal via back-bonding', '$\sigma$-donor ligands only', 'Ionic bonding', 'High temperature', 'option1', 'CO accepts electron density from filled metal $d$ orbitals into its empty $\pi^*$ orbitals (synergic bonding), stabilizing low oxidation states.', 'c_transition_properties', 3, 'JEE Mains Prep', 'approved'),
('The effective atomic number (EAN) rule states that stable complexes tend to have', 'Only $d$ electrons', 'Always 18 electrons', 'No electrons', 'The total electron count equal to the nearest noble gas (e.g., 36 for Kr, 54 for Xe)', 'option4', 'EAN $=$ metal electrons $+$ electrons donated by ligands. Ni(CO)$_4$: $28 + 8 = 36$ (Kr). Fe(CO)$_5$: $26 + 10 = 36$.', 'c_transition_properties', 3, 'JEE Mains Prep', 'approved'),
('The 18-electron rule is the transition metal analogue of the octet rule. Ni(CO)$_4$ obeys it because', 'It has 8 electrons', 'Ni ($d^{10}s^0$, 10 electrons) + 4CO (8 electrons) $= 18$ valence electrons', 'It has 36 electrons', 'It violates the rule', 'option2', 'Ni: 10 valence electrons. Each CO donates 2. Total $= 10 + 8 = 18$. Stable, diamagnetic complex.', 'c_transition_properties', 3, 'JEE Mains Prep', 'approved'),
('The nephelauxetic effect in transition metal complexes refers to', 'The contraction of $d$ orbitals', 'The expansion of $d$ electron cloud due to covalent interaction with ligands, reducing interelectronic repulsion', 'The colour change', 'The magnetic moment change', 'option2', 'Nephelauxetic (cloud-expanding): covalent bonding delocalizes $d$ electrons onto ligands, reducing Racah parameters. Order: F$^-$ $<$ H$_2$O $<$ NH$_3$ $<$ CN$^-$.', 'c_transition_properties', 3, 'JEE Mains Prep', 'approved'),

-- ============================================================
-- c_dichromate_permanganate (7 easy, 7 medium, 7 hard = 21)
-- Preparation, properties and uses of K2Cr2O7 and KMnO4
-- ============================================================
('The oxidation state of Cr in K$_2$Cr$_2$O$_7$ is', '$+3$', '$+6$', '$+7$', '$+2$', 'option2', '2($+1$) + 2($x$) + 7($-2$) $= 0$. $2 + 2x - 14 = 0$. $x = +6$.', 'c_dichromate_permanganate', 1, 'JEE Mains Prep', 'approved'),
('The oxidation state of Mn in KMnO$_4$ is', '$+4$', '$+6$', '$+7$', '$+2$', 'option3', '$+1 + x + 4(-2) = 0$. $x = +7$.', 'c_dichromate_permanganate', 1, 'JEE Mains Prep', 'approved'),
('K$_2$Cr$_2$O$_7$ in acidic solution is a powerful', 'Reducing agent', 'Oxidizing agent', 'Catalyst', 'Base', 'option2', 'Cr$_2$O$_7^{2-}$ + 14H$^+$ + 6e$^- \to$ 2Cr$^{3+}$ + 7H$_2$O. Strong oxidizer in acidic medium.', 'c_dichromate_permanganate', 1, 'JEE Mains Prep', 'approved'),
('KMnO$_4$ in acidic solution is reduced to', 'MnO$_2$', 'Mn$^{2+}$ (colourless)', 'MnO$_4^{2-}$', 'Mn$_2$O$_7$', 'option2', 'Acidic: MnO$_4^-$ + 8H$^+$ + 5e$^- \to$ Mn$^{2+}$ + 4H$_2$O. Purple $\to$ colourless.', 'c_dichromate_permanganate', 1, 'JEE Mains Prep', 'approved'),
('The colour of K$_2$Cr$_2$O$_7$ solution is', 'Purple', 'Orange', 'Green', 'Colourless', 'option2', 'Dichromate ion Cr$_2$O$_7^{2-}$ is orange. Chromate CrO$_4^{2-}$ is yellow.', 'c_dichromate_permanganate', 1, 'JEE Mains Prep', 'approved'),
('The colour of KMnO$_4$ solution is', 'Orange', 'Deep purple/violet', 'Green', 'Yellow', 'option2', 'MnO$_4^-$ is intensely purple due to charge transfer transitions.', 'c_dichromate_permanganate', 1, 'JEE Mains Prep', 'approved'),
('KMnO$_4$ is used in analytical chemistry for', 'Complexometric titrations', 'Acid-base titrations only', 'Precipitation titrations', 'Redox titrations (permanganometry)', 'option4', 'KMnO$_4$ is its own indicator: purple $\to$ colourless (acidic) or green (basic). Used to titrate Fe$^{2+}$, oxalate, etc.', 'c_dichromate_permanganate', 1, 'JEE Mains Prep', 'approved'),
('K$_2$Cr$_2$O$_7$ is prepared from chromite ore (FeCr$_2$O$_4$) by', 'Fusion with Na$_2$CO$_3$ in air, followed by acidification', 'Direct heating', 'Electrolysis', 'Reduction with carbon', 'option1', 'FeCr$_2$O$_4$ + Na$_2$CO$_3$ + O$_2 \to$ Na$_2$CrO$_4$ + Fe$_2$O$_3$. Then acidify: 2Na$_2$CrO$_4$ + H$_2$SO$_4 \to$ Na$_2$Cr$_2$O$_7$ + Na$_2$SO$_4$ + H$_2$O. Add KCl to get K$_2$Cr$_2$O$_7$.', 'c_dichromate_permanganate', 2, 'JEE Mains Prep', 'approved'),
('KMnO$_4$ in neutral/weakly alkaline solution is reduced to', 'Mn$^{2+}$', 'MnO$_2$ (brown precipitate)', 'MnO$_4^{2-}$', 'Mn metal', 'option2', 'Neutral: MnO$_4^-$ + 2H$_2$O + 3e$^- \to$ MnO$_2$ + 4OH$^-$. Brown MnO$_2$ precipitates.', 'c_dichromate_permanganate', 2, 'JEE Mains Prep', 'approved'),
('KMnO$_4$ in strongly alkaline solution is reduced to', 'Mn$^{2+}$', 'MnO$_2$', 'MnO$_4^{2-}$ (manganate, green)', 'Mn$_2$O$_7$', 'option3', 'Strongly alkaline: MnO$_4^-$ + e$^- \to$ MnO$_4^{2-}$ (green). Only 1 electron change.', 'c_dichromate_permanganate', 2, 'JEE Mains Prep', 'approved'),
('The breathalyzer test for alcohol uses', 'NaOH', 'KMnO$_4$', 'K$_2$Cr$_2$O$_7$ in acidic solution (orange $\to$ green when alcohol is oxidized)', 'HCl', 'option3', 'Ethanol reduces Cr$_2$O$_7^{2-}$ (orange) to Cr$^{3+}$ (green). Colour change indicates alcohol presence.', 'c_dichromate_permanganate', 2, 'JEE Mains Prep', 'approved'),
('K$_2$Cr$_2$O$_7$ oxidizes Fe$^{2+}$ to Fe$^{3+}$ in acidic solution. The balanced equation shows that $1\;\text{mol}$ K$_2$Cr$_2$O$_7$ oxidizes', '$3\;\text{mol}$ Fe$^{2+}$', '$6\;\text{mol}$ Fe$^{2+}$', '$2\;\text{mol}$ Fe$^{2+}$', '$1\;\text{mol}$ Fe$^{2+}$', 'option2', 'Cr$_2$O$_7^{2-}$ gains 6e$^-$. Each Fe$^{2+}$ loses 1e$^-$. So 6 mol Fe$^{2+}$ per mol dichromate.', 'c_dichromate_permanganate', 2, 'JEE Mains Prep', 'approved'),
('KMnO$_4$ is prepared industrially by', 'Reduction of MnO$_2$', 'Direct combination of K and Mn', 'Fusion of MnO$_2$ with KOH and oxidant, then electrolytic oxidation of K$_2$MnO$_4$', 'Heating KCl with MnO$_2$', 'option3', '2MnO$_2$ + 4KOH + O$_2 \to$ 2K$_2$MnO$_4$ + 2H$_2$O. Then: 3K$_2$MnO$_4$ + 2H$_2$O $\to$ 2KMnO$_4$ + MnO$_2$ + 4KOH (or electrolytic oxidation).', 'c_dichromate_permanganate', 2, 'JEE Mains Prep', 'approved'),
('In the chromyl chloride test, K$_2$Cr$_2$O$_7$ + NaCl + conc. H$_2$SO$_4$ produces', 'CrO$_2$Cl$_2$ (red vapours)', 'Cl$_2$ (green gas)', 'CrCl$_3$ (green solid)', 'Na$_2$CrO$_4$ (yellow)', 'option1', 'K$_2$Cr$_2$O$_7$ + 4NaCl + 6H$_2$SO$_4 \to$ 2CrO$_2$Cl$_2$ (chromyl chloride, red vapours) + ... Used to detect Cl$^-$.', 'c_dichromate_permanganate', 2, 'JEE Mains Prep', 'approved'),
('The $n$-factor of KMnO$_4$ in acidic, neutral, and strongly alkaline media are respectively', '$5, 3, 1$', '$3, 5, 1$', '$1, 3, 5$', '$5, 1, 3$', 'option1', 'Acidic: Mn$^{+7} \to$ Mn$^{+2}$ (5e$^-$). Neutral: $\to$ MnO$_2$ ($+4$, 3e$^-$). Alkaline: $\to$ MnO$_4^{2-}$ ($+6$, 1e$^-$).', 'c_dichromate_permanganate', 3, 'JEE Mains Prep', 'approved'),
('Baeyer''s test for unsaturation uses', 'K$_2$Cr$_2$O$_7$', 'Dilute alkaline KMnO$_4$ (decolourized by alkenes)', 'Conc. H$_2$SO$_4$', 'Br$_2$ water only', 'option2', 'Cold dilute KMnO$_4$ (purple) is decolourized by alkenes (syn-dihydroxylation). Positive test $=$ unsaturation present.', 'c_dichromate_permanganate', 3, 'JEE Mains Prep', 'approved'),
('The equivalent mass of K$_2$Cr$_2$O$_7$ in acidic medium is', '$294/2 = 147$', '$294/3 = 98$', '$294$', '$294/6 = 49$', 'option4', '$n$-factor $= 6$ (gains 6e$^-$). Equivalent mass $= 294/6 = 49\;\text{g/eq}$.', 'c_dichromate_permanganate', 3, 'JEE Mains Prep', 'approved'),
('KMnO$_4$ oxidizes oxalic acid in acidic medium. The reaction is autocatalytic because', 'The product Mn$^{2+}$ catalyzes the reaction (initially slow, then fast)', 'KMnO$_4$ is the catalyst', 'H$_2$SO$_4$ is the catalyst', 'No catalysis occurs', 'option1', 'Initially slow (no Mn$^{2+}$). As Mn$^{2+}$ forms, it catalyzes the reaction. The solution must be heated to $\sim 60°\text{C}$ to start.', 'c_dichromate_permanganate', 3, 'JEE Mains Prep', 'approved'),
('K$_2$Cr$_2$O$_7$ is preferred over KMnO$_4$ as a primary standard in titrations because', 'K$_2$Cr$_2$O$_7$ is cheaper', 'KMnO$_4$ is more stable', 'K$_2$Cr$_2$O$_7$ is stable, non-hygroscopic, and can be obtained in high purity', 'KMnO$_4$ does not react', 'option3', 'KMnO$_4$ decomposes in light and reacts with organic matter. K$_2$Cr$_2$O$_7$ is stable and can be weighed accurately.', 'c_dichromate_permanganate', 3, 'JEE Mains Prep', 'approved'),
('In the titration of KMnO$_4$ with oxalic acid, the indicator used is', 'Phenolphthalein', 'Methyl orange', 'No external indicator (KMnO$_4$ is self-indicating)', 'Starch', 'option3', 'KMnO$_4$ (purple) $\to$ Mn$^{2+}$ (colourless). The first excess drop of KMnO$_4$ gives a permanent pink colour $=$ endpoint.', 'c_dichromate_permanganate', 3, 'JEE Mains Prep', 'approved'),
('The volume of $0.02\;\text{M}$ KMnO$_4$ required to oxidize $20\;\text{mL}$ of $0.1\;\text{M}$ FeSO$_4$ in acidic medium is', '$20\;\text{mL}$', '$10\;\text{mL}$', '$40\;\text{mL}$', '$4\;\text{mL}$', 'option1', 'Milliequivalents: KMnO$_4$: $V \times 0.02 \times 5$. FeSO$_4$: $20 \times 0.1 \times 1 = 2$. $0.1V = 2$. $V = 20\;\text{mL}$.', 'c_dichromate_permanganate', 3, 'JEE Mains Prep', 'approved'),

-- ============================================================
-- c_inner_transition (7 easy, 7 medium, 7 hard = 21)
-- Lanthanoids, actinoids, configuration, oxidation states, contraction
-- ============================================================
('The lanthanoids are elements with atomic numbers', '$21$ to $30$', '$57$ to $71$', '$89$ to $103$', '$72$ to $86$', 'option2', 'Lanthanoids: La ($57$) to Lu ($71$). They fill the $4f$ subshell.', 'c_inner_transition', 1, 'JEE Mains Prep', 'approved'),
('The actinoids are elements with atomic numbers', '$57$ to $71$', '$89$ to $103$', '$21$ to $30$', '$72$ to $86$', 'option2', 'Actinoids: Ac ($89$) to Lr ($103$). They fill the $5f$ subshell.', 'c_inner_transition', 1, 'JEE Mains Prep', 'approved'),
('The most common oxidation state of lanthanoids is', '$+2$', '$+3$', '$+4$', '$+5$', 'option2', 'Lanthanoids predominantly show $+3$ (losing $5d^1$ and $6s^2$). Some show $+2$ (Eu, Yb) or $+4$ (Ce, Tb) due to $f^0$, $f^7$, $f^{14}$ stability.', 'c_inner_transition', 1, 'JEE Mains Prep', 'approved'),
('Lanthanoid contraction is the gradual decrease in', 'Atomic and ionic radii across the lanthanoid series', 'Atomic number', 'Oxidation state', 'Electronegativity', 'option1', 'Poor shielding by $4f$ electrons causes increasing $Z_{eff}$, steadily shrinking the radii from La$^{3+}$ to Lu$^{3+}$.', 'c_inner_transition', 1, 'JEE Mains Prep', 'approved'),
('Actinoids show a wider range of oxidation states than lanthanoids because', '$5f$ electrons are tightly held', 'The $5f$, $6d$, and $7s$ orbitals are close in energy, allowing more electrons to participate in bonding', 'Actinoids have no $f$ electrons', 'Lanthanoids show more oxidation states', 'option2', 'Actinoids: $+3$ to $+7$ (e.g., U: $+3$ to $+6$, Np: $+3$ to $+7$). $5f$ electrons are less tightly held than $4f$.', 'c_inner_transition', 1, 'JEE Mains Prep', 'approved'),
('All actinoids beyond uranium ($Z = 92$) are', 'Naturally occurring', 'Synthetic (man-made, transuranium elements)', 'Noble gases', 'Non-radioactive', 'option2', 'Np ($93$), Pu ($94$), Am ($95$), etc. are all synthetic. All actinoids are radioactive.', 'c_inner_transition', 1, 'JEE Mains Prep', 'approved'),
('Lanthanoids are also called', 'Alkali metals', 'Noble metals', 'Rare earth elements', 'Halogens', 'option3', 'Historically called "rare earths" though they are not actually rare. Used in magnets, lasers, catalysts.', 'c_inner_transition', 1, 'JEE Mains Prep', 'approved'),
('Ce$^{4+}$ is stable because it achieves', 'A noble gas configuration', 'An empty $4f^0$ configuration (extra stability)', 'A half-filled $4f^7$ configuration', 'A fully filled $4f^{14}$ configuration', 'option2', 'Ce: [Xe]$4f^15d^16s^2$. Ce$^{4+}$: [Xe]$4f^0$ (empty $f$ shell, stable). Ce$^{4+}$ is a strong oxidizing agent.', 'c_inner_transition', 2, 'JEE Mains Prep', 'approved'),
('Eu$^{2+}$ is stable because it achieves', 'An empty $4f$ shell', 'A half-filled $4f^7$ configuration', 'A fully filled $4f^{14}$ configuration', 'A noble gas configuration', 'option2', 'Eu: [Xe]$4f^76s^2$. Eu$^{2+}$: [Xe]$4f^7$ (half-filled, extra stable). Eu$^{2+}$ is a reducing agent.', 'c_inner_transition', 2, 'JEE Mains Prep', 'approved'),
('The separation of lanthanoids is difficult because', 'They have very similar chemical properties due to the same $+3$ oxidation state and similar ionic radii', 'They are gases', 'They have very different properties', 'They do not form compounds', 'option1', 'Similar radii and chemistry make separation challenging. Ion-exchange chromatography is the modern method.', 'c_inner_transition', 2, 'JEE Mains Prep', 'approved'),
('The general electronic configuration of lanthanoids is', '[Ar] $3d^{1-10} 4s^2$', '[Xe] $5f^{1-14} 6d^{0-1} 7s^2$', '[Kr] $4d^{1-10} 5s^2$', '[Xe] $4f^{1-14} 5d^{0-1} 6s^2$', 'option4', 'Lanthanoids fill the $4f$ subshell. Most have $5d^0$ except La, Ce, Gd, Lu which have $5d^1$.', 'c_inner_transition', 2, 'JEE Mains Prep', 'approved'),
('Gadolinium (Gd) has the configuration [Xe] $4f^7 5d^1 6s^2$ instead of [Xe] $4f^8 6s^2$ because', 'The half-filled $4f^7$ configuration is extra stable', '$5d$ is lower in energy than $4f$', 'Gd has no $f$ electrons', 'This is an error', 'option1', 'Half-filled $4f^7$ has maximum exchange energy. One electron promotes to $5d$ to achieve this stability.', 'c_inner_transition', 2, 'JEE Mains Prep', 'approved'),
('Lanthanoid compounds are generally', 'Strongly coloured', 'Weakly coloured or colourless (pale colours from $f$-$f$ transitions)', 'Always black', 'Fluorescent only', 'option2', '$f$-$f$ transitions are Laplace-forbidden (weak). Colours are pale: Pr$^{3+}$ (green), Nd$^{3+}$ (lilac), Er$^{3+}$ (pink).', 'c_inner_transition', 2, 'JEE Mains Prep', 'approved'),
('The magnetic properties of lanthanoid ions are determined by', 'Spin only', 'Both spin and orbital angular momentum ($\mu = g\sqrt{J(J+1)}$)', 'Orbital contribution only', 'They are all diamagnetic', 'option2', 'Unlike $3d$ metals (spin-only), $4f$ electrons have significant orbital contribution. $\mu_{eff}$ calculated using total angular momentum $J$.', 'c_inner_transition', 2, 'JEE Mains Prep', 'approved'),
('The consequence of lanthanoid contraction on post-lanthanoid elements is that', 'Hf and Zr have nearly identical radii and very similar chemistry', 'Post-lanthanoid elements are much larger', 'There is no effect', 'Post-lanthanoid elements are gases', 'option1', 'Zr ($160\;\text{pm}$) $\approx$ Hf ($159\;\text{pm}$). This makes Hf/Zr separation extremely difficult.', 'c_inner_transition', 3, 'JEE Mains Prep', 'approved'),
('Uranium ($Z = 92$) shows oxidation states $+3$ to $+6$. The most stable is', '$+3$', '$+4$', '$+6$ (as UO$_2^{2+}$, uranyl ion)', '$+2$', 'option3', 'UO$_2^{2+}$ (uranyl) is the most stable form of U in aqueous solution. U$^{4+}$ is also common in solid compounds.', 'c_inner_transition', 3, 'JEE Mains Prep', 'approved'),
('The actinoid contraction is larger than the lanthanoid contraction because', 'The $5f$ electrons shield even more poorly than $4f$ electrons', '$5f$ electrons shield better', 'Actinoids are smaller', 'There is no actinoid contraction', 'option1', '$5f$ orbitals are more diffuse and shield less effectively than $4f$, causing a greater contraction across the actinoid series.', 'c_inner_transition', 3, 'JEE Mains Prep', 'approved'),
('Neodymium (Nd) is used in', 'Powerful permanent magnets (Nd$_2$Fe$_{14}$B)', 'Nuclear reactors only', 'Food preservation', 'Water purification', 'option1', 'NdFeB magnets are the strongest permanent magnets known. Used in hard drives, headphones, electric motors, MRI machines.', 'c_inner_transition', 3, 'JEE Mains Prep', 'approved'),
('The reason all actinoids are radioactive is', 'Their nuclei are too large and unstable (all have $Z \geq 89$)', 'They have no neutrons', 'They are synthetic only', 'Radioactivity is unrelated to atomic number', 'option1', 'Beyond Bi ($Z = 83$), all elements are radioactive. Actinoids ($Z = 89$-$103$) have large, unstable nuclei.', 'c_inner_transition', 3, 'JEE Mains Prep', 'approved'),
('Cerium(IV) oxide (CeO$_2$) is used as', 'A pigment only', 'A food additive', 'A fuel', 'A polishing agent for glass and a catalyst in catalytic converters', 'option4', 'CeO$_2$: excellent polishing agent. In catalytic converters: Ce$^{4+}$/Ce$^{3+}$ redox cycle stores/releases oxygen.', 'c_inner_transition', 3, 'JEE Mains Prep', 'approved'),
('The ionic radii of Ln$^{3+}$ ions decrease from La$^{3+}$ ($103\;\text{pm}$) to Lu$^{3+}$ ($86\;\text{pm}$). This steady decrease of $\sim 17\;\text{pm}$ across 14 elements is called', 'Actinoid contraction', 'Lanthanoid contraction', '$d$-block contraction', 'Periodic expansion', 'option2', 'Lanthanoid contraction: $\sim 1.2\;\text{pm}$ decrease per element due to poor $4f$ shielding.', 'c_inner_transition', 3, 'JEE Mains Prep', 'approved'),

-- ============================================================
-- c_coord_intro_werner (7 easy, 7 medium, 7 hard = 21)
-- Coordination compounds, Werner''s theory, ligands, CN, denticity
-- ============================================================
('A coordination compound consists of', 'Only covalent molecules', 'Only ionic bonds', 'A central metal ion surrounded by ligands', 'No metal atoms', 'option3', 'Coordination compounds: central metal atom/ion bonded to a definite number of ligands via coordinate bonds.', 'c_coord_intro_werner', 1, 'JEE Mains Prep', 'approved'),
('Werner''s theory proposed that metals have two types of valencies:', 'Primary (ionizable, satisfied by anions) and secondary (non-ionizable, satisfied by ligands)', 'Only primary valency', 'Only secondary valency', 'No valencies', 'option1', 'Primary valency $=$ oxidation state. Secondary valency $=$ coordination number. Secondary valency is directional.', 'c_coord_intro_werner', 1, 'JEE Mains Prep', 'approved'),
('A ligand is', 'A metal ion', 'A molecule or ion that donates a lone pair of electrons to the central metal', 'A solvent molecule only', 'An electron acceptor', 'option2', 'Ligands are Lewis bases. They donate electron pairs to the metal (Lewis acid) forming coordinate bonds.', 'c_coord_intro_werner', 1, 'JEE Mains Prep', 'approved'),
('The coordination number of a metal in a complex is', 'The number of electrons', 'The oxidation state', 'The number of coordinate bonds formed by the metal with ligands', 'The atomic number', 'option3', 'CN $=$ number of ligand donor atoms directly bonded to the metal. E.g., [Co(NH$_3$)$_6$]$^{3+}$: CN $= 6$.', 'c_coord_intro_werner', 1, 'JEE Mains Prep', 'approved'),
('A monodentate ligand donates', 'No lone pairs', 'Two lone pairs', 'Three lone pairs', 'One lone pair through one donor atom', 'option4', 'Monodentate: one donor atom. E.g., NH$_3$ (N), H$_2$O (O), Cl$^-$ (Cl), CN$^-$ (C).', 'c_coord_intro_werner', 1, 'JEE Mains Prep', 'approved'),
('A bidentate ligand donates through', 'One donor atom', 'Two donor atoms simultaneously', 'Three donor atoms', 'Four donor atoms', 'option2', 'Bidentate: 2 donor atoms. E.g., ethylenediamine (en, 2 N atoms), oxalate (C$_2$O$_4^{2-}$, 2 O atoms).', 'c_coord_intro_werner', 1, 'JEE Mains Prep', 'approved'),
('Chelation refers to', 'The formation of ionic bonds', 'The formation of a ring structure when a polydentate ligand binds to a metal', 'The dissolution of a metal', 'The precipitation of a complex', 'option2', 'Chelate complexes (ring-forming) are more stable than analogous non-chelate complexes (chelate effect).', 'c_coord_intro_werner', 1, 'JEE Mains Prep', 'approved'),
('EDTA (ethylenediaminetetraacetate) is a _____ ligand.', 'Monodentate', 'Bidentate', 'Tetradentate', 'Hexadentate', 'option4', 'EDTA has 6 donor atoms: 2 N + 4 O (from carboxylate groups). It wraps around the metal forming 5 chelate rings.', 'c_coord_intro_werner', 2, 'JEE Mains Prep', 'approved'),
('In [Co(NH$_3$)$_6$]Cl$_3$, the coordination number and oxidation state of Co are', 'CN $= 9$, OS $= +3$', 'CN $= 3$, OS $= +3$', 'CN $= 6$, OS $= +2$', 'CN $= 6$, OS $= +3$', 'option4', '6 NH$_3$ ligands $\to$ CN $= 6$. Charge: $x + 0 = +3$ (since 3 Cl$^-$ outside). OS $= +3$.', 'c_coord_intro_werner', 2, 'JEE Mains Prep', 'approved'),
('An ambidentate ligand is one that can coordinate through', 'Only one donor atom', 'Either of two different donor atoms (but one at a time)', 'Two donor atoms simultaneously', 'No donor atoms', 'option2', 'Ambidentate: NO$_2^-$ (N or O), SCN$^-$ (S or N), CN$^-$ (C or N). Binds through one atom at a time.', 'c_coord_intro_werner', 2, 'JEE Mains Prep', 'approved'),
('The counter ions in [Cu(NH$_3$)$_4$]SO$_4$ are', 'NH$_3$', 'SO$_4^{2-}$', 'Cu$^{2+}$', 'There are no counter ions', 'option2', '[Cu(NH$_3$)$_4$]$^{2+}$ is the complex cation. SO$_4^{2-}$ is the counter ion (outside the coordination sphere).', 'c_coord_intro_werner', 2, 'JEE Mains Prep', 'approved'),
('The chelate effect states that chelate complexes are more stable than analogous non-chelate complexes because', 'Chelate bonds are stronger', 'Chelation increases entropy (releases more monodentate ligands than polydentate ligands consumed)', 'Chelates are always coloured', 'There is no chelate effect', 'option2', 'Thermodynamic: $\Delta S > 0$ (more particles released). Kinetic: polydentate ligands are harder to displace completely.', 'c_coord_intro_werner', 2, 'JEE Mains Prep', 'approved'),
('In [PtCl$_2$(en)], the coordination number of Pt is', '$2$', '$3$', '$4$', '$6$', 'option3', 'en is bidentate (2 donor atoms) + 2 Cl$^-$ (monodentate). CN $= 2 + 2 = 4$.', 'c_coord_intro_werner', 2, 'JEE Mains Prep', 'approved'),
('The effective atomic number (EAN) of Co in [Co(NH$_3$)$_6$]$^{3+}$ is', '$54$ (Xe)', '$36$ (Kr)', '$27$', '$18$', 'option2', 'Co$^{3+}$: $27 - 3 = 24$ electrons. 6 NH$_3$ donate $6 \times 2 = 12$ electrons. EAN $= 24 + 12 = 36$ (Kr).', 'c_coord_intro_werner', 2, 'JEE Mains Prep', 'approved'),
('Werner''s theory was confirmed by', 'Conductivity measurements and precipitation reactions of coordination compounds', 'X-ray crystallography only', 'Mass spectrometry', 'NMR spectroscopy', 'option1', 'Werner showed that [Co(NH$_3$)$_6$]Cl$_3$ gives 3 Cl$^-$ ions (conductivity of 3 ions), while [Co(NH$_3$)$_5$Cl]Cl$_2$ gives 2 Cl$^-$.', 'c_coord_intro_werner', 3, 'JEE Mains Prep', 'approved'),
('The stability constant ($K_f$) of a complex [ML$_n$] is defined as', '$K_f = [\text{M}][\text{L}]^n/[\text{ML}_n]$', '$K_f = [\text{ML}_n]/([\text{M}][\text{L}]^n)$', '$K_f = [\text{ML}_n] \times [\text{M}]$', '$K_f = 1/[\text{ML}_n]$', 'option2', 'Larger $K_f$ $=$ more stable complex. $K_f$ is the equilibrium constant for the formation reaction.', 'c_coord_intro_werner', 3, 'JEE Mains Prep', 'approved'),
('A macrocyclic ligand (e.g., porphyrin, crown ether) forms complexes that are', 'Less stable than chelate complexes', 'More stable than chelate complexes (macrocyclic effect)', 'Equally stable', 'Unstable', 'option2', 'Macrocyclic effect: preorganized ring structure $\to$ even greater stability than open-chain chelates. E.g., hemoglobin (Fe-porphyrin).', 'c_coord_intro_werner', 3, 'JEE Mains Prep', 'approved'),
('The spectrochemical series orders ligands by', 'Their charge', 'Their size', 'Their ability to cause crystal field splitting ($\Delta$)', 'Their colour', 'option3', 'I$^- <$ Br$^- <$ Cl$^- <$ F$^- <$ OH$^- <$ H$_2$O $<$ NH$_3 <$ en $<$ NO$_2^- <$ CN$^- <$ CO. Weak field $\to$ strong field.', 'c_coord_intro_werner', 3, 'JEE Mains Prep', 'approved'),
('The number of ions produced by [Co(NH$_3$)$_4$Cl$_2$]Cl in solution is', '$3$', '$2$', '$4$', '$1$', 'option2', '[Co(NH$_3$)$_4$Cl$_2$]$^+$ + Cl$^-$. 2 ions total. Only the Cl outside the bracket ionizes.', 'c_coord_intro_werner', 3, 'JEE Mains Prep', 'approved'),
('The denticity of the ligand diethylenetriamine (dien, NH$_2$CH$_2$CH$_2$NHCH$_2$CH$_2$NH$_2$) is', '$2$', '$3$', '$4$', '$6$', 'option2', 'dien has 3 nitrogen donor atoms $\to$ tridentate. Forms 2 chelate rings with the metal.', 'c_coord_intro_werner', 3, 'JEE Mains Prep', 'approved'),
('In [Fe(CN)$_6$]$^{4-}$, the oxidation state and coordination number of Fe are', 'OS $= +2$, CN $= 6$', 'OS $= +3$, CN $= 6$', 'OS $= +2$, CN $= 4$', 'OS $= +4$, CN $= 6$', 'option1', '$x + 6(-1) = -4$. $x = +2$. 6 CN$^-$ ligands $\to$ CN $= 6$.', 'c_coord_intro_werner', 3, 'JEE Mains Prep', 'approved'),

-- ============================================================
-- c_coord_nomenclature_isomerism (7 easy, 7 medium, 7 hard = 21)
-- IUPAC nomenclature, isomerism in coordination compounds
-- ============================================================
('In IUPAC nomenclature of coordination compounds, ligands are named', 'After the metal', 'Before the metal in alphabetical order', 'After the counter ion', 'In order of size', 'option2', 'Ligands listed alphabetically, then metal with oxidation state in Roman numerals. E.g., tetraamminedichloridocobalt(III).', 'c_coord_nomenclature_isomerism', 1, 'JEE Mains Prep', 'approved'),
('Anionic ligands end in the suffix', '$-o$ (e.g., chlorido, cyano, hydroxido)', '$-ine$', '$-amine$', '$-ate$', 'option1', 'Cl$^- \to$ chlorido, CN$^- \to$ cyano, OH$^- \to$ hydroxido, O$^{2-} \to$ oxido. Neutral ligands keep their names (except aqua, ammine, carbonyl, nitrosyl).', 'c_coord_nomenclature_isomerism', 1, 'JEE Mains Prep', 'approved'),
('The IUPAC name of [Pt(NH$_3$)$_2$Cl$_2$] is', 'Dichloridodiammineplatinum(II)', 'Diamminedichloridoplatinum(II)', 'Platinum diammine dichloride', 'Platinous chloride ammonia', 'option2', 'Alphabetical: ammine before chlorido. Pt oxidation state: $x + 0 - 2 = 0$, $x = +2$. Diamminedichloridoplatinum(II).', 'c_coord_nomenclature_isomerism', 1, 'JEE Mains Prep', 'approved'),
('Geometric (cis-trans) isomerism is possible in', 'Tetrahedral complexes', 'Square planar and octahedral complexes', 'Linear complexes', 'All complexes', 'option2', 'Cis-trans isomerism requires restricted rotation: square planar (e.g., [Pt(NH$_3$)$_2$Cl$_2$]) and octahedral (e.g., [Co(NH$_3$)$_4$Cl$_2$]$^+$).', 'c_coord_nomenclature_isomerism', 1, 'JEE Mains Prep', 'approved'),
('Optical isomers are non-superimposable mirror images. They are also called', 'Geometric isomers', 'Enantiomers', 'Linkage isomers', 'Ionization isomers', 'option2', 'Enantiomers rotate plane-polarized light in opposite directions ($d$ and $l$ forms).', 'c_coord_nomenclature_isomerism', 1, 'JEE Mains Prep', 'approved'),
('Ionization isomerism arises when', 'Ligands and counter ions exchange positions', 'Ligands change their donor atom', 'The geometry changes', 'The oxidation state changes', 'option1', 'E.g., [Co(NH$_3$)$_5$SO$_4$]Br vs [Co(NH$_3$)$_5$Br]SO$_4$. Same formula, different ions in solution.', 'c_coord_nomenclature_isomerism', 1, 'JEE Mains Prep', 'approved'),
('Linkage isomerism occurs with', 'Ambidentate ligands that can bind through different donor atoms', 'Monodentate ligands only', 'Bidentate ligands', 'No ligands', 'option1', 'E.g., [Co(NH$_3$)$_5$NO$_2$]$^{2+}$ (nitro, N-bonded) vs [Co(NH$_3$)$_5$ONO]$^{2+}$ (nitrito, O-bonded).', 'c_coord_nomenclature_isomerism', 1, 'JEE Mains Prep', 'approved'),
('The IUPAC name of K$_3$[Fe(CN)$_6$] is', 'Potassium hexacyanidoferrate(II)', 'Potassium hexacyanidoferrate(III)', 'Tripotassium hexacyanidoiron(III)', 'Ferric potassium cyanide', 'option2', 'Anionic complex: metal name ends in $-ate$. Fe $\to$ ferrate. OS: $x + 6(-1) = -3$, $x = +3$.', 'c_coord_nomenclature_isomerism', 2, 'JEE Mains Prep', 'approved'),
('The complex [Co(en)$_2$Cl$_2$]$^+$ can show', 'Both geometric (cis/trans) and optical isomerism', 'Only geometric isomerism', 'Only optical isomerism', 'No isomerism', 'option1', 'Octahedral with 2 bidentate + 2 monodentate: cis and trans isomers. The cis form is chiral (optical isomers). Trans is achiral.', 'c_coord_nomenclature_isomerism', 2, 'JEE Mains Prep', 'approved'),
('The cis isomer of [Pt(NH$_3$)$_2$Cl$_2$] (cisplatin) is used as', 'A food additive', 'A fertilizer', 'An anticancer drug', 'A fuel', 'option3', 'Cisplatin: cis-[Pt(NH$_3$)$_2$Cl$_2$]. Binds to DNA, preventing replication. The trans isomer is inactive.', 'c_coord_nomenclature_isomerism', 2, 'JEE Mains Prep', 'approved'),
('Coordination isomerism occurs in compounds that have', 'Only neutral complexes', 'Only one complex ion', 'No complex ions', 'Both cationic and anionic complex ions, which can exchange ligands', 'option4', 'E.g., [Co(NH$_3$)$_6$][Cr(CN)$_6$] vs [Cr(NH$_3$)$_6$][Co(CN)$_6$]. Metals exchange coordination spheres.', 'c_coord_nomenclature_isomerism', 2, 'JEE Mains Prep', 'approved'),
('The number of geometric isomers of [Ma$_2$b$_2$c$_2$] (octahedral, all monodentate) is', '$2$', '$3$', '$5$', '$6$', 'option3', 'For [Ma$_2$b$_2$c$_2$]: 5 geometric isomers (all-cis, all-trans, and 3 mixed arrangements).', 'c_coord_nomenclature_isomerism', 2, 'JEE Mains Prep', 'approved'),
('Hydrate isomerism is a type of', 'Linkage isomerism', 'Geometric isomerism', 'Optical isomerism', 'Ionization isomerism involving water molecules', 'option4', 'E.g., [Cr(H$_2$O)$_6$]Cl$_3$ (violet) vs [Cr(H$_2$O)$_5$Cl]Cl$_2 \cdot$ H$_2$O (green) vs [Cr(H$_2$O)$_4$Cl$_2$]Cl $\cdot$ 2H$_2$O (dark green).', 'c_coord_nomenclature_isomerism', 2, 'JEE Mains Prep', 'approved'),
('The prefixes used for ligand numbers in IUPAC nomenclature are', 'di, tri, tetra for simple ligands; bis, tris, tetrakis for complex ligands', 'Always di, tri, tetra', 'Always bis, tris, tetrakis', 'No prefixes are used', 'option1', 'Simple: di-, tri-, tetra-. Complex (e.g., en, PPh$_3$): bis-, tris-, tetrakis- (in parentheses).', 'c_coord_nomenclature_isomerism', 2, 'JEE Mains Prep', 'approved'),
('The octahedral complex [Co(en)$_3$]$^{3+}$ shows', 'Both geometric and optical', 'Only geometric isomerism', 'Only optical isomerism (no geometric isomers possible)', 'No isomerism', 'option3', 'All three en are equivalent in an octahedral arrangement. No cis/trans possible. But the complex is chiral ($D_3$ symmetry) $\to$ optical isomers ($\Delta$ and $\Lambda$).', 'c_coord_nomenclature_isomerism', 3, 'JEE Mains Prep', 'approved'),
('The fac (facial) and mer (meridional) isomers are types of geometric isomers in', 'Octahedral [Ma$_3$b$_3$] complexes', 'Tetrahedral complexes', 'Square planar complexes', 'Linear complexes', 'option1', 'fac: three identical ligands on one triangular face. mer: three identical ligands in a plane containing the metal.', 'c_coord_nomenclature_isomerism', 3, 'JEE Mains Prep', 'approved'),
('The total number of isomers (geometric + optical) of [Co(en)$_2$Cl$_2$]$^+$ is', '$2$', '$3$', '$4$', '$5$', 'option2', 'Trans (1, achiral) + cis (1 pair of enantiomers $= 2$). Total distinct isomers $= 3$.', 'c_coord_nomenclature_isomerism', 3, 'JEE Mains Prep', 'approved'),
('Square planar complexes of type [Mabcd] (4 different monodentate ligands) show', '$3$ geometric isomers', '$2$ geometric isomers', '$6$ geometric isomers', '$1$ isomer only', 'option1', '[Mabcd] square planar: 3 geometric isomers (based on which pair is trans to each other).', 'c_coord_nomenclature_isomerism', 3, 'JEE Mains Prep', 'approved'),
('The IUPAC name of [CoCl$_2$(en)$_2$]$^+$ (cis isomer) is', 'cis-dichloridodiethylenediaminecobalt(III) ion', 'cis-bis(ethylenediamine)dichloridocobalt(III) ion', 'cis-cobalt(III) bis(ethylenediamine) dichloride', 'cis-dichloridocobalt(III) bis(ethylenediamine)', 'option2', 'Alphabetical: bis(ethylenediamine) before dichlorido. Metal: cobalt(III). Prefix cis- for geometry.', 'c_coord_nomenclature_isomerism', 3, 'JEE Mains Prep', 'approved'),
('Solvate isomerism differs from hydrate isomerism in that', 'Solvate isomerism involves metals only', 'They are identical', 'The solvent is not water (e.g., alcohol)', 'Hydrate isomerism does not exist', 'option3', 'Solvate isomerism is the general case; hydrate isomerism is the specific case when the solvent is water.', 'c_coord_nomenclature_isomerism', 3, 'JEE Mains Prep', 'approved'),
('Tetrahedral complexes generally do not show geometric isomerism because', 'They are always symmetric', 'All positions in a tetrahedron are equivalent (no cis/trans distinction)', 'They have no ligands', 'They are always colourless', 'option2', 'In a tetrahedron, every pair of positions is equivalent. No distinction between cis and trans.', 'c_coord_nomenclature_isomerism', 3, 'JEE Mains Prep', 'approved'),

-- ============================================================
-- c_coord_bonding_cft (7 easy, 7 medium, 7 hard = 21)
-- VBT approach, crystal field theory, colour, magnetism
-- ============================================================
('Crystal Field Theory (CFT) treats the metal-ligand interaction as', 'Purely covalent', 'Purely electrostatic (ionic)', 'Metallic bonding', 'Hydrogen bonding', 'option2', 'CFT: ligands are point charges/dipoles that create an electrostatic field, splitting the $d$ orbitals of the metal.', 'c_coord_bonding_cft', 1, 'JEE Mains Prep', 'approved'),
('In an octahedral crystal field, the $d$ orbitals split into', '$e_g$ (lower) and $t_{2g}$ (higher)', '$t_{2g}$ (lower energy) and $e_g$ (higher energy)', 'All remain degenerate', '$a_{1g}$ and $b_{1g}$', 'option2', 'Octahedral: $d_{xy}, d_{xz}, d_{yz}$ ($t_{2g}$, lower) and $d_{z^2}, d_{x^2-y^2}$ ($e_g$, higher). Splitting $= \Delta_o$.', 'c_coord_bonding_cft', 1, 'JEE Mains Prep', 'approved'),
('The crystal field splitting energy in an octahedral field is denoted', '$\Delta_t$', '$\Delta_o$', '$\Delta_s$', '$\Delta_p$', 'option2', '$\Delta_o$ (octahedral). $\Delta_t$ (tetrahedral). $\Delta_o \approx \frac{9}{4}\Delta_t$ (tetrahedral splitting is smaller).', 'c_coord_bonding_cft', 1, 'JEE Mains Prep', 'approved'),
('Strong field ligands (e.g., CN$^-$, CO) cause', 'Large $\Delta_o$ and low spin complexes', 'Small $\Delta_o$ and high spin complexes', 'No splitting', 'Only tetrahedral complexes', 'option1', 'Large $\Delta_o$: electrons pair up in $t_{2g}$ before occupying $e_g$ $\to$ low spin (fewer unpaired electrons).', 'c_coord_bonding_cft', 1, 'JEE Mains Prep', 'approved'),
('Weak field ligands (e.g., I$^-$, Br$^-$, Cl$^-$) cause', 'Large $\Delta_o$', 'Small $\Delta_o$ and high spin complexes', 'No splitting', 'Low spin complexes', 'option2', 'Small $\Delta_o$: electrons occupy $e_g$ before pairing in $t_{2g}$ $\to$ high spin (more unpaired electrons).', 'c_coord_bonding_cft', 1, 'JEE Mains Prep', 'approved'),
('The colour of a complex is determined by', 'The temperature only', 'The size of the metal', 'The charge of the counter ion', 'The wavelength of light absorbed during $d$-$d$ transitions (complementary colour is observed)', 'option4', 'Absorbed wavelength depends on $\Delta_o$. Transmitted/reflected light is the complementary colour.', 'c_coord_bonding_cft', 1, 'JEE Mains Prep', 'approved'),
('In VBT (Valence Bond Theory), the hybridization of the central metal in an octahedral complex is', '$sp^3$', '$dsp^2$', '$sp^3d^2$ or $d^2sp^3$', '$sp$', 'option3', 'Octahedral: $sp^3d^2$ (outer orbital, high spin) or $d^2sp^3$ (inner orbital, low spin).', 'c_coord_bonding_cft', 1, 'JEE Mains Prep', 'approved'),
('[Fe(CN)$_6$]$^{4-}$ is diamagnetic while [Fe(H$_2$O)$_6$]$^{2+}$ is paramagnetic because', 'H$_2$O is a strong field ligand', 'Fe has different oxidation states', 'CN$^-$ is neutral', 'CN$^-$ is a strong field ligand (large $\Delta_o$, low spin) while H$_2$O is weak field (small $\Delta_o$, high spin)', 'option4', 'Fe$^{2+}$ ($d^6$): with CN$^-$ (strong field): $t_{2g}^6 e_g^0$ (0 unpaired, diamagnetic). With H$_2$O (weak field): $t_{2g}^4 e_g^2$ (4 unpaired, paramagnetic).', 'c_coord_bonding_cft', 2, 'JEE Mains Prep', 'approved'),
('The Crystal Field Stabilization Energy (CFSE) for a $d^3$ ion in an octahedral field is', '$-1.2\Delta_o$', '$-0.4\Delta_o$', '$-0.8\Delta_o$', '$0$', 'option1', '$d^3$: $t_{2g}^3$. CFSE $= 3(-0.4\Delta_o) = -1.2\Delta_o$. Maximum CFSE for $d^3$ and $d^8$ (high spin).', 'c_coord_bonding_cft', 2, 'JEE Mains Prep', 'approved'),
('Tetrahedral complexes are almost always high spin because', '$\Delta_t$ is much smaller than $\Delta_o$ ($\Delta_t \approx 4/9 \Delta_o$), so pairing energy is rarely exceeded', 'They have no $d$ electrons', 'All ligands are strong field', 'Tetrahedral geometry prevents splitting', 'option1', 'Small $\Delta_t$ means it is almost always energetically favourable to occupy higher orbitals rather than pair up.', 'c_coord_bonding_cft', 2, 'JEE Mains Prep', 'approved'),
('The spectrochemical series for common ligands in order of increasing $\Delta_o$ is', 'I$^- <$ Br$^- <$ Cl$^- <$ F$^- <$ OH$^- <$ H$_2$O $<$ NH$_3 <$ en $<$ NO$_2^- <$ CN$^- <$ CO', 'CO $<$ CN$^- <$ NH$_3 <$ H$_2$O $<$ F$^-$', 'All ligands cause the same splitting', 'F$^- >$ Cl$^- >$ Br$^- >$ I$^-$ only', 'option1', 'Weak field (left) to strong field (right). This order is largely independent of the metal.', 'c_coord_bonding_cft', 2, 'JEE Mains Prep', 'approved'),
('In a square planar crystal field, the $d$ orbital with the highest energy is', '$d_{xy}$', '$d_{z^2}$', '$d_{x^2-y^2}$', '$d_{xz}$', 'option3', 'Square planar: $d_{x^2-y^2}$ points directly at ligands $\to$ highest energy. Order: $d_{x^2-y^2} > d_{xy} > d_{z^2} > d_{xz}, d_{yz}$.', 'c_coord_bonding_cft', 2, 'JEE Mains Prep', 'approved'),
('$d^8$ complexes (e.g., Ni$^{2+}$, Pd$^{2+}$, Pt$^{2+}$) with strong field ligands prefer', 'Octahedral geometry', 'Square planar geometry (all electrons paired)', 'Tetrahedral geometry', 'Linear geometry', 'option2', 'Strong field + $d^8$: large CFSE in square planar ($d_{x^2-y^2}$ empty). All 8 electrons paired $\to$ diamagnetic. E.g., [Ni(CN)$_4$]$^{2-}$.', 'c_coord_bonding_cft', 2, 'JEE Mains Prep', 'approved'),
('[Ni(CN)$_4$]$^{2-}$ is diamagnetic and square planar, while [NiCl$_4$]$^{2-}$ is paramagnetic and tetrahedral. This is because', 'CN$^-$ (strong field) forces pairing and square planar geometry; Cl$^-$ (weak field) gives tetrahedral', 'Ni has different oxidation states', 'CN$^-$ is weak field', 'Cl$^-$ is strong field', 'option1', 'Ni$^{2+}$ ($d^8$): CN$^-$ causes large splitting $\to$ $dsp^2$ square planar (0 unpaired). Cl$^-$ causes small splitting $\to$ $sp^3$ tetrahedral (2 unpaired).', 'c_coord_bonding_cft', 2, 'JEE Mains Prep', 'approved'),
('The CFSE for a $d^6$ low spin octahedral complex is', '$-2.4\Delta_o + 2P$', '$-0.4\Delta_o$', '$-2.4\Delta_o$', '$0$', 'option1', '$d^6$ low spin: $t_{2g}^6 e_g^0$. CFSE $= 6(-0.4\Delta_o) + 0(0.6\Delta_o) = -2.4\Delta_o$. But 2 extra pairings needed (vs free ion): add $2P$.', 'c_coord_bonding_cft', 3, 'JEE Mains Prep', 'approved'),
('The Jahn-Teller theorem predicts distortion for', 'Only tetrahedral complexes', 'All complexes', 'Octahedral complexes with unequally filled $e_g$ or $t_{2g}$ orbitals (e.g., $d^4$ high spin, $d^9$)', 'Only square planar complexes', 'option3', 'Unequal occupation of degenerate orbitals $\to$ distortion to remove degeneracy and lower energy. Strongest for $e_g$ (e.g., Cu$^{2+}$ $d^9$: $e_g^3$).', 'c_coord_bonding_cft', 3, 'JEE Mains Prep', 'approved'),
('The $\Delta_o$ value for [Co(NH$_3$)$_6$]$^{3+}$ is larger than for [CoF$_6$]$^{3-}$ because', 'Co has different oxidation states', 'F$^-$ is a stronger field ligand', 'NH$_3$ is higher in the spectrochemical series than F$^-$', 'NH$_3$ is an anion', 'option3', 'NH$_3$ $>$ F$^-$ in spectrochemical series. [Co(NH$_3$)$_6$]$^{3+}$ is low spin (diamagnetic); [CoF$_6$]$^{3-}$ is high spin (paramagnetic).', 'c_coord_bonding_cft', 3, 'JEE Mains Prep', 'approved'),
('The Ligand Field Theory (LFT) improves upon CFT by', 'Incorporating covalent (MO) character of metal-ligand bonds while retaining the crystal field splitting concept', 'Ignoring $d$ orbital splitting', 'Treating all bonds as purely ionic', 'Eliminating the spectrochemical series', 'option1', 'LFT combines CFT (electrostatic splitting) with MO theory (covalent $\sigma$ and $\pi$ bonding). Explains $\pi$-bonding effects on $\Delta$.', 'c_coord_bonding_cft', 3, 'JEE Mains Prep', 'approved'),
('$\pi$-acceptor ligands (CO, CN$^-$) increase $\Delta_o$ because', 'They donate $\pi$ electrons to the metal', 'They accept electron density from filled metal $t_{2g}$ orbitals into their empty $\pi^*$ orbitals, stabilizing $t_{2g}$', 'They have no effect on $\Delta$', 'They destabilize $t_{2g}$', 'option2', 'Back-bonding: metal $t_{2g} \to$ ligand $\pi^*$. This lowers $t_{2g}$ energy, increasing the gap $\Delta_o$. Explains why CO, CN$^-$ are strong field.', 'c_coord_bonding_cft', 3, 'JEE Mains Prep', 'approved'),
('$\pi$-donor ligands (Cl$^-$, Br$^-$, I$^-$) decrease $\Delta_o$ because', 'They donate electron density from their filled $p$ orbitals into metal $t_{2g}$, raising $t_{2g}$ energy', 'They accept electrons from the metal', 'They have no $\pi$ interaction', 'They increase $\Delta_o$', 'option1', '$\pi$-donation: ligand filled $p \to$ metal $t_{2g}$. This raises $t_{2g}$ energy, decreasing $\Delta_o$. Explains why halides are weak field.', 'c_coord_bonding_cft', 3, 'JEE Mains Prep', 'approved'),
('The number of unpaired electrons in [Mn(CN)$_6$]$^{4-}$ (Mn$^{2+}$, $d^5$, strong field) is', '$5$', '$3$', '$1$', '$0$', 'option3', 'Strong field $d^5$: $t_{2g}^5 e_g^0$ (low spin). 1 unpaired electron. $\mu = \sqrt{1 \times 3} = 1.73\;\text{BM}$.', 'c_coord_bonding_cft', 3, 'JEE Mains Prep', 'approved'),

-- ============================================================
-- c_coord_applications (7 easy, 7 medium, 7 hard = 21)
-- Applications in analysis, extraction, biological systems
-- ============================================================
('EDTA is used in analytical chemistry for', 'Redox titrations', 'Acid-base titrations', 'Complexometric titrations to determine metal ion concentrations', 'Precipitation titrations only', 'option3', 'EDTA forms stable 1:1 complexes with most metal ions. Used to determine hardness of water (Ca$^{2+}$, Mg$^{2+}$).', 'c_coord_applications', 1, 'JEE Mains Prep', 'approved'),
('Haemoglobin contains a coordination compound of', 'Cu', 'Fe (in a porphyrin ring)', 'Zn', 'Mn', 'option2', 'Haemoglobin: Fe$^{2+}$ in a porphyrin (heme) ring. Binds O$_2$ reversibly for transport in blood.', 'c_coord_applications', 1, 'JEE Mains Prep', 'approved'),
('Chlorophyll contains a coordination compound of', 'Fe', 'Cu', 'Mg (in a porphyrin ring)', 'Zn', 'option3', 'Chlorophyll: Mg$^{2+}$ at the centre of a modified porphyrin. Essential for photosynthesis.', 'c_coord_applications', 1, 'JEE Mains Prep', 'approved'),
('Vitamin B$_{12}$ (cyanocobalamin) contains', 'Fe', 'Co (in a corrin ring)', 'Cu', 'Zn', 'option2', 'B$_{12}$: Co$^{3+}$ in a corrin ring (similar to porphyrin). Essential for red blood cell formation.', 'c_coord_applications', 1, 'JEE Mains Prep', 'approved'),
('In qualitative analysis, Ni$^{2+}$ is detected using', 'AgNO$_3$', 'NaOH only', 'HCl', 'Dimethylglyoxime (DMG) which forms a red chelate complex', 'option4', 'Ni$^{2+}$ + 2 DMG $\to$ red precipitate of bis(dimethylglyoximato)nickel(II). Highly specific test.', 'c_coord_applications', 1, 'JEE Mains Prep', 'approved'),
('The cyanide process for extraction of gold involves', 'Forming a soluble gold cyanide complex [Au(CN)$_2$]$^-$', 'Melting gold directly', 'Using HCl', 'Electrolysis only', 'option1', '4Au + 8NaCN + 2H$_2$O + O$_2 \to$ 4Na[Au(CN)$_2$] + 4NaOH. Gold dissolves as a complex, then is recovered by reduction with Zn.', 'c_coord_applications', 1, 'JEE Mains Prep', 'approved'),
('Cisplatin [cis-Pt(NH$_3$)$_2$Cl$_2$] is used as', 'An anticancer drug', 'A fertilizer', 'A food preservative', 'A fuel additive', 'option1', 'Cisplatin cross-links DNA strands, preventing cell division. Used against testicular, ovarian, and bladder cancers.', 'c_coord_applications', 1, 'JEE Mains Prep', 'approved'),
('Carbon monoxide poisoning occurs because CO', 'Dissolves in blood', 'Reacts with water', 'Is an acid', 'Forms a very stable complex with haemoglobin (carboxyhaemoglobin), preventing O$_2$ binding', 'option4', 'CO binds to Fe$^{2+}$ in haemoglobin $\sim 200\times$ more strongly than O$_2$, blocking oxygen transport.', 'c_coord_applications', 2, 'JEE Mains Prep', 'approved'),
('In photography, unexposed AgBr is removed by', 'Water', 'Sodium thiosulfate (hypo) which forms a soluble complex [Ag(S$_2$O$_3$)$_2$]$^{3-}$', 'HCl', 'NaOH', 'option2', 'AgBr + 2Na$_2$S$_2$O$_3 \to$ Na$_3$[Ag(S$_2$O$_3$)$_2$] + NaBr. The complex is soluble, "fixing" the image.', 'c_coord_applications', 2, 'JEE Mains Prep', 'approved'),
('Electroplating of metals often uses coordination compounds because', 'Simple salts give better deposits', 'Complex ions release metal slowly, giving a smooth, uniform deposit', 'Complexes are cheaper', 'No electricity is needed', 'option2', 'E.g., silver plating uses K[Ag(CN)$_2$] instead of AgNO$_3$. Slow release of Ag$^+$ from the complex gives a fine-grained deposit.', 'c_coord_applications', 2, 'JEE Mains Prep', 'approved'),
('EDTA is used to treat heavy metal poisoning because', 'It kills bacteria', 'It neutralizes acids', 'It is a vitamin', 'It chelates toxic metal ions (Pb$^{2+}$, Hg$^{2+}$) forming stable, excretable complexes', 'option4', 'Chelation therapy: EDTA wraps around the toxic metal, making it water-soluble and allowing kidney excretion.', 'c_coord_applications', 2, 'JEE Mains Prep', 'approved'),
('Wilkinson''s catalyst [RhCl(PPh$_3$)$_3$] is used for', 'Polymerization', 'Heterogeneous catalysis', 'Homogeneous hydrogenation of alkenes', 'Acid-base reactions', 'option3', 'Rh$^+$ ($d^8$) complex catalyzes H$_2$ addition to C=C bonds in solution. Important in organic synthesis.', 'c_coord_applications', 2, 'JEE Mains Prep', 'approved'),
('Ziegler-Natta catalyst (TiCl$_4$ + Al(C$_2$H$_5$)$_3$) is used for', 'Reduction of metal ores', 'Hydrogenation', 'Oxidation', 'Polymerization of ethylene and propylene', 'option4', 'Produces stereoregular (isotactic) polymers. Ti acts as the coordination site for monomer insertion.', 'c_coord_applications', 2, 'JEE Mains Prep', 'approved'),
('The hardness of water is determined by titration with EDTA using', 'Starch', 'Phenolphthalein', 'Methyl orange', 'Eriochrome Black T (EBT) as indicator', 'option4', 'EBT forms a wine-red complex with Ca$^{2+}$/Mg$^{2+}$. At endpoint, EDTA displaces EBT $\to$ blue colour.', 'c_coord_applications', 2, 'JEE Mains Prep', 'approved'),
('The stability of metal-EDTA complexes follows the Irving-Williams series. The most stable divalent complex is with', 'Mn$^{2+}$', 'Cu$^{2+}$', 'Zn$^{2+}$', 'Ca$^{2+}$', 'option2', 'Irving-Williams: Mn $<$ Fe $<$ Co $<$ Ni $<$ Cu $>$ Zn. Cu$^{2+}$-EDTA is the most stable ($\log K_f = 18.8$).', 'c_coord_applications', 3, 'JEE Mains Prep', 'approved'),
('MRI (Magnetic Resonance Imaging) contrast agents often use', 'Zn$^{2+}$ complexes', 'Fe$^{2+}$ complexes', 'Cu$^{2+}$ complexes', 'Gd$^{3+}$ complexes (paramagnetic, 7 unpaired electrons)', 'option4', 'Gd$^{3+}$ ($f^7$, 7 unpaired electrons) is strongly paramagnetic. Chelated with DTPA or DOTA to reduce toxicity.', 'c_coord_applications', 3, 'JEE Mains Prep', 'approved'),
('The trans effect in square planar Pt(II) chemistry is used to', 'Determine oxidation states', 'Selectively synthesize cis or trans isomers by controlling the order of ligand substitution', 'Measure magnetic moments', 'Calculate CFSE', 'option2', 'Trans effect order: CO $>$ CN$^- >$ NO$_2^- >$ I$^- >$ Br$^- >$ Cl$^- >$ NH$_3 >$ OH$^-$. Ligands with high trans effect labilize the ligand trans to them.', 'c_coord_applications', 3, 'JEE Mains Prep', 'approved'),
('Carbonic anhydrase (a zinc enzyme) catalyzes', 'Protein synthesis', 'CO$_2$ + H$_2$O $\rightleftharpoons$ H$_2$CO$_3$ (hydration of CO$_2$)', 'DNA replication', 'Fat metabolism', 'option2', 'Zn$^{2+}$ at the active site activates a water molecule for nucleophilic attack on CO$_2$. One of the fastest enzymes known.', 'c_coord_applications', 3, 'JEE Mains Prep', 'approved'),
('The Wacker process uses PdCl$_2$/CuCl$_2$ catalyst for', 'Oxidation of ethylene to acetaldehyde', 'Reduction of ketones', 'Polymerization', 'Hydrogenation', 'option1', 'CH$_2$=CH$_2$ + PdCl$_2$ + H$_2$O $\to$ CH$_3$CHO + Pd + 2HCl. CuCl$_2$ reoxidizes Pd. Industrial process.', 'c_coord_applications', 3, 'JEE Mains Prep', 'approved'),
('The chelate effect has an entropic origin. When [Ni(H$_2$O)$_6$]$^{2+}$ reacts with 3 en to form [Ni(en)$_3$]$^{2+}$, the number of free particles', 'Decreases', 'Increases from 4 to 7 (favourable $\Delta S$)', 'Remains the same', 'Becomes zero', 'option2', 'Reactants: 1 complex + 3 en $= 4$ particles. Products: 1 complex + 6 H$_2$O $= 7$ particles. $\Delta S > 0$ drives the reaction.', 'c_coord_applications', 3, 'JEE Mains Prep', 'approved'),
('Prussian blue (Fe$_4$[Fe(CN)$_6$]$_3$) is used as', 'A pigment and an antidote for thallium/caesium poisoning', 'A food additive', 'A fuel', 'A fertilizer', 'option1', 'Prussian blue: intense blue pigment. Medically: traps Cs$^+$/Tl$^+$ in the gut via ion exchange, preventing absorption.', 'c_coord_applications', 3, 'JEE Mains Prep', 'approved');
