-- Learn.ai JEE Mains Question Seed: Physics Units 1-5
-- High-quality questions, every answer verified
-- Remove placeholder physics questions first
DELETE FROM questions WHERE concept_id LIKE 'p_%' AND source = 'Seed';

INSERT INTO questions (question_text, option1, option2, option3, option4, correct_answer, solution_text, concept_id, difficulty_tier, source, status) VALUES

-- ============================================================
-- p_units_si_system (5 easy, 5 medium, 5 hard = 15)
-- ============================================================
('Which of the following is a fundamental SI unit?', 'Newton', 'Kilogram', 'Joule', 'Pascal', 'option2', 'Kilogram is one of the 7 SI base units. Newton, Joule, and Pascal are derived.', 'p_units_si_system', 1, 'JEE Mains Prep', 'approved'),
('The SI unit of luminous intensity is', 'Candela', 'Lumen', 'Lux', 'Watt', 'option1', 'Candela (cd) is the SI base unit of luminous intensity.', 'p_units_si_system', 1, 'JEE Mains Prep', 'approved'),
('How many base quantities exist in the SI system?', '5', '7', '6', '3', 'option2', 'SI has 7 base quantities: length, mass, time, current, temperature, amount of substance, luminous intensity.', 'p_units_si_system', 1, 'JEE Mains Prep', 'approved'),
('One light year is a unit of', 'Distance', 'Time', 'Speed', 'Intensity', 'option1', 'A light year is the distance light travels in one year, about $9.46 \times 10^{15}$ m.', 'p_units_si_system', 1, 'JEE Mains Prep', 'approved'),
('The CGS unit of force is', 'Dyne', 'Newton', 'Poundal', 'Kilogram-force', 'option1', 'In CGS, force is measured in dynes. $1\;\text{dyne} = 10^{-5}\;\text{N}$.', 'p_units_si_system', 1, 'JEE Mains Prep', 'approved'),
('In base SI units, $1\;\text{Pa}$ equals', '$\text{kg}\;\text{m}^{-1}\;\text{s}^{-2}$', '$\text{kg}\;\text{m}\;\text{s}^{-2}$', '$\text{kg}\;\text{m}^{-2}\;\text{s}^{-1}$', '$\text{kg}\;\text{m}^2\;\text{s}^{-2}$', 'option1', '$\text{Pa} = \text{N/m}^2 = \text{kg}\cdot\text{m}\cdot\text{s}^{-2}/\text{m}^2 = \text{kg}\;\text{m}^{-1}\;\text{s}^{-2}$.', 'p_units_si_system', 2, 'JEE Mains Prep', 'approved'),
('Planck''s constant has the same dimensions as', 'Force', 'Linear momentum', 'Angular momentum', 'Energy', 'option3', '$[h] = \text{J}\cdot\text{s} = \text{kg}\;\text{m}^2\;\text{s}^{-1}$, same as angular momentum $[mvr]$.', 'p_units_si_system', 2, 'JEE Mains Prep', 'approved'),
('The ratio $1\;\text{J} : 1\;\text{erg}$ equals', '$10^{-7}$', '$10^7$', '$10^5$', '$10^{-5}$', 'option2', '$1\;\text{J} = 10^3\;\text{g}\cdot(10^2\;\text{cm})^2\cdot\text{s}^{-2} = 10^7\;\text{erg}$.', 'p_units_si_system', 2, 'JEE Mains Prep', 'approved'),
('Which pair has the same dimensions?', 'Velocity and acceleration', 'Force and pressure', 'Momentum and energy', 'Work and torque', 'option4', 'Both work and torque have dimensions $[\text{ML}^2\text{T}^{-2}]$.', 'p_units_si_system', 2, 'JEE Mains Prep', 'approved'),
('If the unit of force is $100\;\text{N}$, length is $10\;\text{m}$, and time is $100\;\text{s}$, the unit of mass is', '$10^2\;\text{kg}$', '$10^4\;\text{kg}$', '$10^3\;\text{kg}$', '$10^5\;\text{kg}$', 'option4', 'Acceleration $= 10/100^2 = 10^{-3}\;\text{m/s}^2$. Mass $= 100/10^{-3} = 10^5\;\text{kg}$.', 'p_units_si_system', 2, 'JEE Mains Prep', 'approved'),
('If momentum $P$, area $A$, and time $T$ are fundamental, the dimension of energy is', '$[P^{1/2}A^{1/2}T^{-1}]$', '$[P^2 A^{-1}]$', '$[PAT^{-1}]$', '$[PA^{1/2}T^{-1}]$', 'option4', 'Energy $= P^a A^b T^c$. Comparing $[\text{ML}^2\text{T}^{-2}]$ with $[\text{MLT}^{-1}]^a[\text{L}^2]^b[\text{T}]^c$: $a=1, b=1/2, c=-1$.', 'p_units_si_system', 3, 'JEE Mains Prep', 'approved'),
('If velocity $V$, force $F$, and energy $E$ are fundamental, the dimension of mass is', '$[EV^{-2}]$', '$[FV^{-1}]$', '$[EF^{-1}V]$', '$[F^2E^{-1}]$', 'option1', 'Mass $= V^a F^b E^c$. Solving: $a=-2, b=0, c=1$. So mass $= [EV^{-2}]$.', 'p_units_si_system', 3, 'JEE Mains Prep', 'approved'),
('The frequency $f$ of a stretched string depends on length $l$, linear density $m$, and tension $T$. By dimensional analysis, $f \propto$', '$l^{-1}\sqrt{m/T}$', '$l\sqrt{m/T}$', '$l^{-1}\sqrt{T/m}$', '$l\sqrt{T/m}$', 'option3', '$f = kl^a m^b T^c$. Solving: $a=-1, b=-1/2, c=1/2$. So $f \propto l^{-1}\sqrt{T/m}$.', 'p_units_si_system', 3, 'JEE Mains Prep', 'approved'),
('The fine structure constant $\alpha = e^2/(4\pi\epsilon_0\hbar c)$ is', 'Has dimensions of charge', 'Dimensionless', 'Has dimensions of energy', 'Has dimensions of length', 'option2', '$[e^2/(4\pi\epsilon_0)] = [\text{ML}^3\text{T}^{-2}]$ and $[\hbar c] = [\text{ML}^3\text{T}^{-2}]$. The ratio is dimensionless ($\alpha \approx 1/137$).', 'p_units_si_system', 3, 'JEE Mains Prep', 'approved'),
('If $c$, $G$, and $h$ are fundamental units, the Planck length equals', '$\sqrt{hG/c^3}$', '$\sqrt{hc/G}$', '$\sqrt{Gc^3/h}$', '$\sqrt{h/(Gc^3)}$', 'option1', 'Let $L = c^a G^b h^d$. Solving: $a=-3/2, b=1/2, d=1/2$. So $L = \sqrt{hG/c^3}$.', 'p_units_si_system', 3, 'JEE Mains Prep', 'approved'),

-- ============================================================
-- p_least_count_errors (5 easy, 5 medium, 5 hard = 15)
-- ============================================================
('The number of significant figures in $0.00340$ is', '2', '5', '3', '4', 'option3', 'Leading zeros are not significant. Digits 3, 4, and the trailing 0 are significant: 3 total.', 'p_least_count_errors', 1, 'JEE Mains Prep', 'approved'),
('The number of significant figures in $6.023 \times 10^{23}$ is', '23', '4', '24', '3', 'option2', 'In scientific notation, count digits in the coefficient: $6.023$ has 4 significant figures.', 'p_least_count_errors', 1, 'JEE Mains Prep', 'approved'),
('The least count of a vernier caliper with 10 VSD $= 9$ MSD and 1 MSD $= 1\;\text{mm}$ is', '$1\;\text{mm}$', '$0.01\;\text{mm}$', '$0.1\;\text{mm}$', '$0.5\;\text{mm}$', 'option3', 'LC $= 1\;\text{MSD} - 1\;\text{VSD} = 1 - 9/10 = 0.1\;\text{mm}$.', 'p_least_count_errors', 1, 'JEE Mains Prep', 'approved'),
('If $a = 5.0 \pm 0.2$ and $b = 3.0 \pm 0.1$, the absolute error in $a + b$ is', '$\pm 0.1$', '$\pm 0.2$', '$\pm 0.3$', '$\pm 0.15$', 'option3', 'For addition, absolute errors add: $\Delta(a+b) = 0.2 + 0.1 = 0.3$.', 'p_least_count_errors', 1, 'JEE Mains Prep', 'approved'),
('The number of significant figures in $100.0$ is', '3', '1', '4', '5', 'option3', 'The trailing zero after the decimal is significant. $100.0$ has 4 significant figures.', 'p_least_count_errors', 1, 'JEE Mains Prep', 'approved'),
('The $\%$ error in $A = a^2 b^{1/3}/c^3$ given $\%$ errors in $a, b, c$ are $1\%, 3\%, 2\%$ is', '$7\%$', '$9\%$', '$5\%$', '$10\%$', 'option2', '$\%$ error $= 2(1) + (1/3)(3) + 3(2) = 2 + 1 + 6 = 9\%$.', 'p_least_count_errors', 2, 'JEE Mains Prep', 'approved'),
('A wire has $l = 8.0 \pm 0.4\;\text{cm}$ and $r = 1.0 \pm 0.1\;\text{cm}$. The $\%$ error in volume ($\pi r^2 l$) is', '$25\%$', '$15\%$', '$20\%$', '$10\%$', 'option1', '$\%$ error $= 2(0.1/1.0)(100) + (0.4/8.0)(100) = 20 + 5 = 25\%$.', 'p_least_count_errors', 2, 'JEE Mains Prep', 'approved'),
('If $T = 2\pi\sqrt{l/g}$ and $l$ has $2\%$ error, $T$ has $1\%$ error, the $\%$ error in $g$ is', '$5\%$', '$3\%$', '$4\%$', '$2\%$', 'option3', '$g = 4\pi^2 l/T^2$. $\%$ error in $g = 2 + 2(1) = 4\%$.', 'p_least_count_errors', 2, 'JEE Mains Prep', 'approved'),
('The LC of a screw gauge with pitch $0.5\;\text{mm}$ and $50$ circular divisions is', '$0.001\;\text{mm}$', '$0.1\;\text{mm}$', '$0.01\;\text{mm}$', '$0.05\;\text{mm}$', 'option3', 'LC $= 0.5/50 = 0.01\;\text{mm}$.', 'p_least_count_errors', 2, 'JEE Mains Prep', 'approved'),
('$2.4 \times 3.65$ rounded to correct significant figures is', '$8.8$', '$8.76$', '$8.760$', '$9.0$', 'option1', '$2.4 \times 3.65 = 8.76$. Result must have 2 significant figures (least of the factors). So $8.8$.', 'p_least_count_errors', 2, 'JEE Mains Prep', 'approved'),
('Density of a cube: $m = 2.00 \pm 0.01\;\text{g}$, side $l = 1.00 \pm 0.01\;\text{cm}$. Max $\%$ error in density is', '$3.0\%$', '$4.0\%$', '$3.5\%$', '$2.5\%$', 'option3', '$\rho = m/l^3$. $\%$ error $= (0.01/2.00)(100) + 3(0.01/1.00)(100) = 0.5 + 3.0 = 3.5\%$.', 'p_least_count_errors', 3, 'JEE Mains Prep', 'approved'),
('$R = V/I$ where $V = 100 \pm 5\;\text{V}$ and $I = 10 \pm 0.2\;\text{A}$. The $\%$ error in $R$ is', '$10\%$', '$5\%$', '$2\%$', '$7\%$', 'option4', '$\%$ error $= (5/100)(100) + (0.2/10)(100) = 5 + 2 = 7\%$.', 'p_least_count_errors', 3, 'JEE Mains Prep', 'approved'),
('$P = a^3 b^2/(c\sqrt{d})$. If $\%$ errors in $a, b, c, d$ are $1\%, 2\%, 3\%, 4\%$, the $\%$ error in $P$ is', '$8\%$', '$10\%$', '$14\%$', '$12\%$', 'option4', '$\%$ error $= 3(1) + 2(2) + 1(3) + (1/2)(4) = 3 + 4 + 3 + 2 = 12\%$.', 'p_least_count_errors', 3, 'JEE Mains Prep', 'approved'),
('Five measurements: $5.12, 5.14, 5.16, 5.10, 5.18\;\text{cm}$. The mean absolute error is', '$0.02\;\text{cm}$', '$0.04\;\text{cm}$', '$0.024\;\text{cm}$', '$0.03\;\text{cm}$', 'option3', 'Mean $= 5.14$. Deviations: $0.02, 0.00, 0.02, 0.04, 0.04$. Mean abs error $= 0.12/5 = 0.024\;\text{cm}$.', 'p_least_count_errors', 3, 'JEE Mains Prep', 'approved'),
('The relative error in $Z = A^{1/3}/B^{3/2}$ is', '$\frac{1}{3}\frac{\Delta A}{A} + \frac{3}{2}\frac{\Delta B}{B}$', '$\frac{\Delta A}{3A} - \frac{3\Delta B}{2B}$', '$3\frac{\Delta A}{A} + \frac{3}{2}\frac{\Delta B}{B}$', '$\frac{1}{3}\frac{\Delta A}{A} \times \frac{3}{2}\frac{\Delta B}{B}$', 'option1', 'For $Z = A^{1/3}B^{-3/2}$, relative error $= (1/3)(\Delta A/A) + (3/2)(\Delta B/B)$. Errors always add.', 'p_least_count_errors', 3, 'JEE Mains Prep', 'approved'),

-- ============================================================
-- p_dimensional_analysis (5 easy, 5 medium, 5 hard = 15)
-- ============================================================
('The dimensional formula of velocity is', '$[\text{LT}^{-1}]$', '$[\text{LT}^{-2}]$', '$[\text{MLT}^{-1}]$', '$[\text{L}^2\text{T}^{-1}]$', 'option1', 'Velocity $= \text{distance}/\text{time} = [\text{LT}^{-1}]$.', 'p_dimensional_analysis', 1, 'JEE Mains Prep', 'approved'),
('The dimensional formula of force is', '$[\text{MLT}^{-2}]$', '$[\text{ML}^2\text{T}^{-2}]$', '$[\text{MLT}^{-1}]$', '$[\text{MT}^{-2}]$', 'option1', 'Force $= ma = [\text{M}][\text{LT}^{-2}] = [\text{MLT}^{-2}]$.', 'p_dimensional_analysis', 1, 'JEE Mains Prep', 'approved'),
('Which quantity is dimensionless?', 'Pressure', 'Stress', 'Strain', 'Force', 'option3', 'Strain $= \Delta L/L$ is a ratio of two lengths, hence dimensionless.', 'p_dimensional_analysis', 1, 'JEE Mains Prep', 'approved'),
('The dimensions of energy are', '$[\text{ML}^2\text{T}^{-1}]$', '$[\text{MLT}^{-2}]$', '$[\text{ML}^2\text{T}^{-2}]$', '$[\text{M}^2\text{LT}^{-2}]$', 'option3', 'Energy $= Fd = [\text{MLT}^{-2}][\text{L}] = [\text{ML}^2\text{T}^{-2}]$.', 'p_dimensional_analysis', 1, 'JEE Mains Prep', 'approved'),
('The dimensional formula of pressure is', '$[\text{ML}^2\text{T}^{-2}]$', '$[\text{MLT}^{-2}]$', '$[\text{ML}^{-1}\text{T}^{-2}]$', '$[\text{ML}^{-2}\text{T}^{-2}]$', 'option3', 'Pressure $= F/A = [\text{MLT}^{-2}]/[\text{L}^2] = [\text{ML}^{-1}\text{T}^{-2}]$.', 'p_dimensional_analysis', 1, 'JEE Mains Prep', 'approved'),
('The dimensional formula of viscosity $\eta$ is', '$[\text{ML}^{-1}\text{T}^{-2}]$', '$[\text{MLT}^{-1}]$', '$[\text{ML}^{-1}\text{T}^{-1}]$', '$[\text{ML}^2\text{T}^{-1}]$', 'option3', 'From $F = \eta A(dv/dx)$: $[\eta] = [\text{MLT}^{-2}]/([\text{L}^2][\text{T}^{-1}]) = [\text{ML}^{-1}\text{T}^{-1}]$.', 'p_dimensional_analysis', 2, 'JEE Mains Prep', 'approved'),
('$\epsilon_0 E^2$ has dimensions of', 'Energy per unit volume', 'Force', 'Charge', 'Potential', 'option1', '$[\epsilon_0 E^2] = [\text{M}^{-1}\text{L}^{-3}\text{T}^4\text{A}^2][\text{MLT}^{-3}\text{A}^{-1}]^2 = [\text{ML}^{-1}\text{T}^{-2}]$, which is energy/volume.', 'p_dimensional_analysis', 2, 'JEE Mains Prep', 'approved'),
('$\sqrt{\mu_0/\epsilon_0}$ has dimensions of', 'Resistance', 'Capacitance', 'Inductance', 'Current', 'option1', '$[\sqrt{\mu_0/\epsilon_0}] = [\text{ML}^2\text{T}^{-3}\text{A}^{-2}]$, which is resistance (ohm).', 'p_dimensional_analysis', 2, 'JEE Mains Prep', 'approved'),
('Which equation is dimensionally incorrect?', '$s = vt - \frac{1}{2}at^2$', '$s = ut + \frac{1}{2}at^2$', '$v^2 = u^2 + 2as$', '$v = u + at^2$', 'option4', 'In $v = u + at^2$: $[at^2] = [\text{LT}^{-2}][\text{T}^2] = [\text{L}] \neq [\text{LT}^{-1}]$. Dimensionally wrong.', 'p_dimensional_analysis', 2, 'JEE Mains Prep', 'approved'),
('The dimensional formula of magnetic flux is', '$[\text{ML}^2\text{T}^{-3}\text{A}^{-1}]$', '$[\text{ML}^2\text{T}^{-1}\text{A}^{-1}]$', '$[\text{MLT}^{-2}\text{A}^{-1}]$', '$[\text{ML}^2\text{T}^{-2}\text{A}^{-1}]$', 'option4', '$[\Phi] = [B][A] = [\text{MT}^{-2}\text{A}^{-1}][\text{L}^2] = [\text{ML}^2\text{T}^{-2}\text{A}^{-1}]$.', 'p_dimensional_analysis', 2, 'JEE Mains Prep', 'approved'),
('Time period of a drop depends on density $\rho$, radius $r$, surface tension $S$. By dimensional analysis, $T \propto$', '$\sqrt{\rho r/S}$', '$\sqrt{S/(\rho r^3)}$', '$\sqrt{\rho r^3/S}$', '$\sqrt{Sr/\rho}$', 'option3', '$T = k\rho^a r^b S^c$. From M: $a+c=0$. From T: $c=-1/2$, so $a=1/2$. From L: $b=3/2$. $T \propto \sqrt{\rho r^3/S}$.', 'p_dimensional_analysis', 3, 'JEE Mains Prep', 'approved'),
('$e^2/(2\epsilon_0 m_e c^2)$ has dimensions of', 'Dimensionless', 'Energy', 'Time', 'Length', 'option4', '$[e^2/\epsilon_0] = [\text{ML}^3\text{T}^{-2}]$. $[m_e c^2] = [\text{ML}^2\text{T}^{-2}]$. Ratio $= [\text{L}]$. This is the classical electron radius.', 'p_dimensional_analysis', 3, 'JEE Mains Prep', 'approved'),
('If force $F$, length $L$, and time $T$ are fundamental, the dimension of mass is', '$[FL^{-1}T^2]$', '$[FLT^{-2}]$', '$[FL^{-1}T^{-2}]$', '$[FT^2L]$', 'option1', '$F = ma \Rightarrow m = F/a = F/(L/T^2) = FT^2/L = [FL^{-1}T^2]$.', 'p_dimensional_analysis', 3, 'JEE Mains Prep', 'approved'),
('$\frac{1}{2}\epsilon_0 E^2$ has the same dimensions as', '$\epsilon_0 \mu_0$', '$\mu_0 H$', '$B^2/(2\mu_0)$', '$E/B$', 'option3', 'Both $\frac{1}{2}\epsilon_0 E^2$ and $B^2/(2\mu_0)$ are energy density: $[\text{ML}^{-1}\text{T}^{-2}]$.', 'p_dimensional_analysis', 3, 'JEE Mains Prep', 'approved'),
('A gas bubble rises with velocity $v$ depending on $g$, radius $r$, and density $\rho$. If $v \propto g^a r^b \rho^c$, then $a + b + c$ is', '$1$', '$2$', '$0$', '$3$', 'option1', '$[\text{LT}^{-1}] = [\text{LT}^{-2}]^a[\text{L}]^b[\text{ML}^{-3}]^c$. From M: $c=0$. From T: $a=1/2$. From L: $b=1/2$. $a+b+c=1$.', 'p_dimensional_analysis', 3, 'JEE Mains Prep', 'approved'),

-- ============================================================
-- p_frame_reference_1d (5 easy, 5 medium, 5 hard = 15)
-- ============================================================
('A body travels $100\;\text{m}$ in $10\;\text{s}$. Its average speed is', '$10\;\text{m/s}$', '$100\;\text{m/s}$', '$1\;\text{m/s}$', '$0.1\;\text{m/s}$', 'option1', 'Average speed $= 100/10 = 10\;\text{m/s}$.', 'p_frame_reference_1d', 1, 'JEE Mains Prep', 'approved'),
('A particle moves $40\;\text{m}$ east then $30\;\text{m}$ north. The displacement magnitude is', '$70\;\text{m}$', '$50\;\text{m}$', '$35\;\text{m}$', '$10\;\text{m}$', 'option2', 'Displacement $= \sqrt{40^2 + 30^2} = \sqrt{2500} = 50\;\text{m}$.', 'p_frame_reference_1d', 1, 'JEE Mains Prep', 'approved'),
('Speed is a _____ quantity and velocity is a _____ quantity.', 'Scalar, vector', 'Vector, scalar', 'Scalar, scalar', 'Vector, vector', 'option1', 'Speed has only magnitude (scalar). Velocity has magnitude and direction (vector).', 'p_frame_reference_1d', 1, 'JEE Mains Prep', 'approved'),
('A car travels $60\;\text{km}$ in $1\;\text{hr}$ then $40\;\text{km}$ in $1\;\text{hr}$. Average speed is', '$100\;\text{km/hr}$', '$50\;\text{km/hr}$', '$60\;\text{km/hr}$', '$40\;\text{km/hr}$', 'option2', 'Average speed $= (60+40)/(1+1) = 50\;\text{km/hr}$.', 'p_frame_reference_1d', 1, 'JEE Mains Prep', 'approved'),
('If a body returns to its starting point, its displacement is', 'Cannot be determined', 'Equal to distance', 'Negative', 'Zero', 'option4', 'Displacement is the vector from start to end. If they coincide, displacement is zero.', 'p_frame_reference_1d', 1, 'JEE Mains Prep', 'approved'),
('A car covers the first half of distance at $40\;\text{km/hr}$ and second half at $60\;\text{km/hr}$. Average speed is', '$48\;\text{km/hr}$', '$50\;\text{km/hr}$', '$52\;\text{km/hr}$', '$45\;\text{km/hr}$', 'option1', 'For equal distances $d$: time $= d/40 + d/60 = 5d/120$. Avg speed $= 2d/(5d/120) = 48\;\text{km/hr}$.', 'p_frame_reference_1d', 2, 'JEE Mains Prep', 'approved'),
('Position $x = 3t^2 - 6t + 2$ (m). Velocity at $t = 2\;\text{s}$ is', '$0\;\text{m/s}$', '$2\;\text{m/s}$', '$12\;\text{m/s}$', '$6\;\text{m/s}$', 'option4', '$v = dx/dt = 6t - 6$. At $t=2$: $v = 12 - 6 = 6\;\text{m/s}$.', 'p_frame_reference_1d', 2, 'JEE Mains Prep', 'approved'),
('A car covers first half of time at $30\;\text{km/hr}$ and second half at $50\;\text{km/hr}$. Average speed is', '$35\;\text{km/hr}$', '$37.5\;\text{km/hr}$', '$42\;\text{km/hr}$', '$40\;\text{km/hr}$', 'option4', 'For equal times $t$: distance $= 30t + 50t = 80t$. Avg speed $= 80t/2t = 40\;\text{km/hr}$.', 'p_frame_reference_1d', 2, 'JEE Mains Prep', 'approved'),
('The slope of a position-time graph gives', 'Displacement', 'Acceleration', 'Velocity', 'Speed', 'option3', 'Slope of $x$-$t$ graph $= dx/dt =$ instantaneous velocity.', 'p_frame_reference_1d', 2, 'JEE Mains Prep', 'approved'),
('A body starts from rest with uniform acceleration. Ratio of distances in 1st, 2nd, 3rd seconds is', '$1:1:1$', '$1:2:3$', '$1:4:9$', '$1:3:5$', 'option4', 'Distance in $n$th second $= u + a(2n-1)/2$. With $u=0$: ratio $= 1:3:5$.', 'p_frame_reference_1d', 2, 'JEE Mains Prep', 'approved'),
('Velocity $v = 4 - 2t\;\text{m/s}$. Distance from $t=0$ to $t=3\;\text{s}$ is', '$4\;\text{m}$', '$3\;\text{m}$', '$5\;\text{m}$', '$6\;\text{m}$', 'option3', '$v=0$ at $t=2$. Displacement $0 \to 2$: $\int_0^2(4-2t)dt = 4$. Displacement $2 \to 3$: $\int_2^3(4-2t)dt = -1$. Distance $= 4+1 = 5\;\text{m}$.', 'p_frame_reference_1d', 3, 'JEE Mains Prep', 'approved'),
('Two trains of length $100\;\text{m}$ each move in opposite directions at $30$ and $20\;\text{m/s}$. Time to cross is', '$4\;\text{s}$', '$2\;\text{s}$', '$5\;\text{s}$', '$10\;\text{s}$', 'option1', 'Relative speed $= 50\;\text{m/s}$. Total length $= 200\;\text{m}$. Time $= 200/50 = 4\;\text{s}$.', 'p_frame_reference_1d', 3, 'JEE Mains Prep', 'approved'),
('Acceleration $a = (6 - 2t)\;\text{m/s}^2$, starting from rest. Maximum velocity is', '$3\;\text{m/s}$', '$6\;\text{m/s}$', '$12\;\text{m/s}$', '$9\;\text{m/s}$', 'option4', '$a=0$ at $t=3$. $v = \int_0^3(6-2t)dt = [6t-t^2]_0^3 = 18-9 = 9\;\text{m/s}$.', 'p_frame_reference_1d', 3, 'JEE Mains Prep', 'approved'),
('A body thrown vertically up at $u$. Average speed for the entire journey is', '$u$', '$u/2$', '$u/3$', '$2u/3$', 'option2', 'Total distance $= u^2/g$. Total time $= 2u/g$. Avg speed $= (u^2/g)/(2u/g) = u/2$.', 'p_frame_reference_1d', 3, 'JEE Mains Prep', 'approved'),
('A boat crosses a river of width $d$ (river speed $v_r$, boat speed $v_b > v_r$). Minimum crossing time is', '$d/v_b$', '$d/\sqrt{v_b^2 - v_r^2}$', '$d/v_r$', '$d/(v_b + v_r)$', 'option1', 'For minimum time, head straight across. Time $= d/v_b$ (boat drifts but crosses fastest).', 'p_frame_reference_1d', 3, 'JEE Mains Prep', 'approved'),

-- ============================================================
-- p_uniformly_accelerated (5 easy, 5 medium, 5 hard = 15)
-- ============================================================
('A body starts from rest, accelerates at $2\;\text{m/s}^2$ for $5\;\text{s}$. Final velocity is', '$7\;\text{m/s}$', '$5\;\text{m/s}$', '$10\;\text{m/s}$', '$2.5\;\text{m/s}$', 'option3', '$v = u + at = 0 + 2(5) = 10\;\text{m/s}$.', 'p_uniformly_accelerated', 1, 'JEE Mains Prep', 'approved'),
('A car at $20\;\text{m/s}$ brakes to rest in $4\;\text{s}$. Deceleration is', '$4\;\text{m/s}^2$', '$5\;\text{m/s}^2$', '$10\;\text{m/s}^2$', '$80\;\text{m/s}^2$', 'option2', '$|a| = |0-20|/4 = 5\;\text{m/s}^2$.', 'p_uniformly_accelerated', 1, 'JEE Mains Prep', 'approved'),
('From rest with uniform acceleration, $20\;\text{m}$ in $2\;\text{s}$. Acceleration is', '$10\;\text{m/s}^2$', '$5\;\text{m/s}^2$', '$20\;\text{m/s}^2$', '$40\;\text{m/s}^2$', 'option1', '$20 = 0 + \frac{1}{2}a(4) \Rightarrow a = 10\;\text{m/s}^2$.', 'p_uniformly_accelerated', 1, 'JEE Mains Prep', 'approved'),
('A ball dropped from rest falls in $3\;\text{s}$ ($g = 10\;\text{m/s}^2$). Distance is', '$30\;\text{m}$', '$45\;\text{m}$', '$90\;\text{m}$', '$15\;\text{m}$', 'option2', '$s = \frac{1}{2}(10)(9) = 45\;\text{m}$.', 'p_uniformly_accelerated', 1, 'JEE Mains Prep', 'approved'),
('$u = 10\;\text{m/s}$, $a = 2\;\text{m/s}^2$. Distance in $5\;\text{s}$ is', '$75\;\text{m}$', '$50\;\text{m}$', '$60\;\text{m}$', '$100\;\text{m}$', 'option1', '$s = 10(5) + \frac{1}{2}(2)(25) = 50 + 25 = 75\;\text{m}$.', 'p_uniformly_accelerated', 1, 'JEE Mains Prep', 'approved'),
('Ball thrown up at $20\;\text{m/s}$ ($g = 10\;\text{m/s}^2$). Max height is', '$40\;\text{m}$', '$20\;\text{m}$', '$10\;\text{m}$', '$30\;\text{m}$', 'option2', '$h = u^2/(2g) = 400/20 = 20\;\text{m}$.', 'p_uniformly_accelerated', 2, 'JEE Mains Prep', 'approved'),
('From rest, $a = 4\;\text{m/s}^2$. Distance in the 3rd second is', '$8\;\text{m}$', '$12\;\text{m}$', '$18\;\text{m}$', '$10\;\text{m}$', 'option4', '$s_n = u + a(2n-1)/2 = 0 + 4(5)/2 = 10\;\text{m}$.', 'p_uniformly_accelerated', 2, 'JEE Mains Prep', 'approved'),
('Area under a velocity-time graph gives', 'Displacement', 'Acceleration', 'Speed', 'Force', 'option1', 'Area $= \int v\;dt =$ displacement.', 'p_uniformly_accelerated', 2, 'JEE Mains Prep', 'approved'),
('Bodies dropped from heights $h$ and $4h$. Ratio of times to reach ground is', '$1:\sqrt{2}$', '$1:4$', '$2:1$', '$1:2$', 'option4', '$t = \sqrt{2h/g}$. Ratio $= \sqrt{h}:\sqrt{4h} = 1:2$.', 'p_uniformly_accelerated', 2, 'JEE Mains Prep', 'approved'),
('A body moving at $v$ is brought to rest over distance $d$. If speed is $2v$, stopping distance is', '$4d$', '$2d$', '$d$', '$8d$', 'option1', '$v^2 = 2ad \Rightarrow d \propto v^2$. If speed doubles, distance $= 4d$.', 'p_uniformly_accelerated', 2, 'JEE Mains Prep', 'approved'),
('A ball dropped from $45\;\text{m}$ ($g = 10\;\text{m/s}^2$). Distance in the last second of fall is', '$30\;\text{m}$', '$20\;\text{m}$', '$15\;\text{m}$', '$25\;\text{m}$', 'option4', 'Total time $= \sqrt{2(45)/10} = 3\;\text{s}$. Distance in first $2\;\text{s} = \frac{1}{2}(10)(4) = 20\;\text{m}$. Last second $= 45 - 20 = 25\;\text{m}$.', 'p_uniformly_accelerated', 3, 'JEE Mains Prep', 'approved'),
('A car starts from rest, accelerates at $2\;\text{m/s}^2$ for $10\;\text{s}$, then decelerates at $4\;\text{m/s}^2$ to stop. Total distance is', '$200\;\text{m}$', '$100\;\text{m}$', '$125\;\text{m}$', '$150\;\text{m}$', 'option4', 'Phase 1: $v = 2(10) = 20\;\text{m/s}$, $s_1 = \frac{1}{2}(2)(100) = 100\;\text{m}$. Phase 2: $s_2 = 20^2/(2 \times 4) = 50\;\text{m}$. Total $= 150\;\text{m}$.', 'p_uniformly_accelerated', 3, 'JEE Mains Prep', 'approved'),
('Two balls are thrown simultaneously: A upward at $20\;\text{m/s}$ and B downward at $20\;\text{m/s}$ from a $200\;\text{m}$ tower. The difference in time to reach ground is ($g = 10\;\text{m/s}^2$)', '$4\;\text{s}$', '$2\;\text{s}$', '$6\;\text{s}$', '$8\;\text{s}$', 'option1', 'Ball B: $200 = 20t + 5t^2 \Rightarrow t^2 + 4t - 40 = 0 \Rightarrow t = (-4+\sqrt{176})/2 = (-4+4\sqrt{11})/2$. Ball A: $200 = -20t + 5t^2 \Rightarrow t^2 - 4t - 40 = 0 \Rightarrow t = (4+\sqrt{176})/2 = (4+4\sqrt{11})/2$. Difference $= (4+4\sqrt{11})/2 - (-4+4\sqrt{11})/2 = 8/2 = 4\;\text{s}$.', 'p_uniformly_accelerated', 3, 'JEE Mains Prep', 'approved'),
('A particle covers half the distance with speed $v_1$ and the remaining half with speed $v_2$. If $v_1 = 3v_2$, the average speed in terms of $v_1$ is', '$v_1/2$', '$3v_1/4$', '$2v_1/3$', '$v_1/3$', 'option1', 'Avg speed for equal distances $= 2v_1 v_2/(v_1+v_2)$. With $v_2 = v_1/3$: $= 2v_1(v_1/3)/(v_1 + v_1/3) = (2v_1^2/3)/(4v_1/3) = v_1/2$.', 'p_uniformly_accelerated', 3, 'JEE Mains Prep', 'approved'),
('A body is dropped from height $h$. It covers $\frac{h}{2}$ in the last $1\;\text{s}$. The total time of fall is ($g = 10\;\text{m/s}^2$)', '$\sqrt{2}\;\text{s}$', '$2\;\text{s}$', '$(2+\sqrt{2})\;\text{s}$', '$(2-\sqrt{2})\;\text{s}$', 'option3', 'Total time $T$: $h = \frac{1}{2}gT^2$. In $(T-1)$ seconds: $h/2 = \frac{1}{2}g(T-1)^2$. Dividing: $2 = T^2/(T-1)^2 \Rightarrow \sqrt{2}(T-1) = T \Rightarrow T(\sqrt{2}-1) = \sqrt{2} \Rightarrow T = \sqrt{2}/(\sqrt{2}-1) = \sqrt{2}(\sqrt{2}+1) = 2+\sqrt{2}\;\text{s}$.', 'p_uniformly_accelerated', 3, 'JEE Mains Prep', 'approved'),

-- ============================================================
-- p_motion_plane_projectile (5 easy, 5 medium, 5 hard = 15)
-- ============================================================
('A projectile is launched at $45°$ with speed $20\;\text{m/s}$ ($g = 10\;\text{m/s}^2$). The range is', '$80\;\text{m}$', '$20\;\text{m}$', '$40\;\text{m}$', '$10\;\text{m}$', 'option3', '$R = u^2\sin 2\theta/g = 400 \times 1/10 = 40\;\text{m}$.', 'p_motion_plane_projectile', 1, 'JEE Mains Prep', 'approved'),
('The time of flight of a projectile launched at angle $\theta$ with speed $u$ is', '$u^2\sin\theta/g$', '$u\sin\theta/g$', '$2u\cos\theta/g$', '$2u\sin\theta/g$', 'option4', '$T = 2u\sin\theta/g$ (time for vertical component to go up and come back).', 'p_motion_plane_projectile', 1, 'JEE Mains Prep', 'approved'),
('In uniform circular motion, the acceleration is directed', 'Towards the centre', 'Along the tangent', 'Away from the centre', 'At $45°$ to the radius', 'option1', 'In UCM, centripetal acceleration always points towards the centre of the circle.', 'p_motion_plane_projectile', 1, 'JEE Mains Prep', 'approved'),
('The maximum height of a projectile launched at $30°$ with $u = 20\;\text{m/s}$ ($g = 10\;\text{m/s}^2$) is', '$15\;\text{m}$', '$10\;\text{m}$', '$20\;\text{m}$', '$5\;\text{m}$', 'option4', '$H = u^2\sin^2\theta/(2g) = 400 \times (1/4)/20 = 5\;\text{m}$.', 'p_motion_plane_projectile', 1, 'JEE Mains Prep', 'approved'),
('A body moves in a circle of radius $2\;\text{m}$ with speed $4\;\text{m/s}$. Centripetal acceleration is', '$8\;\text{m/s}^2$', '$2\;\text{m/s}^2$', '$16\;\text{m/s}^2$', '$4\;\text{m/s}^2$', 'option1', '$a_c = v^2/r = 16/2 = 8\;\text{m/s}^2$.', 'p_motion_plane_projectile', 1, 'JEE Mains Prep', 'approved'),
('For maximum range, the angle of projection should be', '$30°$', '$45°$', '$60°$', '$90°$', 'option2', '$R = u^2\sin 2\theta/g$. Maximum when $\sin 2\theta = 1$, i.e., $\theta = 45°$.', 'p_motion_plane_projectile', 2, 'JEE Mains Prep', 'approved'),
('Two projectiles have the same range when launched at angles $\theta$ and', '$90° - \theta$', '$180° - \theta$', '$2\theta$', '$\theta/2$', 'option1', '$R \propto \sin 2\theta$. $\sin 2\theta = \sin(180° - 2\theta) = \sin 2(90° - \theta)$. So complementary angles give equal range.', 'p_motion_plane_projectile', 2, 'JEE Mains Prep', 'approved'),
('A ball is thrown horizontally at $10\;\text{m/s}$ from a $20\;\text{m}$ cliff ($g = 10\;\text{m/s}^2$). It hits the ground at', '$\sqrt{2}\;\text{s}$', '$1\;\text{s}$', '$4\;\text{s}$', '$2\;\text{s}$', 'option4', 'Vertical: $20 = \frac{1}{2}(10)t^2 \Rightarrow t = 2\;\text{s}$. Horizontal motion doesn''t affect fall time.', 'p_motion_plane_projectile', 2, 'JEE Mains Prep', 'approved'),
('In projectile motion, the horizontal component of velocity', 'Increases', 'Remains constant', 'Decreases', 'Becomes zero at max height', 'option2', 'No horizontal force acts (ignoring air resistance), so horizontal velocity is constant throughout.', 'p_motion_plane_projectile', 2, 'JEE Mains Prep', 'approved'),
('A particle in UCM with period $T$ and radius $r$. Its speed is', '$\pi r/T$', '$2\pi r/T$', '$2\pi r^2/T$', '$r/T$', 'option2', 'Speed $= \text{circumference}/\text{period} = 2\pi r/T$.', 'p_motion_plane_projectile', 2, 'JEE Mains Prep', 'approved'),
('A projectile has range $R$ on level ground. The maximum height is $R/4$ when the angle of projection is', '$90°$', '$30°$', '$60°$', '$45°$', 'option4', '$R = u^2\sin 2\theta/g$, $H = u^2\sin^2\theta/(2g)$. $H/R = \sin^2\theta/(2\sin 2\theta) = \tan\theta/4$. For $H = R/4$: $\tan\theta = 1$, so $\theta = 45°$.', 'p_motion_plane_projectile', 3, 'JEE Mains Prep', 'approved'),
('A ball thrown at $60°$ with $u = 20\;\text{m/s}$. Speed at maximum height is ($g = 10\;\text{m/s}^2$)', '$10\;\text{m/s}$', '$0\;\text{m/s}$', '$20\;\text{m/s}$', '$5\;\text{m/s}$', 'option1', 'At max height, vertical velocity $= 0$. Speed $= u\cos 60° = 20 \times 0.5 = 10\;\text{m/s}$.', 'p_motion_plane_projectile', 3, 'JEE Mains Prep', 'approved'),
('A projectile is launched at $30°$ with speed $u$. The velocity makes $45°$ with horizontal after time', '$u\sqrt{3}/(2g)$', '$u/(2g)$', '$u(\sqrt{3}-1)/(2g)$', '$u/(g\sqrt{3})$', 'option3', 'At time $t$: $\tan 45° = 1 = (u\sin 30° - gt)/(u\cos 30°)$. $u\cos 30° = u\sin 30° - gt$. $u\sqrt{3}/2 = u/2 - gt$. $gt = u/2 - u\sqrt{3}/2 = u(1-\sqrt{3})/2$. Since angle is below horizontal: $gt = u(\sqrt{3}-1)/2$. $t = u(\sqrt{3}-1)/(2g)$.', 'p_motion_plane_projectile', 3, 'JEE Mains Prep', 'approved'),
('A particle moves in a circle of radius $R$ with speed $v = bt^2$ where $b$ is constant. The net acceleration at time $t$ is', '$b^2t^4/R$', '$2bt$', '$\sqrt{4b^2t^2 + b^4t^8/R^2}$', '$bt^2/R$', 'option3', 'Tangential: $a_t = dv/dt = 2bt$. Centripetal: $a_c = v^2/R = b^2t^4/R$. Net $= \sqrt{a_t^2 + a_c^2} = \sqrt{4b^2t^2 + b^4t^8/R^2}$.', 'p_motion_plane_projectile', 3, 'JEE Mains Prep', 'approved'),
('A ball is thrown horizontally from a cliff. After $2\;\text{s}$, the velocity makes $45°$ with horizontal ($g = 10\;\text{m/s}^2$). The initial horizontal speed is', '$20\;\text{m/s}$', '$10\;\text{m/s}$', '$40\;\text{m/s}$', '$5\;\text{m/s}$', 'option1', 'After $2\;\text{s}$: $v_y = gt = 20\;\text{m/s}$. For $45°$: $\tan 45° = v_y/v_x = 1$, so $v_x = v_y = 20\;\text{m/s}$.', 'p_motion_plane_projectile', 3, 'JEE Mains Prep', 'approved'),

-- ============================================================
-- p_newtons_laws_impulse (5 easy, 5 medium, 5 hard = 15)
-- ============================================================
('Newton''s first law defines', 'Inertia', 'Force', 'Momentum', 'Energy', 'option1', 'Newton''s first law states that a body continues in its state of rest or uniform motion unless acted upon by an external force. This defines inertia.', 'p_newtons_laws_impulse', 1, 'JEE Mains Prep', 'approved'),
('A force of $10\;\text{N}$ acts on a $2\;\text{kg}$ mass. The acceleration is', '$20\;\text{m/s}^2$', '$5\;\text{m/s}^2$', '$0.2\;\text{m/s}^2$', '$12\;\text{m/s}^2$', 'option2', '$a = F/m = 10/2 = 5\;\text{m/s}^2$.', 'p_newtons_laws_impulse', 1, 'JEE Mains Prep', 'approved'),
('The SI unit of momentum is', '$\text{J}\;\text{s}$', '$\text{N}\;\text{m}$', '$\text{kg}\;\text{m/s}^2$', '$\text{kg}\;\text{m/s}$', 'option4', 'Momentum $= mv$, so its unit is $\text{kg}\cdot\text{m/s}$.', 'p_newtons_laws_impulse', 1, 'JEE Mains Prep', 'approved'),
('Impulse equals', 'Change in momentum', 'Force', 'Acceleration', 'Kinetic energy', 'option1', 'Impulse $= F \Delta t = \Delta p$ (change in momentum).', 'p_newtons_laws_impulse', 1, 'JEE Mains Prep', 'approved'),
('Action and reaction forces act on', 'Same point', 'Same body', 'Different bodies', 'Same direction', 'option3', 'Newton''s third law: action and reaction are equal and opposite but act on different bodies.', 'p_newtons_laws_impulse', 1, 'JEE Mains Prep', 'approved'),
('A $0.5\;\text{kg}$ ball moving at $6\;\text{m/s}$ is stopped in $0.1\;\text{s}$. The average force is', '$30\;\text{N}$', '$3\;\text{N}$', '$0.3\;\text{N}$', '$300\;\text{N}$', 'option1', '$F = \Delta p/\Delta t = (0.5 \times 6)/0.1 = 3/0.1 = 30\;\text{N}$.', 'p_newtons_laws_impulse', 2, 'JEE Mains Prep', 'approved'),
('A $1000\;\text{kg}$ car accelerates from $0$ to $20\;\text{m/s}$ in $10\;\text{s}$. The net force is', '$2000\;\text{N}$', '$200\;\text{N}$', '$20000\;\text{N}$', '$1000\;\text{N}$', 'option1', '$F = ma = 1000 \times (20/10) = 2000\;\text{N}$.', 'p_newtons_laws_impulse', 2, 'JEE Mains Prep', 'approved'),
('A $2\;\text{kg}$ body on a smooth surface is pulled by $10\;\text{N}$ at $60°$ above horizontal. Horizontal acceleration is', '$5\;\text{m/s}^2$', '$2.5\;\text{m/s}^2$', '$4.33\;\text{m/s}^2$', '$10\;\text{m/s}^2$', 'option2', 'Horizontal force $= 10\cos 60° = 5\;\text{N}$. $a = 5/2 = 2.5\;\text{m/s}^2$.', 'p_newtons_laws_impulse', 2, 'JEE Mains Prep', 'approved'),
('A $0.2\;\text{kg}$ ball hits a wall at $5\;\text{m/s}$ and rebounds at $5\;\text{m/s}$. The impulse on the ball is', '$0\;\text{N}\cdot\text{s}$', '$1\;\text{N}\cdot\text{s}$', '$2\;\text{N}\cdot\text{s}$', '$0.5\;\text{N}\cdot\text{s}$', 'option3', 'Impulse $= m(v_f - v_i) = 0.2(5 - (-5)) = 0.2 \times 10 = 2\;\text{N}\cdot\text{s}$.', 'p_newtons_laws_impulse', 2, 'JEE Mains Prep', 'approved'),
('The apparent weight of a person in a lift accelerating upward at $a$ is', '$m(g+a)$', '$m(g-a)$', '$mg$', '$ma$', 'option1', 'In an upward-accelerating lift, $N - mg = ma$, so $N = m(g+a)$.', 'p_newtons_laws_impulse', 2, 'JEE Mains Prep', 'approved'),
('A rocket ejects gas at rate $dm/dt$ with exhaust velocity $v_e$. The thrust is', '$v_e/(dm/dt)$', '$v_e^2(dm/dt)$', '$(dm/dt)/v_e$', '$v_e(dm/dt)$', 'option4', 'Thrust $= v_e \times dm/dt$ (rate of change of momentum of ejected gas).', 'p_newtons_laws_impulse', 3, 'JEE Mains Prep', 'approved'),
('Two blocks $m_1 = 3\;\text{kg}$ and $m_2 = 2\;\text{kg}$ are connected by a string on a smooth surface. Force $F = 10\;\text{N}$ pulls $m_1$. Tension in string is', '$4\;\text{N}$', '$6\;\text{N}$', '$10\;\text{N}$', '$5\;\text{N}$', 'option1', '$a = F/(m_1+m_2) = 10/5 = 2\;\text{m/s}^2$. Tension $= m_2 \times a = 2 \times 2 = 4\;\text{N}$.', 'p_newtons_laws_impulse', 3, 'JEE Mains Prep', 'approved'),
('A $60\;\text{kg}$ person in a lift feels weight $720\;\text{N}$. The lift acceleration is ($g = 10\;\text{m/s}^2$)', '$2\;\text{m/s}^2$ downward', '$2\;\text{m/s}^2$ upward', '$12\;\text{m/s}^2$ upward', '$0\;\text{m/s}^2$', 'option2', '$N = m(g+a) \Rightarrow 720 = 60(10+a) \Rightarrow a = 2\;\text{m/s}^2$ upward.', 'p_newtons_laws_impulse', 3, 'JEE Mains Prep', 'approved'),
('A force $F = (3t^2 + 2)\;\text{N}$ acts on a $1\;\text{kg}$ body at rest. Velocity at $t = 2\;\text{s}$ is', '$12\;\text{m/s}$', '$10\;\text{m/s}$', '$14\;\text{m/s}$', '$8\;\text{m/s}$', 'option1', '$v = \int_0^2 F\;dt/m = \int_0^2(3t^2+2)dt = [t^3+2t]_0^2 = 8+4 = 12\;\text{m/s}$.', 'p_newtons_laws_impulse', 3, 'JEE Mains Prep', 'approved'),
('An Atwood machine has masses $5\;\text{kg}$ and $3\;\text{kg}$. The acceleration is ($g = 10\;\text{m/s}^2$)', '$2.5\;\text{m/s}^2$', '$5\;\text{m/s}^2$', '$10\;\text{m/s}^2$', '$1.25\;\text{m/s}^2$', 'option1', '$a = (m_1-m_2)g/(m_1+m_2) = (5-3)(10)/(5+3) = 20/8 = 2.5\;\text{m/s}^2$.', 'p_newtons_laws_impulse', 3, 'JEE Mains Prep', 'approved'),

-- ============================================================
-- p_conservation_momentum (5 easy, 5 medium, 5 hard = 15)
-- ============================================================
('Conservation of linear momentum requires', 'No external force on the system', 'No friction', 'Constant velocity', 'Elastic collision', 'option1', 'Linear momentum is conserved when the net external force on the system is zero.', 'p_conservation_momentum', 1, 'JEE Mains Prep', 'approved'),
('A $2\;\text{kg}$ body at $3\;\text{m/s}$ collides with a $1\;\text{kg}$ body at rest and they stick together. Their common velocity is', '$2\;\text{m/s}$', '$3\;\text{m/s}$', '$1\;\text{m/s}$', '$6\;\text{m/s}$', 'option1', '$m_1 v_1 = (m_1+m_2)v$. $2(3) = 3v \Rightarrow v = 2\;\text{m/s}$.', 'p_conservation_momentum', 1, 'JEE Mains Prep', 'approved'),
('A gun of mass $4\;\text{kg}$ fires a $50\;\text{g}$ bullet at $400\;\text{m/s}$. Recoil velocity of gun is', '$2\;\text{m/s}$', '$10\;\text{m/s}$', '$50\;\text{m/s}$', '$5\;\text{m/s}$', 'option4', '$0 = 0.05(400) + 4v \Rightarrow v = -20/4 = -5\;\text{m/s}$. Recoil speed $= 5\;\text{m/s}$.', 'p_conservation_momentum', 1, 'JEE Mains Prep', 'approved'),
('For three concurrent forces to be in equilibrium, they must', 'Be parallel', 'Be equal', 'Form a closed triangle', 'Act along the same line', 'option3', 'Three concurrent forces in equilibrium can be represented by the sides of a triangle (Lami''s theorem / triangle law).', 'p_conservation_momentum', 1, 'JEE Mains Prep', 'approved'),
('The total momentum of an isolated system is', 'Constant', 'Zero', 'Increasing', 'Decreasing', 'option1', 'By conservation of momentum, total momentum of an isolated system remains constant.', 'p_conservation_momentum', 1, 'JEE Mains Prep', 'approved'),
('A $10\;\text{kg}$ body explodes into two pieces of $4\;\text{kg}$ and $6\;\text{kg}$. If the $4\;\text{kg}$ piece moves at $6\;\text{m/s}$, the speed of the $6\;\text{kg}$ piece is', '$6\;\text{m/s}$', '$4\;\text{m/s}$', '$10\;\text{m/s}$', '$2.4\;\text{m/s}$', 'option2', 'Initially at rest: $0 = 4(6) + 6v \Rightarrow v = -24/6 = -4\;\text{m/s}$. Speed $= 4\;\text{m/s}$.', 'p_conservation_momentum', 2, 'JEE Mains Prep', 'approved'),
('A $1\;\text{kg}$ ball at $10\;\text{m/s}$ collides head-on with a $2\;\text{kg}$ ball at $4\;\text{m/s}$ (same direction). If they stick, the common velocity is', '$4.67\;\text{m/s}$', '$7\;\text{m/s}$', '$6\;\text{m/s}$', '$14\;\text{m/s}$', 'option3', '$1(10) + 2(4) = 3v \Rightarrow v = 18/3 = 6\;\text{m/s}$.', 'p_conservation_momentum', 2, 'JEE Mains Prep', 'approved'),
('Two equal masses moving at right angles with speed $v$ collide and stick. Their speed after collision is', '$\sqrt{2}v$', '$v$', '$v/2$', '$v/\sqrt{2}$', 'option4', 'Momentum: $p_x = mv$, $p_y = mv$. Total $p = m\sqrt{v^2+v^2} = mv\sqrt{2}$. Combined mass $= 2m$. Speed $= mv\sqrt{2}/(2m) = v/\sqrt{2}$.', 'p_conservation_momentum', 2, 'JEE Mains Prep', 'approved'),
('A bullet of mass $m$ embeds in a block of mass $M$ on a frictionless surface. The fraction of KE lost is', '$m/(m+M)$', '$M/(m+M)$', '$1/2$', '$m/M$', 'option2', 'KE lost $= \frac{1}{2}mv^2 - \frac{1}{2}(m+M)(mv/(m+M))^2 = \frac{1}{2}mv^2(1 - m/(m+M)) = \frac{1}{2}mv^2 \cdot M/(m+M)$. Fraction $= M/(m+M)$.', 'p_conservation_momentum', 2, 'JEE Mains Prep', 'approved'),
('A man of $60\;\text{kg}$ jumps from a $200\;\text{kg}$ boat at $4\;\text{m/s}$ relative to ground. Boat velocity is', '$0.6\;\text{m/s}$', '$2\;\text{m/s}$', '$4\;\text{m/s}$', '$1.2\;\text{m/s}$', 'option4', '$0 = 60(4) + 200v \Rightarrow v = -240/200 = -1.2\;\text{m/s}$. Speed $= 1.2\;\text{m/s}$.', 'p_conservation_momentum', 2, 'JEE Mains Prep', 'approved'),
('A shell at rest explodes into three pieces of equal mass. Two fly off at $60°$ to each other with speed $v$. Speed of the third piece is', '$2v$', '$v\sqrt{3}$', '$v$', '$v/\sqrt{3}$', 'option2', 'Resultant momentum of two pieces: $p = \sqrt{(mv)^2 + (mv)^2 + 2(mv)(mv)\cos 60°} = mv\sqrt{3}$. Third piece: $mv_3 = mv\sqrt{3}$, so $v_3 = v\sqrt{3}$.', 'p_conservation_momentum', 3, 'JEE Mains Prep', 'approved'),
('A ball of mass $m$ moving at $v$ hits an identical stationary ball. After elastic head-on collision, the first ball', 'Moves at $v/2$', 'Stops', 'Rebounds at $v$', 'Moves at $v$', 'option2', 'In elastic head-on collision between equal masses, the first ball stops and the second moves at $v$.', 'p_conservation_momentum', 3, 'JEE Mains Prep', 'approved'),
('A $4\;\text{kg}$ ball at $2\;\text{m/s}$ collides elastically head-on with a $1\;\text{kg}$ ball at rest. Velocity of $1\;\text{kg}$ ball after collision is', '$3.2\;\text{m/s}$', '$2\;\text{m/s}$', '$4\;\text{m/s}$', '$1.6\;\text{m/s}$', 'option1', '$v_2 = 2m_1 u_1/(m_1+m_2) = 2(4)(2)/5 = 16/5 = 3.2\;\text{m/s}$.', 'p_conservation_momentum', 3, 'JEE Mains Prep', 'approved'),
('A body of mass $m$ moving at $v$ collides with a stationary body of mass $2m$. If the collision is perfectly inelastic, the loss in KE is', '$mv^2/2$', '$mv^2/3$', '$mv^2/6$', '$2mv^2/3$', 'option2', 'Common velocity $= mv/(3m) = v/3$. KE lost $= \frac{1}{2}mv^2 - \frac{1}{2}(3m)(v/3)^2 = \frac{1}{2}mv^2 - \frac{1}{6}mv^2 = \frac{1}{3}mv^2$.', 'p_conservation_momentum', 3, 'JEE Mains Prep', 'approved'),
('A ballistic pendulum: a $10\;\text{g}$ bullet at $v$ embeds in a $2\;\text{kg}$ block which rises $0.2\;\text{m}$. The bullet speed $v$ is ($g = 10\;\text{m/s}^2$)', '$100\;\text{m/s}$', '$200\;\text{m/s}$', '$402\;\text{m/s}$', '$40\;\text{m/s}$', 'option3', 'Block+bullet velocity after impact: $V = \sqrt{2gh} = \sqrt{2(10)(0.2)} = 2\;\text{m/s}$. Momentum: $0.01v = (0.01+2)(2) = 4.02$. $v = 402\;\text{m/s}$.', 'p_conservation_momentum', 3, 'JEE Mains Prep', 'approved'),

-- ============================================================
-- p_friction (5 easy, 5 medium, 5 hard = 15)
-- ============================================================
('Static friction is always', 'Equal to $\mu_s N$', 'Less than or equal to $\mu_s N$', 'Greater than kinetic friction', 'Zero on rough surfaces', 'option2', 'Static friction adjusts from 0 up to $\mu_s N$. It equals $\mu_s N$ only at the point of impending motion.', 'p_friction', 1, 'JEE Mains Prep', 'approved'),
('A $10\;\text{kg}$ block on a surface with $\mu_k = 0.3$. Kinetic friction force is ($g = 10\;\text{m/s}^2$)', '$30\;\text{N}$', '$3\;\text{N}$', '$100\;\text{N}$', '$10\;\text{N}$', 'option1', '$f_k = \mu_k mg = 0.3 \times 10 \times 10 = 30\;\text{N}$.', 'p_friction', 1, 'JEE Mains Prep', 'approved'),
('Friction force acts', 'Opposite to the direction of motion (or tendency)', 'Along the normal', 'In the direction of motion', 'Perpendicular to the surface', 'option1', 'Friction opposes relative motion or the tendency of relative motion between surfaces.', 'p_friction', 1, 'JEE Mains Prep', 'approved'),
('Rolling friction is generally _____ than sliding friction.', 'Greater', 'Less', 'Equal to', 'Unrelated to', 'option2', 'Rolling friction is much less than sliding friction, which is why wheels are used for transport.', 'p_friction', 1, 'JEE Mains Prep', 'approved'),
('The coefficient of friction is', 'Dimensionless', 'Measured in Newtons', 'Measured in kg', 'Measured in m/s', 'option1', '$\mu = f/N$, a ratio of two forces, hence dimensionless.', 'p_friction', 1, 'JEE Mains Prep', 'approved'),
('A $5\;\text{kg}$ block is pushed with $30\;\text{N}$ on a surface with $\mu_k = 0.2$ ($g = 10\;\text{m/s}^2$). Acceleration is', '$4\;\text{m/s}^2$', '$6\;\text{m/s}^2$', '$2\;\text{m/s}^2$', '$8\;\text{m/s}^2$', 'option1', '$f_k = 0.2(5)(10) = 10\;\text{N}$. $a = (30-10)/5 = 4\;\text{m/s}^2$.', 'p_friction', 2, 'JEE Mains Prep', 'approved'),
('A block on a rough incline of angle $30°$ with $\mu_s = 0.6$. Will it slide? ($\tan 30° \approx 0.577$)', 'Yes, it slides down', 'No, it remains stationary', 'It slides up', 'Cannot determine', 'option2', 'Block slides if $\tan\theta > \mu_s$. $\tan 30° = 0.577 < 0.6$. So it stays.', 'p_friction', 2, 'JEE Mains Prep', 'approved'),
('The angle of repose for a surface with $\mu_s = 1$ is', '$45°$', '$30°$', '$60°$', '$90°$', 'option1', 'Angle of repose $\alpha = \tan^{-1}(\mu_s) = \tan^{-1}(1) = 45°$.', 'p_friction', 2, 'JEE Mains Prep', 'approved'),
('A $2\;\text{kg}$ block on a rough surface ($\mu = 0.5$) is pulled at $30°$ above horizontal with $20\;\text{N}$. Normal force is ($g = 10\;\text{m/s}^2$)', '$15\;\text{N}$', '$20\;\text{N}$', '$10\;\text{N}$', '$5\;\text{N}$', 'option3', '$N = mg - F\sin 30° = 20 - 20(0.5) = 20 - 10 = 10\;\text{N}$.', 'p_friction', 2, 'JEE Mains Prep', 'approved'),
('Minimum force to move a block of mass $m$ on a rough surface ($\mu$) is applied at angle $\theta = \tan^{-1}\mu$. This force equals', '$mg\sqrt{1+\mu^2}$', '$\mu mg$', '$mg/\mu$', '$\mu mg/\sqrt{1+\mu^2}$', 'option4', 'At optimal angle $\theta = \tan^{-1}\mu$: $F = \mu mg/(\cos\theta + \mu\sin\theta)$. With $\cos\theta = 1/\sqrt{1+\mu^2}$ and $\sin\theta = \mu/\sqrt{1+\mu^2}$: $F = \mu mg/((1+\mu^2)/\sqrt{1+\mu^2}) = \mu mg/\sqrt{1+\mu^2}$.', 'p_friction', 2, 'JEE Mains Prep', 'approved'),
('A block slides down a rough incline ($\theta = 30°$, $\mu_k = 0.2$). Acceleration is ($g = 10\;\text{m/s}^2$)', '$6.73\;\text{m/s}^2$', '$5\;\text{m/s}^2$', '$1.73\;\text{m/s}^2$', '$3.27\;\text{m/s}^2$', 'option4', '$a = g(\sin\theta - \mu_k\cos\theta) = 10(0.5 - 0.2 \times 0.866) = 10(0.5 - 0.173) = 3.27\;\text{m/s}^2$.', 'p_friction', 3, 'JEE Mains Prep', 'approved'),
('Two blocks $A$ ($3\;\text{kg}$) and $B$ ($2\;\text{kg}$) are stacked. $\mu$ between them $= 0.4$, surface is smooth. Max force on $A$ so $B$ doesn''t slide is ($g = 10\;\text{m/s}^2$)', '$20\;\text{N}$', '$8\;\text{N}$', '$12\;\text{N}$', '$40\;\text{N}$', 'option1', 'Max acceleration of $B$ (by friction) $= \mu g = 4\;\text{m/s}^2$. For system: $F = (3+2)(4) = 20\;\text{N}$.', 'p_friction', 3, 'JEE Mains Prep', 'approved'),
('A block of mass $m$ on a rough surface ($\mu$) is given initial velocity $v_0$. Distance before stopping is', '$v_0^2/(\mu g)$', '$v_0/(2\mu g)$', '$v_0^2/(2\mu g)$', '$\mu g v_0^2/2$', 'option3', 'Deceleration $= \mu g$. $v^2 = v_0^2 - 2\mu g \cdot s$. At stop: $s = v_0^2/(2\mu g)$.', 'p_friction', 3, 'JEE Mains Prep', 'approved'),
('A block is placed on a rough incline and connected to a hanging mass via a pulley. The system is in equilibrium. If $m_1$ (on incline, $\theta = 30°$, $\mu_s = 0.3$) $= 5\;\text{kg}$, the range of $m_2$ for equilibrium is', '$1.2\;\text{kg}$ to $3.8\;\text{kg}$', '$2.5\;\text{kg}$ to $3.5\;\text{kg}$', '$1.0\;\text{kg}$ to $4.0\;\text{kg}$', '$0.5\;\text{kg}$ to $5.0\;\text{kg}$', 'option1', '$m_2 g = m_1 g\sin 30° \pm \mu_s m_1 g\cos 30°$. $m_2 = 5(0.5 \pm 0.3 \times 0.866) = 5(0.5 \pm 0.26) = 5(0.24)$ to $5(0.76) = 1.2$ to $3.8\;\text{kg}$.', 'p_friction', 3, 'JEE Mains Prep', 'approved'),
('A car on a flat road with $\mu_s = 0.5$ ($g = 10\;\text{m/s}^2$). Maximum speed for a turn of radius $50\;\text{m}$ is', '$\approx 15.8\;\text{m/s}$', '$25\;\text{m/s}$', '$10\;\text{m/s}$', '$50\;\text{m/s}$', 'option1', '$v_{max} = \sqrt{\mu_s g r} = \sqrt{0.5 \times 10 \times 50} = \sqrt{250} \approx 15.8\;\text{m/s}$.', 'p_friction', 3, 'JEE Mains Prep', 'approved'),

-- ============================================================
-- p_circular_motion_dynamics (5 easy, 5 medium, 5 hard = 15)
-- ============================================================
('Centripetal force is directed', 'Away from the centre', 'Towards the centre', 'Along the tangent', 'At $45°$ to the radius', 'option2', 'Centripetal force always points towards the centre of the circular path.', 'p_circular_motion_dynamics', 1, 'JEE Mains Prep', 'approved'),
('Centripetal acceleration for speed $v$ and radius $r$ is', '$v/r$', '$vr$', '$v^2/r$', '$v^2 r$', 'option3', '$a_c = v^2/r$ directed towards the centre.', 'p_circular_motion_dynamics', 1, 'JEE Mains Prep', 'approved'),
('A $2\;\text{kg}$ mass moves in a circle of radius $1\;\text{m}$ at $3\;\text{m/s}$. Centripetal force is', '$6\;\text{N}$', '$18\;\text{N}$', '$9\;\text{N}$', '$3\;\text{N}$', 'option2', '$F = mv^2/r = 2(9)/1 = 18\;\text{N}$.', 'p_circular_motion_dynamics', 1, 'JEE Mains Prep', 'approved'),
('In uniform circular motion, the speed is', 'Increasing', 'Constant', 'Decreasing', 'Zero', 'option2', 'In UCM, speed (magnitude of velocity) is constant; only direction changes.', 'p_circular_motion_dynamics', 1, 'JEE Mains Prep', 'approved'),
('The centripetal force for a car on a flat circular road is provided by', 'Friction', 'Gravity', 'Normal force', 'Engine force', 'option1', 'On a flat road, friction between tyres and road provides the centripetal force for turning.', 'p_circular_motion_dynamics', 1, 'JEE Mains Prep', 'approved'),
('A car moves on a banked road of angle $\theta$ with no friction. The speed for safe turning (radius $r$) is', '$\sqrt{rg\cos\theta}$', '$\sqrt{rg\sin\theta}$', '$\sqrt{rg/\tan\theta}$', '$\sqrt{rg\tan\theta}$', 'option4', 'On a frictionless banked road: $\tan\theta = v^2/(rg)$, so $v = \sqrt{rg\tan\theta}$.', 'p_circular_motion_dynamics', 2, 'JEE Mains Prep', 'approved'),
('A stone of $0.5\;\text{kg}$ is whirled in a vertical circle of radius $1\;\text{m}$. Minimum speed at the top is ($g = 10\;\text{m/s}^2$)', '$\sqrt{5}\;\text{m/s}$', '$10\;\text{m/s}$', '$5\;\text{m/s}$', '$\sqrt{10}\;\text{m/s}$', 'option4', 'At top: $mg = mv^2/r \Rightarrow v = \sqrt{gr} = \sqrt{10}\;\text{m/s}$.', 'p_circular_motion_dynamics', 2, 'JEE Mains Prep', 'approved'),
('Angular velocity $\omega$ and linear velocity $v$ are related by', '$v = \omega r$', '$v = \omega/r$', '$v = \omega r^2$', '$v = \omega^2 r$', 'option1', '$v = \omega r$ where $r$ is the radius of the circular path.', 'p_circular_motion_dynamics', 2, 'JEE Mains Prep', 'approved'),
('A conical pendulum of length $l$ makes angle $\theta$ with vertical. Its time period is', '$2\pi\sqrt{l\cos\theta/g}$', '$2\pi\sqrt{l/g}$', '$2\pi\sqrt{l\sin\theta/g}$', '$2\pi\sqrt{l/(g\cos\theta)}$', 'option1', 'Vertical: $T\cos\theta = mg$. Horizontal: $T\sin\theta = m\omega^2 r = m\omega^2 l\sin\theta$. So $\omega^2 = g/(l\cos\theta)$. $T_p = 2\pi/\omega = 2\pi\sqrt{l\cos\theta/g}$.', 'p_circular_motion_dynamics', 2, 'JEE Mains Prep', 'approved'),
('A particle in UCM completes $5$ revolutions in $2\;\text{s}$. Its angular velocity is', '$5\pi\;\text{rad/s}$', '$10\pi\;\text{rad/s}$', '$2.5\pi\;\text{rad/s}$', '$\pi\;\text{rad/s}$', 'option1', 'Frequency $= 5/2 = 2.5\;\text{Hz}$. $\omega = 2\pi f = 5\pi\;\text{rad/s}$.', 'p_circular_motion_dynamics', 2, 'JEE Mains Prep', 'approved'),
('Minimum speed at the bottom of a vertical circle of radius $r$ for complete revolution is', '$\sqrt{5gr}$', '$\sqrt{gr}$', '$\sqrt{3gr}$', '$\sqrt{2gr}$', 'option1', 'At top: $v_{top} = \sqrt{gr}$. Energy conservation: $\frac{1}{2}mv_{bot}^2 = \frac{1}{2}mv_{top}^2 + mg(2r)$. $v_{bot} = \sqrt{v_{top}^2 + 4gr} = \sqrt{5gr}$.', 'p_circular_motion_dynamics', 3, 'JEE Mains Prep', 'approved'),
('A car on a banked road ($\theta = 30°$) with $\mu_s = 0.5$ and $r = 100\;\text{m}$. Maximum safe speed is ($g = 10\;\text{m/s}^2$)', '$\approx 38\;\text{m/s}$', '$24\;\text{m/s}$', '$50\;\text{m/s}$', '$17\;\text{m/s}$', 'option1', '$v_{max} = \sqrt{rg(\tan\theta + \mu_s)/(1 - \mu_s\tan\theta)} = \sqrt{100 \times 10 \times (0.577 + 0.5)/(1 - 0.289)} = \sqrt{1000 \times 1.077/0.711} = \sqrt{1515} \approx 38.9\;\text{m/s}$.', 'p_circular_motion_dynamics', 3, 'JEE Mains Prep', 'approved'),
('A particle moves in a circle of radius $1\;\text{m}$ with speed $v = 2t$. At $t = 1\;\text{s}$, the net acceleration magnitude is', '$2\;\text{m/s}^2$', '$4\;\text{m/s}^2$', '$2\sqrt{5}\;\text{m/s}^2$', '$6\;\text{m/s}^2$', 'option3', 'At $t=1$: $v=2$, $a_t = dv/dt = 2\;\text{m/s}^2$, $a_c = v^2/r = 4\;\text{m/s}^2$. Net $= \sqrt{4+16} = \sqrt{20} = 2\sqrt{5}\;\text{m/s}^2$.', 'p_circular_motion_dynamics', 3, 'JEE Mains Prep', 'approved'),
('A hemispherical bowl of radius $R$ has a particle released from the rim. Speed at the bottom (frictionless) is', '$\sqrt{4gR}$', '$\sqrt{gR}$', '$\sqrt{2gR}$', '$\sqrt{gR/2}$', 'option3', 'Height dropped $= R$. By energy conservation: $v = \sqrt{2gR}$.', 'p_circular_motion_dynamics', 3, 'JEE Mains Prep', 'approved'),
('A cyclist leans at angle $\theta$ while turning on a flat road at speed $v$ on radius $r$. Then $\tan\theta$ equals', '$v^2/(rg)$', '$rg/v^2$', '$v/(rg)$', '$v^2 r/g$', 'option1', 'The cyclist leans so that $\tan\theta = v^2/(rg)$, balancing centripetal force with gravity.', 'p_circular_motion_dynamics', 3, 'JEE Mains Prep', 'approved'),

-- ============================================================
-- p_work_ke_pe_theorem (5 easy, 5 medium, 5 hard = 15)
-- ============================================================
('Work done by a force $F$ over displacement $d$ at angle $\theta$ is', '$Fd\sin\theta$', '$Fd\cos\theta$', '$Fd$', '$F/d$', 'option2', '$W = Fd\cos\theta$ where $\theta$ is the angle between force and displacement.', 'p_work_ke_pe_theorem', 1, 'JEE Mains Prep', 'approved'),
('The kinetic energy of a $2\;\text{kg}$ body moving at $3\;\text{m/s}$ is', '$9\;\text{J}$', '$6\;\text{J}$', '$3\;\text{J}$', '$18\;\text{J}$', 'option1', '$KE = \frac{1}{2}mv^2 = \frac{1}{2}(2)(9) = 9\;\text{J}$.', 'p_work_ke_pe_theorem', 1, 'JEE Mains Prep', 'approved'),
('Work done by gravity on a $5\;\text{kg}$ body falling $10\;\text{m}$ is ($g = 10\;\text{m/s}^2$)', '$-500\;\text{J}$', '$50\;\text{J}$', '$500\;\text{J}$', '$100\;\text{J}$', 'option3', '$W = mgh = 5(10)(10) = 500\;\text{J}$ (force and displacement in same direction).', 'p_work_ke_pe_theorem', 1, 'JEE Mains Prep', 'approved'),
('The SI unit of power is', 'Pascal', 'Joule', 'Newton', 'Watt', 'option4', 'Power $= \text{work}/\text{time}$. SI unit is Watt ($1\;\text{W} = 1\;\text{J/s}$).', 'p_work_ke_pe_theorem', 1, 'JEE Mains Prep', 'approved'),
('Work done by a force perpendicular to displacement is', 'Zero', 'Positive', 'Negative', 'Maximum', 'option1', '$W = Fd\cos 90° = 0$. A perpendicular force does no work.', 'p_work_ke_pe_theorem', 1, 'JEE Mains Prep', 'approved'),
('A $1000\;\text{kg}$ car accelerates from rest to $20\;\text{m/s}$. Work done by the engine (ignoring friction) is', '$200\;\text{kJ}$', '$100\;\text{kJ}$', '$400\;\text{kJ}$', '$20\;\text{kJ}$', 'option1', '$W = \Delta KE = \frac{1}{2}(1000)(400) = 200000\;\text{J} = 200\;\text{kJ}$.', 'p_work_ke_pe_theorem', 2, 'JEE Mains Prep', 'approved'),
('A body of mass $m$ has momentum $p$. Its kinetic energy is', '$p^2 m/2$', '$p/(2m)$', '$2mp^2$', '$p^2/(2m)$', 'option4', '$p = mv \Rightarrow v = p/m$. $KE = \frac{1}{2}mv^2 = p^2/(2m)$.', 'p_work_ke_pe_theorem', 2, 'JEE Mains Prep', 'approved'),
('A pump lifts $100\;\text{kg}$ of water per minute to $10\;\text{m}$ height. Power required is ($g = 10\;\text{m/s}^2$)', '$1000\;\text{W}$', '$\approx 167\;\text{W}$', '$100\;\text{W}$', '$10\;\text{W}$', 'option2', '$P = mgh/t = 100(10)(10)/60 = 10000/60 \approx 167\;\text{W}$.', 'p_work_ke_pe_theorem', 2, 'JEE Mains Prep', 'approved'),
('Work done by a variable force $F = 3x^2$ from $x = 0$ to $x = 2\;\text{m}$ is', '$12\;\text{J}$', '$8\;\text{J}$', '$6\;\text{J}$', '$4\;\text{J}$', 'option2', '$W = \int_0^2 3x^2\;dx = [x^3]_0^2 = 8\;\text{J}$.', 'p_work_ke_pe_theorem', 2, 'JEE Mains Prep', 'approved'),
('If KE of a body is doubled, its momentum becomes', 'Half', '$2$ times', '$4$ times', '$\sqrt{2}$ times', 'option4', '$KE = p^2/(2m)$. If $KE'' = 2KE$, then $p'' = \sqrt{2}p$.', 'p_work_ke_pe_theorem', 2, 'JEE Mains Prep', 'approved'),
('A force $F = (2x + 3)\;\text{N}$ acts on a body. Work done from $x = 1$ to $x = 5\;\text{m}$ is', '$40\;\text{J}$', '$24\;\text{J}$', '$36\;\text{J}$', '$28\;\text{J}$', 'option3', '$W = \int_1^5(2x+3)dx = [x^2+3x]_1^5 = (25+15)-(1+3) = 40-4 = 36\;\text{J}$.', 'p_work_ke_pe_theorem', 3, 'JEE Mains Prep', 'approved'),
('A $2\;\text{kg}$ body at $10\;\text{m/s}$ is acted on by a retarding force $F = -0.1v^2$. Distance before speed halves is', '$5\ln 2\;\text{m}$', '$10\ln 2\;\text{m}$', '$40\ln 2\;\text{m}$', '$20\ln 2\;\text{m}$', 'option4', '$ma = -0.1v^2$. $m\;v\;dv/ds = -0.1v^2$. $2\;dv/v = -0.1\;ds$. $\int_{10}^{5} 2/v\;dv = -0.1s$. $2\ln(5/10) = -0.1s$. $s = 2\ln 2/0.1 = 20\ln 2\;\text{m}$.', 'p_work_ke_pe_theorem', 3, 'JEE Mains Prep', 'approved'),
('Two bodies of masses $m$ and $4m$ have equal KE. Ratio of their momenta is', '$1:1$', '$1:4$', '$2:1$', '$1:2$', 'option4', '$p = \sqrt{2mKE}$. Ratio $= \sqrt{m}:\sqrt{4m} = 1:2$.', 'p_work_ke_pe_theorem', 3, 'JEE Mains Prep', 'approved'),
('A chain of length $L$ and mass $M$ lies on a table with $1/3$ hanging. Work to pull it fully onto the table is', '$MgL/3$', '$MgL/6$', '$MgL/9$', '$MgL/18$', 'option4', 'Mass hanging $= M/3$, its CM is $L/6$ below table. $W = (M/3)g(L/6) = MgL/18$.', 'p_work_ke_pe_theorem', 3, 'JEE Mains Prep', 'approved'),
('Power delivered to a body of mass $m$ by a constant force $F$ starting from rest at time $t$ is', '$Ft/m$', '$F^2 t/m$', '$F^2/(mt)$', '$Fmt$', 'option2', '$v = Ft/m$. Power $= Fv = F \times Ft/m = F^2 t/m$.', 'p_work_ke_pe_theorem', 3, 'JEE Mains Prep', 'approved'),

-- ============================================================
-- p_spring_pe_conservation (5 easy, 5 medium, 5 hard = 15)
-- ============================================================
('The potential energy stored in a spring compressed by $x$ with spring constant $k$ is', '$kx$', '$\frac{1}{2}kx^2$', '$kx^2$', '$\frac{1}{2}kx$', 'option2', 'Spring PE $= \frac{1}{2}kx^2$.', 'p_spring_pe_conservation', 1, 'JEE Mains Prep', 'approved'),
('A conservative force is one for which', 'Work done is path-independent', 'Work done is always zero', 'Force is constant', 'Force is always perpendicular to motion', 'option1', 'For conservative forces, work depends only on initial and final positions, not the path.', 'p_spring_pe_conservation', 1, 'JEE Mains Prep', 'approved'),
('Which of the following is a non-conservative force?', 'Gravity', 'Friction', 'Spring force', 'Electrostatic force', 'option2', 'Friction is non-conservative: work done depends on the path taken.', 'p_spring_pe_conservation', 1, 'JEE Mains Prep', 'approved'),
('A spring with $k = 200\;\text{N/m}$ is compressed $0.1\;\text{m}$. PE stored is', '$1\;\text{J}$', '$2\;\text{J}$', '$10\;\text{J}$', '$0.1\;\text{J}$', 'option1', '$PE = \frac{1}{2}(200)(0.01) = 1\;\text{J}$.', 'p_spring_pe_conservation', 1, 'JEE Mains Prep', 'approved'),
('In the absence of non-conservative forces, total mechanical energy is', 'Zero', 'Increasing', 'Decreasing', 'Conserved', 'option4', 'When only conservative forces act, $KE + PE = \text{constant}$.', 'p_spring_pe_conservation', 1, 'JEE Mains Prep', 'approved'),
('A $1\;\text{kg}$ ball is dropped from $5\;\text{m}$. Speed just before hitting ground is ($g = 10\;\text{m/s}^2$)', '$20\;\text{m/s}$', '$5\;\text{m/s}$', '$\sqrt{50}\;\text{m/s}$', '$10\;\text{m/s}$', 'option4', '$mgh = \frac{1}{2}mv^2 \Rightarrow v = \sqrt{2gh} = \sqrt{100} = 10\;\text{m/s}$.', 'p_spring_pe_conservation', 2, 'JEE Mains Prep', 'approved'),
('A spring ($k = 500\;\text{N/m}$) launches a $0.5\;\text{kg}$ ball from compression $0.2\;\text{m}$. Speed of ball is', '$20\;\text{m/s}$', '$10\;\text{m/s}$', '$4\;\text{m/s}$', '$\approx 6.32\;\text{m/s}$', 'option4', '$\frac{1}{2}kx^2 = \frac{1}{2}mv^2$. $v = x\sqrt{k/m} = 0.2\sqrt{1000} = 0.2 \times 31.6 \approx 6.32\;\text{m/s}$.', 'p_spring_pe_conservation', 2, 'JEE Mains Prep', 'approved'),
('A ball slides down a frictionless track from height $h$ and goes around a vertical loop of radius $r$. Minimum $h$ for complete loop is', '$3r$', '$2r$', '$r$', '$5r/2$', 'option4', 'At top of loop: $v_{top} = \sqrt{gr}$. Energy: $mgh = mg(2r) + \frac{1}{2}m(gr)$. $h = 2r + r/2 = 5r/2$.', 'p_spring_pe_conservation', 2, 'JEE Mains Prep', 'approved'),
('A pendulum of length $1\;\text{m}$ is released from $60°$. Speed at the lowest point is ($g = 10\;\text{m/s}^2$)', '$\sqrt{5}\;\text{m/s}$', '$\sqrt{20}\;\text{m/s}$', '$\sqrt{10}\;\text{m/s}$', '$10\;\text{m/s}$', 'option3', 'Height $= l(1-\cos 60°) = 1(1-0.5) = 0.5\;\text{m}$. $v = \sqrt{2gh} = \sqrt{10}\;\text{m/s}$.', 'p_spring_pe_conservation', 2, 'JEE Mains Prep', 'approved'),
('If the spring constant is doubled and compression is halved, the PE becomes', 'Quarter', 'Same', 'Double', 'Half', 'option4', '$PE = \frac{1}{2}kx^2$. New $PE = \frac{1}{2}(2k)(x/2)^2 = \frac{1}{2}(2k)(x^2/4) = kx^2/4 = \frac{1}{2} \times \frac{1}{2}kx^2$. So PE is halved.', 'p_spring_pe_conservation', 2, 'JEE Mains Prep', 'approved'),
('A block of mass $m$ slides down a rough incline of height $h$ ($\mu_k$, angle $\theta$). Speed at bottom is', '$\sqrt{2g(h - \mu_k)}$', '$\sqrt{2gh}$', '$\sqrt{2gh(1 - \mu_k\cot\theta)}$', '$\sqrt{gh}$', 'option3', 'Friction work $= \mu_k mg\cos\theta \times h/\sin\theta = \mu_k mgh\cot\theta$. $mgh - \mu_k mgh\cot\theta = \frac{1}{2}mv^2$. $v = \sqrt{2gh(1-\mu_k\cot\theta)}$.', 'p_spring_pe_conservation', 3, 'JEE Mains Prep', 'approved'),
('Two springs $k_1$ and $k_2$ in series store total PE $= U$ when compressed by $x$. The PE in spring $k_1$ is', '$Uk_1 k_2$', '$Uk_1/(k_1+k_2)$', '$U/2$', '$Uk_2/(k_1+k_2)$', 'option4', 'In series, same force $F$ in both. $x_1 = F/k_1$, $x_2 = F/k_2$. $U_1 = \frac{1}{2}k_1 x_1^2 = F^2/(2k_1)$. $U = F^2/(2k_{eq}) = F^2(k_1+k_2)/(2k_1 k_2)$. $U_1/U = k_2/(k_1+k_2)$.', 'p_spring_pe_conservation', 3, 'JEE Mains Prep', 'approved'),
('A particle moves under $F = -kx^3$. The PE function (with $U(0) = 0$) is', '$-kx^4/4$', '$kx^3/3$', '$kx^4/4$', '$kx^2/2$', 'option3', '$U = -\int F\;dx = -\int(-kx^3)dx = kx^4/4 + C$. With $U(0) = 0$: $U = kx^4/4$.', 'p_spring_pe_conservation', 3, 'JEE Mains Prep', 'approved'),
('A $2\;\text{kg}$ block compresses a spring ($k = 800\;\text{N/m}$) by $0.1\;\text{m}$ on a rough surface ($\mu = 0.3$). Distance the block travels after release is ($g = 10\;\text{m/s}^2$)', '$0.5\;\text{m}$', '$\approx 0.67\;\text{m}$', '$1\;\text{m}$', '$0.4\;\text{m}$', 'option2', 'Spring PE $= \frac{1}{2}(800)(0.01) = 4\;\text{J}$. Friction force $= 0.3(2)(10) = 6\;\text{N}$. Distance $= 4/6 = 0.67\;\text{m}$.', 'p_spring_pe_conservation', 3, 'JEE Mains Prep', 'approved'),
('A ball on a string in a vertical circle. Tension at bottom minus tension at top equals', '$2mg$', '$3mg$', '$mg$', '$6mg$', 'option4', 'At bottom: $T_B = mv_B^2/r + mg$. At top: $T_T = mv_T^2/r - mg$. $T_B - T_T = m(v_B^2 - v_T^2)/r + 2mg$. Energy: $v_B^2 - v_T^2 = 4gr$. So $T_B - T_T = 4mg + 2mg = 6mg$.', 'p_spring_pe_conservation', 3, 'JEE Mains Prep', 'approved'),

-- ============================================================
-- p_collisions (5 easy, 5 medium, 5 hard = 15)
-- ============================================================
('In a perfectly elastic collision', 'Both KE and momentum are conserved', 'Only momentum is conserved', 'Only KE is conserved', 'Neither is conserved', 'option1', 'Elastic collision: both kinetic energy and momentum are conserved.', 'p_collisions', 1, 'JEE Mains Prep', 'approved'),
('In a perfectly inelastic collision, the bodies', 'Stick together', 'Bounce back', 'Pass through each other', 'Remain stationary', 'option1', 'In a perfectly inelastic collision, the bodies stick together and move with a common velocity.', 'p_collisions', 1, 'JEE Mains Prep', 'approved'),
('The coefficient of restitution for a perfectly elastic collision is', '$0$', '$1$', '$0.5$', '$\infty$', 'option2', '$e = 1$ for perfectly elastic, $e = 0$ for perfectly inelastic.', 'p_collisions', 1, 'JEE Mains Prep', 'approved'),
('A $1\;\text{kg}$ ball at $4\;\text{m/s}$ hits a wall and rebounds at $4\;\text{m/s}$. Change in momentum is', '$0$', '$8\;\text{kg}\cdot\text{m/s}$', '$4\;\text{kg}\cdot\text{m/s}$', '$16\;\text{kg}\cdot\text{m/s}$', 'option2', '$\Delta p = m(v_f - v_i) = 1(4 - (-4)) = 8\;\text{kg}\cdot\text{m/s}$.', 'p_collisions', 1, 'JEE Mains Prep', 'approved'),
('In any collision, which quantity is always conserved?', 'Momentum', 'Kinetic energy', 'Potential energy', 'Speed', 'option1', 'Momentum is conserved in all collisions (elastic and inelastic) when no external force acts.', 'p_collisions', 1, 'JEE Mains Prep', 'approved'),
('A ball dropped from height $h$ bounces to height $h/4$. Coefficient of restitution is', '$1/2$', '$1/\sqrt{2}$', '$1/4$', '$\sqrt{2}$', 'option1', '$e = \sqrt{h''/h} = \sqrt{(h/4)/h} = \sqrt{1/4} = 1/2$.', 'p_collisions', 2, 'JEE Mains Prep', 'approved'),
('In elastic collision of mass $m$ with mass $2m$ at rest, fraction of KE transferred is', '$8/9$', '$1/2$', '$4/9$', '$1/9$', 'option1', '$v_2 = 2m_1 u/(m_1+m_2) = 2mu/(3m) = 2u/3$. KE transferred $= \frac{1}{2}(2m)(2u/3)^2 = 4mu^2/9$. Original KE $= mu^2/2$. Fraction $= (4/9)/(1/2) = 8/9$.', 'p_collisions', 2, 'JEE Mains Prep', 'approved'),
('Two identical balls collide obliquely. One is at rest. After elastic collision, the angle between their velocities is', '$60°$', '$90°$', '$180°$', '$45°$', 'option2', 'In elastic collision of equal masses where one is at rest, the velocities after collision are perpendicular.', 'p_collisions', 2, 'JEE Mains Prep', 'approved'),
('A $3\;\text{kg}$ body at $4\;\text{m/s}$ collides head-on elastically with a $1\;\text{kg}$ body at rest. Velocity of $3\;\text{kg}$ body after collision is', '$0\;\text{m/s}$', '$1\;\text{m/s}$', '$3\;\text{m/s}$', '$2\;\text{m/s}$', 'option4', '$v_1 = (m_1-m_2)u_1/(m_1+m_2) = (3-1)(4)/(3+1) = 8/4 = 2\;\text{m/s}$.', 'p_collisions', 2, 'JEE Mains Prep', 'approved'),
('In a head-on elastic collision, a light particle ($m$) hits a heavy particle ($M \gg m$) at rest. The light particle', 'Rebounds with nearly the same speed', 'Stops', 'Continues with same speed', 'Moves at half speed', 'option1', '$v_1 = (m-M)u/(m+M) \approx -u$ when $M \gg m$. The light particle rebounds with nearly the same speed.', 'p_collisions', 2, 'JEE Mains Prep', 'approved'),
('A neutron ($m$) collides elastically head-on with a carbon nucleus ($12m$) at rest. Fraction of KE retained by neutron is', '$1/2$', '$(1/13)^2$', '$11/13$', '$(11/13)^2$', 'option4', '$v_1 = (m-12m)u/(m+12m) = -11u/13$. KE retained $= \frac{1}{2}m(11u/13)^2/(\frac{1}{2}mu^2) = (11/13)^2$.', 'p_collisions', 3, 'JEE Mains Prep', 'approved'),
('A ball of mass $m$ at velocity $v$ collides with a stationary ball of mass $m$. If $e = 1/2$, velocities after collision are', '$3v/4$ and $v/4$', '$v/2$ and $v/2$', '$v$ and $0$', '$v/4$ and $3v/4$', 'option4', 'Momentum: $mv = mv_1 + mv_2 \Rightarrow v_1 + v_2 = v$. Restitution: $v_2 - v_1 = ev = v/2$. Solving: $v_1 = v/4$, $v_2 = 3v/4$.', 'p_collisions', 3, 'JEE Mains Prep', 'approved'),
('A ball dropped from height $h$ onto a floor with $e = 0.8$. Height after 2nd bounce is', '$0.41h$', '$0.64h$', '$0.8h$', '$0.51h$', 'option1', 'After each bounce, height $= e^2 \times$ previous height. After 2nd bounce: $h_2 = e^4 h = (0.8)^4 h = 0.4096h \approx 0.41h$.', 'p_collisions', 3, 'JEE Mains Prep', 'approved'),
('A particle of mass $m$ moving at $v$ collides elastically with a stationary particle of mass $3m$. The maximum percentage of KE transferred is', '$25\%$', '$100\%$', '$50\%$', '$75\%$', 'option4', '$v_2 = 2m_1 u/(m_1+m_2) = 2mv/(4m) = v/2$. KE transferred $= \frac{1}{2}(3m)(v/2)^2 = 3mv^2/8$. Original KE $= mv^2/2$. Fraction $= (3/8)/(1/2) = 3/4 = 75\%$.', 'p_collisions', 3, 'JEE Mains Prep', 'approved'),
('Two particles of masses $m$ and $2m$ move towards each other with speeds $2v$ and $v$ respectively. After perfectly inelastic collision, the speed of the combined mass is', '$v/3$', '$0$', '$v$', '$4v/3$', 'option2', 'Taking $m$ direction as positive: $p = m(2v) + 2m(-v) = 2mv - 2mv = 0$. Combined mass $= 3m$. Speed $= 0/3m = 0$.', 'p_collisions', 3, 'JEE Mains Prep', 'approved'),

-- ============================================================
-- p_centre_of_mass (5 easy, 5 medium, 5 hard = 15)
-- ============================================================
('The centre of mass of a uniform rod lies at', 'One end', 'Its midpoint', 'One-third from an end', 'One-quarter from an end', 'option2', 'By symmetry, the CM of a uniform rod is at its geometric centre (midpoint).', 'p_centre_of_mass', 1, 'JEE Mains Prep', 'approved'),
('Two particles of masses $1\;\text{kg}$ and $3\;\text{kg}$ are at $x = 0$ and $x = 4\;\text{m}$. The CM is at', '$x = 3\;\text{m}$', '$x = 2\;\text{m}$', '$x = 1\;\text{m}$', '$x = 4\;\text{m}$', 'option1', '$x_{cm} = (1 \times 0 + 3 \times 4)/(1+3) = 12/4 = 3\;\text{m}$.', 'p_centre_of_mass', 1, 'JEE Mains Prep', 'approved'),
('The centre of mass of a uniform circular disc is at', 'Outside the disc', 'On the circumference', 'Its geometric centre', 'At the edge', 'option3', 'By symmetry, the CM of a uniform disc is at its geometric centre.', 'p_centre_of_mass', 1, 'JEE Mains Prep', 'approved'),
('If no external force acts on a system, its centre of mass', 'Oscillates', 'Accelerates', 'Remains at origin', 'Moves with constant velocity', 'option4', 'No external force means $\vec{F}_{ext} = 0$, so $\vec{a}_{cm} = 0$ and CM moves with constant velocity (or stays at rest).', 'p_centre_of_mass', 1, 'JEE Mains Prep', 'approved'),
('Three equal masses are placed at the vertices of an equilateral triangle. The CM is at', 'Outside the triangle', 'One vertex', 'The midpoint of one side', 'The centroid', 'option4', 'By symmetry, the CM of three equal masses at vertices of an equilateral triangle is at the centroid.', 'p_centre_of_mass', 1, 'JEE Mains Prep', 'approved'),
('Two particles of masses $2\;\text{kg}$ and $3\;\text{kg}$ are at $(1, 2)$ and $(4, 1)$. The $x$-coordinate of CM is', '$3.0$', '$2.5$', '$2.8$', '$1.6$', 'option3', '$x_{cm} = (2 \times 1 + 3 \times 4)/(2+3) = (2+12)/5 = 14/5 = 2.8$.', 'p_centre_of_mass', 2, 'JEE Mains Prep', 'approved'),
('A $60\;\text{kg}$ person stands at one end of a $4\;\text{m}$, $40\;\text{kg}$ boat on frictionless water. If the person walks to the other end, the boat moves', '$1.6\;\text{m}$', '$4\;\text{m}$', '$2.4\;\text{m}$', '$0\;\text{m}$', 'option3', 'CM is fixed. Person moves $4\;\text{m}$ relative to boat. Boat displacement $= 60 \times 4/(60+40) = 2.4\;\text{m}$ (opposite direction).', 'p_centre_of_mass', 2, 'JEE Mains Prep', 'approved'),
('The CM of a uniform semicircular wire of radius $R$ is at distance from the centre', '$2R/\pi$', '$R/2$', '$4R/(3\pi)$', '$R/\pi$', 'option1', 'For a semicircular wire: $y_{cm} = 2R/\pi$ from the centre along the axis of symmetry.', 'p_centre_of_mass', 2, 'JEE Mains Prep', 'approved'),
('Masses $1, 2, 3\;\text{kg}$ are at $(0,0)$, $(1,0)$, $(0,1)$. The CM coordinates are', '$(1/3, 1/2)$', '$(1/2, 1/3)$', '$(1/2, 1/2)$', '$(1/3, 1/3)$', 'option1', '$x_{cm} = (0+2+0)/6 = 1/3$. $y_{cm} = (0+0+3)/6 = 1/2$. CM $= (1/3, 1/2)$.', 'p_centre_of_mass', 2, 'JEE Mains Prep', 'approved'),
('A uniform disc of radius $R$ has a circular hole of radius $R/2$ cut from one edge. The CM shifts from the original centre by', '$R/3$', '$R/4$', '$R/6$', '$R/2$', 'option3', 'Mass of disc $= M$, hole mass $= M/4$ (area ratio). Hole centre at $R/2$ from disc centre. $x_{cm} = -\frac{(M/4)(R/2)}{M - M/4} = -\frac{MR/8}{3M/4} = -R/6$. Shift $= R/6$.', 'p_centre_of_mass', 2, 'JEE Mains Prep', 'approved'),
('The CM of a uniform solid hemisphere of radius $R$ is at distance from the flat face', '$3R/8$', '$R/2$', '$R/4$', '$3R/(4\pi)$', 'option1', 'For a solid hemisphere, $y_{cm} = 3R/8$ from the flat face (standard result by integration).', 'p_centre_of_mass', 3, 'JEE Mains Prep', 'approved'),
('The CM of a uniform semicircular disc of radius $R$ from the centre is', '$R/2$', '$2R/\pi$', '$4R/(3\pi)$', '$3R/8$', 'option3', 'For a semicircular disc: $y_{cm} = 4R/(3\pi)$ from the diameter (standard result).', 'p_centre_of_mass', 3, 'JEE Mains Prep', 'approved'),
('A uniform triangular lamina has vertices at $(0,0)$, $(a,0)$, $(0,b)$. Its CM is at', '$(a/3, b/3)$', '$(a/2, b/2)$', '$(a/4, b/4)$', '$(a/3, b/2)$', 'option1', 'CM of a triangular lamina is at the centroid: $(\bar{x}, \bar{y}) = ((0+a+0)/3, (0+0+b)/3) = (a/3, b/3)$.', 'p_centre_of_mass', 3, 'JEE Mains Prep', 'approved'),
('A uniform square plate of side $a$ has a square of side $a/2$ removed from one corner. The CM shifts from the original centre by', '$a/(4\sqrt{2}) \times 1/3$', '$a/6$', '$a/4$', '$a\sqrt{2}/12$', 'option4', 'Removed mass $= M/4$ at distance $a/(4\sqrt{2}) \times \sqrt{2} = a/4$ diagonally from centre. Actually: removed square CM is at $(a/4, a/4)$ from corner, i.e., at distance $a/4$ from plate centre along both axes. $\Delta x = (M/4)(a/4)/(3M/4) = a/12$. Similarly $\Delta y = a/12$. Net shift $= a\sqrt{2}/12$.', 'p_centre_of_mass', 3, 'JEE Mains Prep', 'approved'),
('The CM of a uniform solid cone of height $h$ from the base is', '$h/2$', '$h/3$', '$h/4$', '$3h/4$', 'option3', 'For a solid cone, $y_{cm} = h/4$ from the base (standard result by integration).', 'p_centre_of_mass', 3, 'JEE Mains Prep', 'approved'),

-- ============================================================
-- p_torque_angular_momentum (5 easy, 5 medium, 5 hard = 15)
-- ============================================================
('Torque is defined as', '$\vec{r} \cdot \vec{F}$', '$\vec{F} \times \vec{r}$', '$\vec{r} \times \vec{F}$', '$\vec{F} / \vec{r}$', 'option3', 'Torque $\vec{\tau} = \vec{r} \times \vec{F}$ (cross product of position vector and force).', 'p_torque_angular_momentum', 1, 'JEE Mains Prep', 'approved'),
('The SI unit of torque is', '$\text{kg}\cdot\text{m/s}$', '$\text{N/m}$', '$\text{N}\cdot\text{m}$', '$\text{J/s}$', 'option3', 'Torque $= rF\sin\theta$, so its unit is Newton-metre ($\text{N}\cdot\text{m}$).', 'p_torque_angular_momentum', 1, 'JEE Mains Prep', 'approved'),
('Angular momentum of a particle is $\vec{L} =$', '$\vec{p} \times \vec{r}$', '$\vec{r} \times \vec{p}$', '$\vec{r} \cdot \vec{p}$', '$m\vec{r}$', 'option2', 'Angular momentum $\vec{L} = \vec{r} \times \vec{p} = \vec{r} \times m\vec{v}$.', 'p_torque_angular_momentum', 1, 'JEE Mains Prep', 'approved'),
('A force of $10\;\text{N}$ acts at $0.5\;\text{m}$ from the pivot, perpendicular to the lever. Torque is', '$0.5\;\text{N}\cdot\text{m}$', '$20\;\text{N}\cdot\text{m}$', '$10\;\text{N}\cdot\text{m}$', '$5\;\text{N}\cdot\text{m}$', 'option4', '$\tau = rF\sin 90° = 0.5 \times 10 = 5\;\text{N}\cdot\text{m}$.', 'p_torque_angular_momentum', 1, 'JEE Mains Prep', 'approved'),
('If net external torque on a system is zero, which quantity is conserved?', 'Angular momentum', 'Linear momentum', 'Kinetic energy', 'Torque', 'option1', 'When $\vec{\tau}_{ext} = 0$, $d\vec{L}/dt = 0$, so angular momentum is conserved.', 'p_torque_angular_momentum', 1, 'JEE Mains Prep', 'approved'),
('A $2\;\text{kg}$ particle moves at $3\;\text{m/s}$ in a circle of radius $0.5\;\text{m}$. Its angular momentum is', '$6\;\text{kg}\cdot\text{m}^2/\text{s}$', '$1.5\;\text{kg}\cdot\text{m}^2/\text{s}$', '$3\;\text{kg}\cdot\text{m}^2/\text{s}$', '$0.5\;\text{kg}\cdot\text{m}^2/\text{s}$', 'option3', '$L = mvr = 2 \times 3 \times 0.5 = 3\;\text{kg}\cdot\text{m}^2/\text{s}$.', 'p_torque_angular_momentum', 2, 'JEE Mains Prep', 'approved'),
('A disc of moment of inertia $I$ rotates at $\omega$. A second identical disc (initially at rest) is placed on it. New angular velocity is', '$\omega$', '$\omega/2$', '$2\omega$', '$\omega/4$', 'option2', 'Conservation of angular momentum: $I\omega = 2I\omega''$. $\omega'' = \omega/2$.', 'p_torque_angular_momentum', 2, 'JEE Mains Prep', 'approved'),
('The relation between torque and angular momentum is', '$\vec{\tau} = \vec{L}/t$', '$\vec{\tau} = d\vec{L}/dt$', '$\vec{\tau} = \vec{L} \times \vec{\omega}$', '$\vec{\tau} = I\vec{L}$', 'option2', 'Newton''s second law for rotation: $\vec{\tau} = d\vec{L}/dt$.', 'p_torque_angular_momentum', 2, 'JEE Mains Prep', 'approved'),
('A torque of $10\;\text{N}\cdot\text{m}$ acts on a body of $I = 2\;\text{kg}\cdot\text{m}^2$. Angular acceleration is', '$20\;\text{rad/s}^2$', '$5\;\text{rad/s}^2$', '$0.2\;\text{rad/s}^2$', '$12\;\text{rad/s}^2$', 'option2', '$\alpha = \tau/I = 10/2 = 5\;\text{rad/s}^2$.', 'p_torque_angular_momentum', 2, 'JEE Mains Prep', 'approved'),
('A particle of mass $m$ moves with velocity $v$ along a line at perpendicular distance $d$ from a point O. Its angular momentum about O is', '$mvd$', '$mv/d$', '$md/v$', '$mv^2 d$', 'option1', '$L = mvr_\perp = mvd$ where $d$ is the perpendicular distance from O to the line of motion.', 'p_torque_angular_momentum', 2, 'JEE Mains Prep', 'approved'),
('An ice skater with arms extended has $I = 6\;\text{kg}\cdot\text{m}^2$ at $2\;\text{rad/s}$. She pulls arms in to $I = 2\;\text{kg}\cdot\text{m}^2$. New angular velocity is', '$4\;\text{rad/s}$', '$6\;\text{rad/s}$', '$3\;\text{rad/s}$', '$12\;\text{rad/s}$', 'option2', '$L = I_1\omega_1 = I_2\omega_2$. $6 \times 2 = 2\omega_2$. $\omega_2 = 6\;\text{rad/s}$.', 'p_torque_angular_momentum', 3, 'JEE Mains Prep', 'approved'),
('A uniform rod of mass $M$ and length $L$ is pivoted at one end and released from horizontal. Angular velocity at the lowest point is', '$\sqrt{3g/L}$', '$\sqrt{2g/L}$', '$\sqrt{g/L}$', '$\sqrt{6g/L}$', 'option1', 'CM falls $L/2$. Energy: $Mg(L/2) = \frac{1}{2}I\omega^2 = \frac{1}{2}(ML^2/3)\omega^2$. $\omega = \sqrt{3g/L}$.', 'p_torque_angular_momentum', 3, 'JEE Mains Prep', 'approved'),
('A disc rotates at $\omega_0$ and is brought to rest by a constant torque in $t$ seconds. The number of revolutions is', '$\omega_0 t/\pi$', '$\omega_0 t/(2\pi)$', '$\omega_0^2 t/(4\pi)$', '$\omega_0 t/(4\pi)$', 'option4', '$\alpha = \omega_0/t$. $\theta = \omega_0 t - \frac{1}{2}(\omega_0/t)t^2 = \omega_0 t/2$. Revolutions $= \theta/(2\pi) = \omega_0 t/(4\pi)$.', 'p_torque_angular_momentum', 3, 'JEE Mains Prep', 'approved'),
('A turntable ($I = 4\;\text{kg}\cdot\text{m}^2$) rotates at $3\;\text{rad/s}$. A $2\;\text{kg}$ mass is placed at $1\;\text{m}$ from centre. New angular velocity is', '$2\;\text{rad/s}$', '$1.5\;\text{rad/s}$', '$3\;\text{rad/s}$', '$2.4\;\text{rad/s}$', 'option1', '$I_2 = 4 + 2(1)^2 = 6\;\text{kg}\cdot\text{m}^2$. $L = 4 \times 3 = 12$. $\omega_2 = 12/6 = 2\;\text{rad/s}$.', 'p_torque_angular_momentum', 3, 'JEE Mains Prep', 'approved'),
('A particle moves in a plane with $\vec{r} = 3\hat{i} + 4\hat{j}$ m and $\vec{p} = 2\hat{i} - \hat{j}$ kg$\cdot$m/s. Its angular momentum about the origin is', '$5\hat{k}\;\text{kg}\cdot\text{m}^2/\text{s}$', '$11\hat{k}\;\text{kg}\cdot\text{m}^2/\text{s}$', '$-5\hat{k}\;\text{kg}\cdot\text{m}^2/\text{s}$', '$-11\hat{k}\;\text{kg}\cdot\text{m}^2/\text{s}$', 'option4', '$\vec{L} = \vec{r} \times \vec{p} = (3\hat{i}+4\hat{j}) \times (2\hat{i}-\hat{j}) = 3(-1)\hat{k} + 4(2)(-\hat{k}) = -3\hat{k} - 8\hat{k} = -11\hat{k}$.', 'p_torque_angular_momentum', 3, 'JEE Mains Prep', 'approved'),

-- ============================================================
-- p_moment_of_inertia (5 easy, 5 medium, 5 hard = 15)
-- ============================================================
('Moment of inertia depends on', 'Mass distribution about the axis', 'Total mass only', 'Shape only', 'Angular velocity', 'option1', 'Moment of inertia depends on both the mass and how it is distributed relative to the axis of rotation.', 'p_moment_of_inertia', 1, 'JEE Mains Prep', 'approved'),
('The moment of inertia of a point mass $m$ at distance $r$ from the axis is', '$mr^2$', '$mr$', '$m/r^2$', '$m^2 r$', 'option1', '$I = mr^2$ for a point mass at distance $r$ from the axis.', 'p_moment_of_inertia', 1, 'JEE Mains Prep', 'approved'),
('The SI unit of moment of inertia is', '$\text{kg}\cdot\text{m}$', '$\text{kg}\cdot\text{m}^2$', '$\text{N}\cdot\text{m}^2$', '$\text{kg/m}^2$', 'option2', '$I = \sum mr^2$, so its unit is $\text{kg}\cdot\text{m}^2$.', 'p_moment_of_inertia', 1, 'JEE Mains Prep', 'approved'),
('The moment of inertia of a uniform ring of mass $M$ and radius $R$ about its axis is', '$MR^2$', '$\frac{1}{2}MR^2$', '$\frac{2}{5}MR^2$', '$\frac{1}{4}MR^2$', 'option1', 'All mass of a ring is at distance $R$ from the axis. $I = MR^2$.', 'p_moment_of_inertia', 1, 'JEE Mains Prep', 'approved'),
('The rotational kinetic energy of a body is', '$\frac{1}{2}I\omega^2$', '$I\omega$', '$\frac{1}{2}I\omega$', '$I\omega^2$', 'option1', 'Rotational KE $= \frac{1}{2}I\omega^2$, analogous to $\frac{1}{2}mv^2$.', 'p_moment_of_inertia', 1, 'JEE Mains Prep', 'approved'),
('The moment of inertia of a uniform disc of mass $M$ and radius $R$ about its axis is', '$\frac{1}{2}MR^2$', '$MR^2$', '$\frac{1}{4}MR^2$', '$\frac{2}{5}MR^2$', 'option1', 'For a uniform disc about its central axis: $I = \frac{1}{2}MR^2$.', 'p_moment_of_inertia', 2, 'JEE Mains Prep', 'approved'),
('The moment of inertia of a uniform solid sphere about a diameter is', '$MR^2$', '$\frac{2}{3}MR^2$', '$\frac{1}{2}MR^2$', '$\frac{2}{5}MR^2$', 'option4', 'For a solid sphere about a diameter: $I = \frac{2}{5}MR^2$.', 'p_moment_of_inertia', 2, 'JEE Mains Prep', 'approved'),
('The moment of inertia of a uniform rod of mass $M$ and length $L$ about its centre is', '$ML^2/12$', '$ML^2/3$', '$ML^2/4$', '$ML^2$', 'option1', 'For a uniform rod about its centre: $I = ML^2/12$.', 'p_moment_of_inertia', 2, 'JEE Mains Prep', 'approved'),
('A disc ($I = 0.5\;\text{kg}\cdot\text{m}^2$) rotates at $10\;\text{rad/s}$. Its rotational KE is', '$25\;\text{J}$', '$50\;\text{J}$', '$5\;\text{J}$', '$100\;\text{J}$', 'option1', '$KE = \frac{1}{2}I\omega^2 = \frac{1}{2}(0.5)(100) = 25\;\text{J}$.', 'p_moment_of_inertia', 2, 'JEE Mains Prep', 'approved'),
('The radius of gyration $k$ of a body is defined by', '$k = \sqrt{I}$', '$I = Mk$', '$k = I/M$', '$I = Mk^2$', 'option4', 'Radius of gyration: $I = Mk^2$, so $k = \sqrt{I/M}$.', 'p_moment_of_inertia', 2, 'JEE Mains Prep', 'approved'),
('A solid cylinder and a hollow cylinder of same mass and radius roll down an incline. Which reaches first?', 'Solid cylinder', 'Hollow cylinder', 'Both together', 'Cannot determine', 'option1', 'Acceleration $= g\sin\theta/(1 + I/(MR^2))$. Solid: $I = MR^2/2$, factor $= 3/2$. Hollow: $I = MR^2$, factor $= 2$. Solid has larger acceleration, reaches first.', 'p_moment_of_inertia', 3, 'JEE Mains Prep', 'approved'),
('A disc rolls without slipping. The ratio of rotational KE to total KE is', '$1/3$', '$1/2$', '$2/3$', '$1/4$', 'option1', 'Total KE $= \frac{1}{2}mv^2 + \frac{1}{2}I\omega^2 = \frac{1}{2}mv^2 + \frac{1}{4}mv^2 = \frac{3}{4}mv^2$. Rotational $= \frac{1}{4}mv^2$. Ratio $= (1/4)/(3/4) = 1/3$.', 'p_moment_of_inertia', 3, 'JEE Mains Prep', 'approved'),
('A solid sphere rolls without slipping down an incline of height $h$. Speed at bottom is', '$\sqrt{5gh/3}$', '$\sqrt{2gh}$', '$\sqrt{gh}$', '$\sqrt{10gh/7}$', 'option4', '$mgh = \frac{1}{2}mv^2 + \frac{1}{2}(\frac{2}{5}mR^2)(v/R)^2 = \frac{7}{10}mv^2$. $v = \sqrt{10gh/7}$.', 'p_moment_of_inertia', 3, 'JEE Mains Prep', 'approved'),
('Four particles each of mass $m$ are at corners of a square of side $a$. Moment of inertia about a diagonal is', '$2ma^2$', '$ma^2$', '$4ma^2$', '$ma^2/2$', 'option2', 'Two particles lie on the diagonal (distance $0$). Two are at perpendicular distance $a/\sqrt{2}$ from diagonal. $I = 2m(a/\sqrt{2})^2 = 2m(a^2/2) = ma^2$.', 'p_moment_of_inertia', 3, 'JEE Mains Prep', 'approved'),
('A uniform disc of mass $M$ and radius $R$ has a hole of radius $R/2$ cut at the edge. Its moment of inertia about the original centre axis is', '$13MR^2/32$', '$MR^2/2$', '$3MR^2/8$', '$7MR^2/16$', 'option1', 'Hole mass $= M/4$. Hole MI about its own centre $= \frac{1}{2}(M/4)(R/2)^2 = MR^2/32$. By parallel axis: $I_{hole} = MR^2/32 + (M/4)(R/2)^2 = MR^2/32 + MR^2/16 = 3MR^2/32$. $I = MR^2/2 - 3MR^2/32 = 16MR^2/32 - 3MR^2/32 = 13MR^2/32$.', 'p_moment_of_inertia', 3, 'JEE Mains Prep', 'approved'),

-- ============================================================
-- p_axes_theorems (5 easy, 5 medium, 5 hard = 15)
-- ============================================================
('The parallel axis theorem states $I = I_{cm} +$', '$M/d^2$', '$Md$', '$Md^2$', '$2Md^2$', 'option3', 'Parallel axis theorem: $I = I_{cm} + Md^2$ where $d$ is the distance between the two parallel axes.', 'p_axes_theorems', 1, 'JEE Mains Prep', 'approved'),
('The perpendicular axis theorem applies to', 'All rigid bodies', 'Planar (2D) bodies only', 'Only spheres', 'Only rods', 'option2', 'The perpendicular axis theorem ($I_z = I_x + I_y$) applies only to planar (laminar) bodies.', 'p_axes_theorems', 1, 'JEE Mains Prep', 'approved'),
('For a planar body in the $xy$-plane, the perpendicular axis theorem gives', '$I_z = \sqrt{I_x^2 + I_y^2}$', '$I_z = I_x - I_y$', '$I_z = I_x \times I_y$', '$I_z = I_x + I_y$', 'option4', '$I_z = I_x + I_y$ where $z$ is perpendicular to the plane of the body.', 'p_axes_theorems', 1, 'JEE Mains Prep', 'approved'),
('MI of a ring of mass $M$, radius $R$ about a diameter is', '$MR^2/4$', '$MR^2$', '$MR^2/2$', '$2MR^2$', 'option3', 'By perpendicular axis theorem: $I_{axis} = 2I_{dia}$. $MR^2 = 2I_{dia}$. $I_{dia} = MR^2/2$.', 'p_axes_theorems', 1, 'JEE Mains Prep', 'approved'),
('The parallel axis theorem requires one axis to pass through', 'Any point', 'The centre of mass', 'The edge', 'The geometric centre', 'option2', 'The parallel axis theorem: $I = I_{cm} + Md^2$. One axis must pass through the CM.', 'p_axes_theorems', 1, 'JEE Mains Prep', 'approved'),
('MI of a disc about a diameter is', '$MR^2/4$', '$MR^2/2$', '$MR^2$', '$MR^2/8$', 'option1', 'By perpendicular axis: $I_{axis} = 2I_{dia}$. $MR^2/2 = 2I_{dia}$. $I_{dia} = MR^2/4$.', 'p_axes_theorems', 2, 'JEE Mains Prep', 'approved'),
('MI of a uniform rod about one end is', '$ML^2$', '$ML^2/12$', '$ML^2/4$', '$ML^2/3$', 'option4', 'By parallel axis: $I_{end} = ML^2/12 + M(L/2)^2 = ML^2/12 + ML^2/4 = ML^2/3$.', 'p_axes_theorems', 2, 'JEE Mains Prep', 'approved'),
('MI of a ring about a tangent in its plane is', '$MR^2/2$', '$MR^2$', '$2MR^2$', '$3MR^2/2$', 'option4', '$I_{dia} = MR^2/2$. By parallel axis: $I_{tangent} = MR^2/2 + MR^2 = 3MR^2/2$.', 'p_axes_theorems', 2, 'JEE Mains Prep', 'approved'),
('MI of a disc about a tangent perpendicular to its plane is', '$3MR^2/2$', '$MR^2$', '$MR^2/2$', '$2MR^2$', 'option1', '$I_{axis} = MR^2/2$. By parallel axis: $I = MR^2/2 + MR^2 = 3MR^2/2$.', 'p_axes_theorems', 2, 'JEE Mains Prep', 'approved'),
('MI of a solid sphere about a tangent is', '$2MR^2/5$', '$7MR^2/5$', '$MR^2$', '$9MR^2/5$', 'option2', '$I_{dia} = 2MR^2/5$. By parallel axis: $I = 2MR^2/5 + MR^2 = 7MR^2/5$.', 'p_axes_theorems', 2, 'JEE Mains Prep', 'approved'),
('MI of a hollow sphere (thin shell) of mass $M$, radius $R$ about a diameter is', '$2MR^2/5$', '$MR^2$', '$2MR^2/3$', '$MR^2/2$', 'option3', 'For a thin spherical shell about a diameter: $I = 2MR^2/3$ (standard result).', 'p_axes_theorems', 3, 'JEE Mains Prep', 'approved'),
('MI of a disc about a tangent in its plane is', '$MR^2$', '$3MR^2/4$', '$5MR^2/4$', '$3MR^2/2$', 'option3', '$I_{dia} = MR^2/4$. By parallel axis: $I = MR^2/4 + MR^2 = 5MR^2/4$.', 'p_axes_theorems', 3, 'JEE Mains Prep', 'approved'),
('A uniform square lamina of mass $M$ and side $a$. MI about an axis through centre and perpendicular to plane is', '$Ma^2/4$', '$Ma^2/12$', '$Ma^2/3$', '$Ma^2/6$', 'option4', 'By symmetry $I_x = I_y = Ma^2/12$. By perpendicular axis: $I_z = I_x + I_y = Ma^2/6$.', 'p_axes_theorems', 3, 'JEE Mains Prep', 'approved'),
('MI of a uniform rectangular plate ($M$, sides $a$ and $b$) about an axis through centre parallel to side $b$ is', '$Ma^2/3$', '$Mb^2/12$', '$M(a^2+b^2)/12$', '$Ma^2/12$', 'option4', 'For a rectangular plate, MI about axis parallel to side $b$ through centre $= Ma^2/12$.', 'p_axes_theorems', 3, 'JEE Mains Prep', 'approved'),
('A thin rod of mass $M$ and length $L$ is bent into a ring. MI about the ring axis is', '$ML^2/(4\pi^2)$', '$ML^2/12$', '$ML^2/(2\pi^2)$', '$ML^2/4$', 'option1', 'Ring radius: $2\pi R = L \Rightarrow R = L/(2\pi)$. $I = MR^2 = M L^2/(4\pi^2)$.', 'p_axes_theorems', 3, 'JEE Mains Prep', 'approved'),

-- ============================================================
-- p_rigid_body_equilibrium (5 easy, 5 medium, 5 hard = 15)
-- ============================================================
('For a rigid body in static equilibrium, the net force must be', 'Non-zero', 'Maximum', 'Equal to weight', 'Zero', 'option4', 'Static equilibrium requires $\sum \vec{F} = 0$ (translational) and $\sum \vec{\tau} = 0$ (rotational).', 'p_rigid_body_equilibrium', 1, 'JEE Mains Prep', 'approved'),
('For complete equilibrium of a rigid body, the net torque about any point must be', 'Non-zero', 'Maximum', 'Equal to the net force', 'Zero', 'option4', 'Both $\sum \vec{F} = 0$ and $\sum \vec{\tau} = 0$ are required for static equilibrium.', 'p_rigid_body_equilibrium', 1, 'JEE Mains Prep', 'approved'),
('A uniform beam of weight $W$ is supported at both ends. Each support bears a load of', '$W$', '$W/2$', '$W/4$', '$2W$', 'option2', 'By symmetry, each support bears half the weight: $W/2$.', 'p_rigid_body_equilibrium', 1, 'JEE Mains Prep', 'approved'),
('The condition for rotational equilibrium is', '$\sum \tau = 0$', '$\sum F = 0$', '$\omega = 0$', '$\alpha = \text{constant}$', 'option1', 'Rotational equilibrium requires the net torque about any point to be zero.', 'p_rigid_body_equilibrium', 1, 'JEE Mains Prep', 'approved'),
('A couple consists of', 'Two perpendicular forces', 'Two equal forces in the same direction', 'A single force', 'Two equal and opposite parallel forces', 'option4', 'A couple is a pair of equal, opposite, parallel forces separated by a distance.', 'p_rigid_body_equilibrium', 1, 'JEE Mains Prep', 'approved'),
('A $4\;\text{m}$ uniform beam ($W = 100\;\text{N}$) has a $200\;\text{N}$ load at $1\;\text{m}$ from the left end. Reaction at the left support is', '$200\;\text{N}$', '$100\;\text{N}$', '$150\;\text{N}$', '$250\;\text{N}$', 'option1', 'Torque about right end: $R_L(4) = 100(2) + 200(3) = 200 + 600 = 800$. $R_L = 200\;\text{N}$.', 'p_rigid_body_equilibrium', 2, 'JEE Mains Prep', 'approved'),
('The moment of a couple of forces $F$ separated by distance $d$ is', '$Fd$', '$F/d$', '$2Fd$', '$Fd^2$', 'option1', 'Moment of a couple $= F \times d$ (force times perpendicular distance between forces).', 'p_rigid_body_equilibrium', 2, 'JEE Mains Prep', 'approved'),
('A uniform ladder of length $L$ and weight $W$ leans against a smooth wall at angle $\theta$. Friction force at the floor is', '$W/(2\tan\theta)$', '$W\tan\theta/2$', '$W\cos\theta$', '$W\sin\theta$', 'option1', 'Torque about base: $N_{wall} \times L\sin\theta = W \times (L/2)\cos\theta$. $N_{wall} = W\cos\theta/(2\sin\theta) = W/(2\tan\theta)$. Friction $= N_{wall} = W/(2\tan\theta)$.', 'p_rigid_body_equilibrium', 2, 'JEE Mains Prep', 'approved'),
('A see-saw has a $30\;\text{kg}$ child at $2\;\text{m}$ from the pivot. A $20\;\text{kg}$ child must sit at what distance for balance?', '$4\;\text{m}$', '$2\;\text{m}$', '$3\;\text{m}$', '$1.5\;\text{m}$', 'option3', '$30 \times 2 = 20 \times d$. $d = 60/20 = 3\;\text{m}$.', 'p_rigid_body_equilibrium', 2, 'JEE Mains Prep', 'approved'),
('A uniform plank of mass $M$ extends a distance $d$ beyond the edge of a table. Maximum mass that can be placed at the end without tipping (plank length $L$) is', '$ML/(2d)$', '$Md/L$', '$M(L-d)/d$', '$M(L - 2d)/(2d)$', 'option4', 'Pivot at table edge. Plank CM is at $L/2 - d$ from edge (on table side). Torque balance: $m \times d = M(L/2 - d)$. $m = M(L/2 - d)/d = M(L - 2d)/(2d)$.', 'p_rigid_body_equilibrium', 2, 'JEE Mains Prep', 'approved'),
('A uniform rod of mass $M$ and length $L$ is hinged at one end and held horizontal by a string at the other end making angle $\theta$ with the rod. Tension in the string is', '$Mg/(2\sin\theta)$', '$Mg/\sin\theta$', '$Mg\sin\theta/2$', '$Mg/(2\cos\theta)$', 'option1', 'Torque about hinge: $T\sin\theta \times L = Mg \times L/2$. $T = Mg/(2\sin\theta)$.', 'p_rigid_body_equilibrium', 3, 'JEE Mains Prep', 'approved'),
('A uniform cube of side $a$ is placed on a rough incline. It topples before sliding if $\mu_s$ is greater than', '$0.75$', '$0.5$', '$\tan 30°$', '$\tan\theta$ where $\theta$ satisfies $\tan\theta = 1$, i.e., $\mu_s > 1$', 'option4', 'Cube topples when torque about edge overcomes: $\tan\theta > a/a = 1$. It slides when $\tan\theta > \mu_s$. Topples before sliding if $\mu_s > 1$.', 'p_rigid_body_equilibrium', 3, 'JEE Mains Prep', 'approved'),
('A horizontal beam of length $L$ and weight $W$ is fixed to a wall. A wire at the free end makes $30°$ with horizontal. Tension in wire is', '$W$', '$W/2$', '$W\sqrt{3}$', '$2W$', 'option1', 'Torque about wall: $T\sin 30° \times L = W \times L/2$. $T(1/2) = W/2$. $T = W$.', 'p_rigid_body_equilibrium', 3, 'JEE Mains Prep', 'approved'),
('Three forces $\vec{F}_1$, $\vec{F}_2$, $\vec{F}_3$ act on a body in equilibrium. If $F_1 = 10\;\text{N}$ at $0°$, $F_2 = 10\;\text{N}$ at $120°$, then $F_3$ is', '$10\;\text{N}$ at $240°$', '$20\;\text{N}$ at $180°$', '$10\;\text{N}$ at $180°$', '$10\sqrt{3}\;\text{N}$ at $270°$', 'option1', 'By Lami''s theorem or vector addition: three equal forces at $120°$ apart are in equilibrium. $F_3 = 10\;\text{N}$ at $240°$.', 'p_rigid_body_equilibrium', 3, 'JEE Mains Prep', 'approved'),
('A uniform rod of weight $W$ and length $L$ rests with one end on a smooth floor and the other against a smooth wall, making angle $\theta$ with the floor. A horizontal force $F$ at the floor end keeps it in equilibrium. $F$ equals', '$W/(2\sin\theta)$', '$W\tan\theta/2$', '$W\cot\theta/2$', '$W\cos\theta$', 'option3', 'Torque about floor end: $N_{wall}(L\sin\theta) = W(L\cos\theta/2)$. $N_{wall} = W\cos\theta/(2\sin\theta) = W\cot\theta/2$. Horizontal equilibrium: $F = N_{wall} = W\cot\theta/2$.', 'p_rigid_body_equilibrium', 3, 'JEE Mains Prep', 'approved');